'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const m=require('../src/siteSupport/imweb'),profile=require('../src/siteSupport/profiles.json').find(p=>p.name==='Momos'),fixture=require('./fixtures/siteSupport/momos-kr-product.json'),listing=require('./fixtures/siteSupport/momos-kr-listing.json');
function html(f=fixture){return [f.store,f.primary].map(n=>'<script type="application/ld+json">'+JSON.stringify(n)+'</script>').join('')+'<script>throw new Error("Merchant code must never execute")</script>';}
test('Momos native retail options retain exact KRW totals, market identity, stock and declared net sizes',()=>{
 const source=m.nativeProduct(fixture.native,m.primaryProduct(html(),fixture.url,profile),fixture.url,profile),p=require('../src/catalogNormalization').normalizeProduct(require('../src/extraction').structuredExtraction({html:html(),url:fixture.url,sourceProduct:source}).product,fixture.url);
 assert.match(p.source_product_id,/^imweb:KR:S2026022396690869a4918:s20260713f944d1d0af054$/);assert.equal(p.variants.length,12);assert.equal(p.variants_complete,false);assert.deepEqual(p.variants.map(v=>v.source_id),fixture.native.options_detail.map(v=>v.code));assert.deepEqual(p.variants.map(v=>v.money.minorUnits),[24000,48000,24000,48000,24000,48000,24000,48000,24000,48000,24000,48000]);assert(p.variants.every(v=>v.money.currency==='KRW'&&v.availability==='in_stock'));assert.deepEqual(p.variants.map(v=>v.weight_g),[200,500,200,500,200,500,200,500,200,500,200,500]);
 const sold=structuredClone(fixture.native);sold.options_detail[0].status='SOLDOUT';assert.equal(m.nativeProduct(sold,m.primaryProduct(html(),fixture.url,profile),fixture.url,profile).offers[0].availability,'https://schema.org/OutOfStock');
 for(const mutate of [p=>p.idx++,p=>p.site_code='other-store',p=>p.price++,p=>p.options_detail[0].value_code_list[0]='unproven',p=>p.options_detail[0].price='unknown']){const bad=structuredClone(fixture.native);mutate(bad);assert.throws(()=>m.nativeProduct(bad,m.primaryProduct(html(),fixture.url,profile),fixture.url,profile));}
 const usd=structuredClone(fixture);usd.primary.offers.priceCurrency='USD';assert.throws(()=>m.primaryProduct(html(usd),fixture.url,profile),/price\/currency/);assert.throws(()=>m.primaryProduct(html(),'https://en.momos.co.kr/shop_view?idx=4183',profile),/product missing/);
 assert.equal(m.contentsWeight('<table><tr><td>내용량</td><td>400 g (100 g x 4 ea)</td></tr></table>'),400);assert.equal(m.contentsWeight('<table><tr><td>내용량</td><td>200 g / 500 g</td></tr><tr><td>배송 중량</td><td>10 kg</td></tr></table>'),null);assert.equal(m.contentsWeight('<table><tr><td>내용량</td><td>500 ml</td></tr></table>'),null);
 assert.equal(m.stockState({...fixture.native,use_pre_sale:true},fixture.native.options_detail[0]),null);
});
test('Momos scoped public catalog validates merchant category and exact pagination; English TLS market never grants omission reconciliation',async()=>{
 const p={...profile,listing_paths:['/CoffeeBeans']},home=html()+'<script>window.MOMOS_API_BASE = "https://office.momos.co.kr";</script>',category='<div data-momos-grid data-category="'+p.listing_categories['/CoffeeBeans']+'"></div>';
 const fetchHtml=async u=>({success:true,data:u===p.bootstrap_url?home:u.includes('/api/public/products')?JSON.stringify(listing):category,finalUrl:u});
 const found=await m.discoverImwebProducts({website_url:'https://en.momos.co.kr'},p,fetchHtml);assert.equal(found.complete,true);assert.equal(found.urls.length,22);assert(found.urls.every(u=>u.startsWith('https://momos.co.kr/shop_view?idx=')));assert.equal(profile.bootstrap_url,'https://momos.co.kr');assert.equal(profile.reconcile_omissions,false);assert.equal(found.reconcile_omissions,false);
 const bad=await m.discoverImwebProducts({},p,async u=>({success:true,data:u===p.bootstrap_url?home:u.includes('/api/public/products')?JSON.stringify({...listing,totalCount:23}):category}));assert.equal(bad.complete,false);assert.match(bad.error,/Truncated/);
 assert.equal(m.listingCategory('<div data-momos-grid data-category="other"></div>','/CoffeeBeans',profile),null);
 assert.equal(m.listingCategory('<script>url : (\'/ajax/get_shop_list_view.cm\'); var config={\'menu_url\': \'/InstantCoffee/\', \'category\': \'s20260714322491b8b5ebb\'}</script>','/InstantCoffee',profile),'s20260714322491b8b5ebb');
});
test('captured Momos own-brand blends and optional coffee-mix cup combinations retain native variants',()=>{
 for(const [id,count] of [[2486,18],[7392,4]]){const f=require('./fixtures/siteSupport/momos-kr-'+id+'.json'),p=m.nativeProduct(f.native,m.primaryProduct(html(f),f.url,profile),f.url,profile);assert.equal(p.offers.length,count);assert.equal(p.name,f.primary.name);assert(p.offers.every(o=>o.priceCurrency==='KRW'));assert.deepEqual(p.offers.map(o=>o.availability),f.native.options_detail.map(o=>'https://schema.org/'+(o.status==='SOLDOUT'?'OutOfStock':'InStock')));assert.deepEqual(p.offers.map(o=>o.sku),f.native.options_detail.map(o=>o.code));}
 const f=require('./fixtures/siteSupport/momos-kr-7392.json'),p=m.nativeProduct(f.native,m.primaryProduct(html(f),f.url,profile),f.url,profile);assert.deepEqual(p.offers.map(o=>Number(o.price)),[34000,42000,34100,42100]);assert.deepEqual(p.offers.map(o=>o._net_weight_g),[500,500,500,500]);
});
test('standalone Momos shopping bags and cups misfiled in coffee categories are excluded by their verified native codes',async()=>{
 const p={...profile,listing_paths:['/CoffeeBeans']},home=html()+'<script>window.MOMOS_API_BASE = "https://office.momos.co.kr";</script>',category='<div data-momos-grid data-category="'+p.listing_categories['/CoffeeBeans']+'"></div>',payload=structuredClone(listing);
 payload.items.push({prodNo:4279,prodCode:'s20260713cf43960c3e7d4',name:'모모스커피 쇼핑백',status:'sale',pdpUrl:'/shop_view?idx=4279'},{prodNo:4919,prodCode:'s2026071370e1388d2b2b4',name:'[굿즈] 스페셜티 커피믹스 컵',status:'sale',pdpUrl:'/shop_view?idx=4919'});payload.count=payload.totalCount=24;
 const d=await m.discoverImwebProducts({},p,async u=>({success:true,data:u===p.bootstrap_url?home:u.includes('/api/public/products')?JSON.stringify(payload):category}));assert.equal(d.complete,true);assert.equal(d.urls.length,22);assert(!d.urls.some(u=>/idx=(4279|4919)$/.test(u)));
});
