'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const h=require('./apply-batch8b-four-remaining-fields.cjs'),bundle=h.loadBundle(),clone=x=>JSON.parse(JSON.stringify(x));
function initial(){return {...clone(bundle.baseline),owners:bundle.owners.map(o=>({id:o.entity_id,name:o.name,website_url:o.website_url,metadata:{preserve:'all'}})),roles:bundle.owners.map(o=>({entity_id:o.entity_id,role:'roaster',metadata:{preserve:true}})),sources:bundle.owners.map((o,i)=>({id:'00000000-0000-4000-8000-00000000000'+i,entity_id:o.entity_id,...o.source_ids[0],source_url:o.website_url,raw_data:{untouched:true}})),canonicalOut:[],canonicalIn:[],crawlState:[],activeClaims:[]};}
function response(url,rows,status=200,offset=0){const r=new Response(JSON.stringify(rows),{status,headers:{'content-type':'application/json','content-range':Array.isArray(rows)&&rows.length?`${offset}-${offset+rows.length-1}/*`:'*/*'}});Object.defineProperty(r,'url',{value:url});return r;}
function fixture(state=initial(),options={}){let clock=Date.parse(bundle.source_at)+60000;const calls=[],events=[];const delegate=async(url,req)=>{
 const u=new URL(url),table=u.pathname.split('/').pop(),q=u.searchParams,offset=Number(q.get('offset')||0);calls.push({url,method:req.method,body:req.body&&JSON.parse(req.body)});clock+=50;
 if(options.hook){const override=await options.hook({url,req,state,calls,offset});if(override)return override;}
 if(table==='entity_crawl_state'&&options.absent)return response(url,{code:'PGRST205'},404);
 let key={entities:'owners',entity_roles:'roles',entity_source_ids:'sources',entity_crawl_state:'crawlState',crawl_runs:'activeClaims',products:'parents',product_variants:'variants',coffee_facts:'facts'}[table];let rows=table==='entity_attributes'?(q.has('attribute_value')?state.canonicalIn:state.canonicalOut):state[key];assert(rows,'unknown table');
 const match=r=>[...q].filter(([k])=>!['select','order','limit','offset'].includes(k)).every(([k,v])=>v==='is.null'?r[k]===null:v.startsWith('eq.')?String(r[k])===v.slice(3):v.startsWith('in.(')?v.slice(4,-1).split(',').includes(String(r[k])):false);
 if(req.method==='PATCH'){const hits=rows.filter(match);if(hits.length===1){Object.assign(hits[0],JSON.parse(req.body),{updated_at:new Date(clock).toISOString()});}return response(url,clone(hits));}
 assert.equal(req.method,'GET');rows=rows.filter(match);const order=(q.get('order')||'').split(',').filter(Boolean);rows.sort((a,b)=>{for(const col of order){const k=col.split('.')[0],n=String(a[k]).localeCompare(String(b[k]));if(n)return n;}return 0;});return response(url,clone(rows.slice(offset,offset+Number(q.get('limit')))),200,offset);
 };return{state,calls,events,now:()=>clock,advance:n=>clock+=n,client(mode='preview',extra={}){return h.createClient({bundle,key:'offline-test',mode,delegate,event:e=>events.push(e),now:()=>clock,wait:async n=>clock+=n,...extra});}};}
async function preview(f){return h.execute({client:f.client(),bundle,now:f.now});}
test('pinned source fragments, exact4 actions and Black parent correction load',()=>{assert.equal(bundle.actions.length,4);assert.equal(bundle.baseline.parents[1].is_available,false);assert.equal(bundle.actions.filter(a=>a.table==='products').length,0);});
test('default check and exact confirmation CLI only',()=>{assert.equal(h.cli([]).mode,'check');assert.equal(h.cli(['--preview']).mode,'preview');for(const a of [['--apply'],['--run'],['--apply','x','a'.repeat(64),'--yes']])assert.throws(()=>h.cli(a));});
test('preview uses14 GETs and no writes',async()=>{const f=fixture(),p=await preview(f);assert.equal(p.requests,14);assert.equal(p.writes,0);assert(f.calls.every(c=>c.method==='GET'));});
test('optional absent crawl state is unknown, explicitly recorded',async()=>{const f=fixture(initial(),{absent:true}),p=await preview(f);assert.equal(p.optional_crawl_state_absent,true);assert.equal(p.permission_inferred,false);assert(f.events.some(e=>e.event==='optional_crawl_state_absent'));});
test('full apply uses52 requests,4 PATCH only and preserves exact unrelated values',async()=>{const f=fixture(),p=await preview(f),before=clone(f.state);f.calls.length=0;const c=f.client('apply',{validateWrite:()=>h.validatePreview(p,bundle,f.now())}),r=await h.execute({client:c,bundle,mode:'apply',preview:p,now:f.now,append:e=>f.events.push(e)});assert.equal(c.requests,52);assert.equal(r.writes,4);assert.equal(f.calls.filter(x=>x.method==='PATCH').length,4);assert(f.calls.every(x=>['GET','PATCH'].includes(x.method)));assert.deepEqual(r.after.parents[1],before.parents[1]);for(const v of r.after.variants){const old=before.variants.find(x=>x.id===v.id);assert.equal(v.price_cents,old.price_cents);assert.equal(v.currency,old.currency);}assert.equal(r.after.parents[0].availability_last_seen_at,null);assert.equal(h.timestampKey(r.after.parents[0].availability_checked_at),h.timestampKey(bundle.source_at));assert.deepEqual(r.after.parents,before.parents);assert.equal(r.after.variants.find(v=>v.id===bundle.actions[0].id).weight_g,227);assert.equal(r.after.facts.find(f=>f.product_id===h.PRODUCTS[1]).process,'Black Honey');});
test('existing optional crawl-state rows stay within54 apply requests',async()=>{const s=initial();s.crawlState=h.OWNERS.map(entity_id=>({entity_id,allow_crawl:true}));const f=fixture(s),p=await preview(f);assert.equal(p.requests,15);const r=await h.execute({client:f.client('apply'),bundle,mode:'apply',preview:p,now:f.now});assert.equal(r.requests,54);});
for(const [label,edit]of [
 ['owner name',s=>s.owners[0].name='Wrong'],['owner host',s=>s.owners[1].website_url='https://wrong.example/'],['missing roaster',s=>s.roles=[]],['foreign source',s=>s.sources[0].entity_id=h.OWNERS[1]],['canonical outgoing',s=>s.canonicalOut=[{entity_id:h.OWNERS[0],attribute_key:'canonical_roaster_entity_id'}]],['canonical incoming',s=>s.canonicalIn=[{attribute_value:h.OWNERS[0],attribute_key:'canonical_roaster_entity_id'}]],['active claim',s=>s.activeClaims=[{id:'x',entity_id:h.OWNERS[0],status:'running'}]],['crawl disabled',s=>s.crawlState=[{entity_id:h.OWNERS[0],allow_crawl:false}]],['price changed',s=>s.variants[0].price_cents++],['weight filled',s=>s.variants.find(v=>v.id===bundle.actions[0].id).weight_g=227],['fact filled',s=>s.facts.find(f=>f.product_id===h.PRODUCTS[1]).process='Other'],['parent version',s=>s.parents[0].updated_at='2026-09-27T12:00:00Z'],['additional variant',s=>s.variants.push({...s.variants[0],id:'another'})]
])test('preview holds '+label,async()=>{const s=initial();edit(s);const f=fixture(s);await assert.rejects(preview(f));assert(!f.calls.some(c=>c.method==='PATCH'));});
test('all4 child PATCH CAS include every captured field and null; products can never be mutated',()=>{const s=initial();for(let i=0;i<4;i++){const d=h.descriptor('mutation',bundle,0,i,s),q=new URL(d.url).searchParams,row=h.rowFor(s,bundle.actions[i]);assert.deepEqual(d.body,bundle.actions[i].patch);assert(!new URL(d.url).pathname.endsWith('/products'));for(const[k,v]of Object.entries(row))assert.equal(q.get(k),v===null?'is.null':'eq.'+v);}});
test('changed mutation body, owner or products table denied',()=>{for(const mod of [b=>b.actions[0].patch.price_cents=1,b=>b.actions[0].entity_id=h.OWNERS[1],b=>b.actions[0].table='products']){const b=clone(bundle);mod(b);assert.throws(()=>h.descriptor('mutation',b,0,0,initial()));}});
test('expired/future/changed-helper previews refuse before requests',async()=>{const f=fixture(),p=await preview(f);for(const changed of [{...p,at:'2000-01-01T00:00:00Z'},{...p,at:'2100-01-01T00:00:00Z'},{...p,helper_sha256:'x'}]){const c=f.client('apply');await assert.rejects(h.execute({client:c,bundle,mode:'apply',preview:changed,now:f.now}));assert.equal(c.requests,0);}});
test('fresh preview owner metadata drift refuses any PATCH',async()=>{const f=fixture(),p=await preview(f);f.state.owners[0].metadata.preserve='changed';await assert.rejects(h.execute({client:f.client('apply'),bundle,mode:'apply',preview:p,now:f.now}));assert(!f.calls.some(c=>c.method==='PATCH'));});
test('per-action source drift stops before first PATCH',async()=>{const f=fixture(),p=await preview(f);let checked=0;await assert.rejects(h.execute({client:f.client('apply'),bundle,mode:'apply',preview:p,now:f.now,append:e=>{if(e.event==='all_preconditions_pass'){f.state.sources[0].raw_data.changed=true;checked++;}}}));assert.equal(checked,1);assert(!f.calls.some(c=>c.method==='PATCH'));});
test('per-action new active claim stops before first PATCH',async()=>{const f=fixture(),p=await preview(f);await assert.rejects(h.execute({client:f.client('apply'),bundle,mode:'apply',preview:p,now:f.now,append:e=>{if(e.event==='all_preconditions_pass')f.state.activeClaims.push({id:'new',entity_id:h.OWNERS[0],status:'running'});}}));assert(!f.calls.some(c=>c.method==='PATCH'));});
test('returned unrelated field mutation fails preservation',()=>{const a=bundle.actions[0],old=h.rowFor(initial(),a),row={...old,...a.patch,price_cents:1};assert.throws(()=>h.afterRow([row],old,a),/preservation/);});
test('zero or multiple CAS representations fail',()=>{const a=bundle.actions[0],old=h.rowFor(initial(),a);assert.throws(()=>h.afterRow([],old,a));assert.throws(()=>h.afterRow([old,old],old,a));});
test('ambiguous PATCH response latches without replay',async()=>{const f=fixture(initial(),{hook:({url,req})=>req.method==='PATCH'?response(url,{code:'57014'},500):null}),c=f.client('apply');await assert.rejects(c.request('mutation',0,0,f.state));await assert.rejects(c.request('mutation',0,0,f.state));assert.equal(f.calls.length,1);});
test('preview transport denies PATCH and latches',async()=>{const f=fixture(),c=f.client();await assert.rejects(c.request('mutation',0,0,f.state));await assert.rejects(c.request('owners'));assert.equal(f.calls.length,0);});
for(const [label,respond]of [['changed URL',(u)=>response(u+'x',[])],['empty URL',()=>new Response('[]',{headers:{'content-type':'application/json','content-range':'*/*'}})],['nonJSON',(u)=>{const r=response(u,[]);r.headers.set('content-type','text/html');return r;}],['bad range',(u)=>{const r=response(u,[]);r.headers.set('content-range','0-0/*');return r;}],['overflow',(u)=>response(u,Array.from({length:25},()=>({})))],['wrong optional error',(u)=>response(u,{code:'42501'},404)]])test('transport fails closed '+label,async()=>{const f=fixture(initial(),{hook:({url})=>respond(url)}),c=f.client();await assert.rejects(c.request('crawlState'));await assert.rejects(c.request('owners'));assert.equal(f.calls.length,1);});
test('nonempty EOF refuses hidden extra rows',async()=>{const f=fixture(initial(),{hook:({url,offset})=>offset?response(url,[{id:'hidden'}],200,offset):null});await assert.rejects(preview(f),/nonempty_eof/);});
test('completion pacing loops after early timer and includes slow body',async()=>{let clock=0,done=0,n=0;const waits=[];const c=h.createClient({bundle,key:'test',now:()=>clock,wait:async ms=>{waits.push(ms);clock+=ms===500?499:ms;},delegate:async u=>{if(n)assert(clock-done>=500);n++;clock+=1200;const r=response(u,[]);const reader=r.body.getReader.bind(r.body);r.body.getReader=()=>{const rr=reader();return {read:async()=>{const x=await rr.read();if(x.done){clock+=70;done=clock;}return x;},releaseLock:()=>rr.releaseLock()};};return r;}});await c.request('activeClaims');await c.request('activeClaims');assert.deepEqual(waits,[500,1]);});
test('deadline expired during cooldown refuses actual dispatch',async()=>{let clock=0,n=0;const c=h.createClient({bundle,key:'x',now:()=>clock,wait:async()=>clock=300001,delegate:async u=>{n++;return response(u,[]);}});await c.request('activeClaims');await assert.rejects(c.request('activeClaims'),/deadline/);assert.equal(n,1);});
test('write TTL rechecked after pacing',async()=>{let n=0;const f=fixture(),c=f.client('apply',{validateWrite:()=>{throw Object.assign(Error('expired'),{code:'preview_expired'});},delegate:async()=>{n++;}});await assert.rejects(c.request('mutation',0,0,f.state),/expired/);assert.equal(n,0);});
test('journal error before mutation prevents dispatch',async()=>{const f=fixture(),c=f.client('apply',{event:()=>{throw Error('disk failure');}});await assert.rejects(c.request('mutation',0,0,f.state));assert.equal(f.calls.length,0);});

test('regression: original executed parent response differs only in SQL timestamp spelling',()=>{const fs=require('node:fs'),path=require('node:path'),base=__dirname===h.ROOT+'/src/myCoffeeExplorerImport'?h.STATE:__dirname,events=fs.readFileSync(path.join(base,'batch8b-five-field-repair-apply/events.ndjson'),'utf8').trim().split('\n').map(JSON.parse),attempt=events.find(e=>e.event==='mutation_attempt_no_retry'),returned=events.find(e=>e.event==='request_result'&&e.kind==='mutation').rows;const old=require('./apply-batch8b-five-fields.cjs');assert.throws(()=>old.afterRow(returned,attempt.before,attempt.action),/availability_checked_at/);assert.doesNotThrow(()=>h.afterRow(returned,attempt.before,attempt.action));});
test('timestamp equivalent UTC spellings preserve microseconds',()=>{assert.equal(h.timestampKey('2026-09-27T16:31:50.750Z'),h.timestampKey('2026-09-27T16:31:50.75+00:00'));assert.equal(h.timestampKey('2026-09-27T12:31:50.123456-04:00'),h.timestampKey('2026-09-27T16:31:50.123456Z'));assert.notEqual(h.timestampKey('2026-09-27T16:31:50.123456Z'),h.timestampKey('2026-09-27T16:31:50.123457Z'));});
test('non-timestamp fields never use date-equivalence',()=>{assert.equal(h.fieldEqual('variant_name','2026-09-27T16:31:50.750Z','2026-09-27T16:31:50.75+00:00'),false);assert.throws(()=>h.timestampKey('2026-09-27'));assert.throws(()=>h.timestampKey('yesterday'));});
test('equivalent created_at representation accepted, real microsecond change refused',()=>{const a=bundle.actions[0],before=h.rowFor(initial(),a),row={...before,...a.patch,created_at:before.created_at.replace('+00:00','Z')};assert.doesNotThrow(()=>h.afterRow([row],before,a));const changed={...row,created_at:'2026-09-27T10:45:32.559273+00:00'};assert.throws(()=>h.afterRow([changed],before,a),/created_at/);});
