'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const h=require('./apply-strawanzer-six-weight-fill.cjs'),p=h.loadPlan(),clone=structuredClone;
function fixture(){
 let time=100000,fault=null;const data={entities:[{id:h.OWNER,name:p.owner.name,website_url:p.owner.website_url,metadata:{untouched:'owner'}}],entity_roles:[{entity_id:h.OWNER,role:'roaster',role_metadata:{untouched:true}}],entity_source_ids:[{id:'source-id',entity_id:h.OWNER,...p.baseline.sources[0],raw_data:{untouched:'source'}}],entity_attributes:[],entity_crawl_state:[],crawl_runs:[{id:h.CLAIM,entity_id:h.OWNER,status:'completed',pages_visited:2,coffees_found:2,meta:{untouched:'claim'}}],products:p.baseline.products.map(t=>({id:t.id,entity_id:t.entity_id,name:t.name,source_url:t.source_url,is_active:true,metadata:{raw:'keep all product metadata'},updated_at:'2026-09-27T09:40:23Z'})),product_variants:clone(p.baseline.variants),coffee_facts:p.baseline.products.map(t=>({product_id:t.id,...t.coffee_facts,raw:{untouched:'fact'}})),product_media:p.baseline.products.flatMap(t=>t.product_media.map(m=>({product_id:t.id,...m,sort_order:0}))),media_assets:p.baseline.products.flatMap(t=>t.product_media.map(m=>({id:m.media_asset_id,url:'https://images.example.test/retained',content_hash:'retain'}))),known_pages:p.products.map(t=>({id:t.product_id+'-known',entity_id:h.OWNER,url:t.source_url,status:'coffee',classification:{raw:'retain'}}))};
 const calls=[],events=[];const delegate=async(url,init)=>{
  const u=new URL(url),table=u.pathname.split('/').at(-1),offset=Number(u.searchParams.get('offset')||0),method=init.method;calls.push({url,method,body:init.body&&JSON.parse(init.body)});if(fault){const r=await fault({u,table,offset,method,data,calls});if(r)return r;}
  let rows=clone(data[table]);for(const[k,v]of u.searchParams){if(['select','order','limit','offset'].includes(k))continue;if(v.startsWith('in.(')){const allowed=v.slice(4,-1).split(',');rows=rows.filter(r=>allowed.includes(String(r[k])));}else if(v==='is.null')rows=rows.filter(r=>r[k]===null);else if(v.startsWith('eq.'))rows=rows.filter(r=>String(r[k])===v.slice(3));}
  if(method==='PATCH'){rows=rows.map(r=>{const real=data.product_variants.find(v=>v.id===r.id);return clone(Object.assign(real,JSON.parse(init.body),{updated_at:'2026-09-27T10:05:00Z'}));});}
  else{rows=rows.slice(offset,offset+Number(u.searchParams.get('limit')));if(u.searchParams.get('select')!=='*')rows=rows.map(r=>Object.fromEntries(u.searchParams.get('select').split(',').map(k=>[k,r[k]])));}
  return new Response(JSON.stringify(rows),{status:200,headers:{'content-type':'application/json','content-range':rows.length?offset+'-'+(offset+rows.length-1)+'/*':'*/*'}});
 };
 return{data,calls,events,setFault:f=>fault=f,writes:()=>calls.filter(c=>c.method!=='GET'),client:(writes=false)=>h.createClient({plan:p,key:'offline-not-a-key',allowWrites:writes,delegate,event:e=>events.push(e),now:()=>time,wait:async ms=>{time+=ms;}})};
}
const preview=f=>h.execute({client:f.client(),plan:p}),apply=(f,v)=>h.execute({client:f.client(true),plan:p,mode:'apply',preview:v});
test('real pinned plan and live-index receipt are bound; no fabricated index assertion',()=>{assert.equal(p.patches.length,6);assert.equal(p.baseline.variants.length,18);const evidenceBase=__dirname===h.ROOT+'/src/myCoffeeExplorerImport'?h.STATE:__dirname;assert.equal(h.sha(fs.readFileSync(path.join(evidenceBase,h.INDEX_FILE))),h.INDEX_SHA);});
test('checkpoint complete is not live database completed status',async()=>{assert.equal(p.baseline.claim.status,'complete');const f=fixture();f.data.crawl_runs[0].status='complete';await assert.rejects(preview(f),/claim_changed/);assert.equal(f.writes().length,0);});
test('preview establishes full fresh context in24GETs, zero writes',async()=>{const f=fixture(),v=await preview(f);assert.equal(v.requests,24);assert.equal(f.writes().length,0);assert.equal(v.before.parents[0].metadata.raw,'keep all product metadata');assert(v.before.knownPages[0].classification);});
test('six PATCHes fill only whole-bean weights, preserve12groundrows and allrawcontext in102requests',async()=>{const f=fixture(),v=await preview(f);f.calls.length=0;const r=await apply(f,v);assert.equal(r.requests,102);assert.equal(f.writes().length,6);assert(f.writes().every(w=>w.method==='PATCH'&&Object.keys(w.body).join()==='weight_g'));for(const q of p.patches)assert.equal(r.after.variants.find(v=>v.id===q.variant_id).weight_g,q.changes.weight_g);for(const old of p.baseline.variants.filter(v=>!p.patches.some(q=>q.variant_id===v.id)))assert.deepEqual(r.after.variants.find(v=>v.id===old.id),old);for(const k of Object.keys(r.before).filter(k=>k!=='variants'))assert.deepEqual(r.after[k],r.before[k]);});
for(const[name,mutate]of[
 ['owner website changed',d=>d.entities[0].website_url='https://other.invalid/'],['roaster role missing',d=>d.entity_roles=[]],['source reassigned',d=>d.entity_source_ids[0].entity_id='other'],['source duplicated',d=>d.entity_source_ids.push({...d.entity_source_ids[0],id:'other',entity_id:'other'})],['outgoing canonical',d=>d.entity_attributes.push({entity_id:h.OWNER,attribute_key:'canonical_roaster_entity_id',attribute_value:'other'})],['incoming canonical',d=>d.entity_attributes.push({entity_id:'other',attribute_key:'canonical_roaster_entity_id',attribute_value:h.OWNER})],['active competing claim',d=>d.crawl_runs.push({id:'other',entity_id:h.OWNER,status:'running'})],['original claim changed',d=>d.crawl_runs[0].status='failed'],['crawl denied',d=>d.entity_crawl_state.push({entity_id:h.OWNER,allow_crawl:false})],['product reassigned',d=>d.products[0].entity_id='other'],['product source changed',d=>d.products[0].source_url='https://other.invalid/'],['product inactive',d=>d.products[0].is_active=false],['non-target source duplicate',d=>d.products.push({...d.products[0],id:'other',entity_id:'other'})],['whole-bean label changed',d=>d.product_variants.find(r=>r.id===p.patches[0].variant_id).variant_name='250 g whole beans'],['whole-bean already filled',d=>d.product_variants.find(r=>r.id===p.patches[0].variant_id).weight_g=250],['ground row occupies weight',d=>d.product_variants.find(r=>r.variant_name.includes('Gemahlen')).weight_g=1000],['extra variant',d=>d.product_variants.push({...d.product_variants[0],id:'extra'})],['ground row price changed',d=>d.product_variants.find(r=>r.variant_name.includes('Gemahlen')).price_cents=1],['new variant schema field',d=>d.product_variants[0].unexpected=true],['known page missing',d=>d.known_pages.pop()],['known page status changed',d=>d.known_pages[0].status='skip'],['media reference changed',d=>d.product_media[0].media_asset_id='other'],['fact projection changed',d=>d.coffee_facts[0].process='wrong']
])test('fresh preflight refuses '+name,async()=>{const f=fixture();mutate(f.data);await assert.rejects(preview(f));assert.equal(f.writes().length,0);});
test('allnine null-inclusive CAS values are present for allsix patch IDs; out ofscope writes rejected',()=>{for(let i=0;i<6;i++){const d=h.descriptor('patch'+i,p),q=new URL(d.url).searchParams;assert.equal(d.method,'PATCH');assert.deepEqual(d.body,p.patches[i].changes);for(const[k,v]of Object.entries(p.patches[i].before))assert.equal(q.get(k),v===null?'is.null':'eq.'+v);assert.equal([...q].length,10);}for(const kind of['patch6','insertVariants','deleteVariants','rpc'])assert.throws(()=>h.descriptor(kind,p),/out_of_scope/);});
test('full raw metadata drift after preview blocks allwrites',async()=>{for(const edit of[d=>d.products[0].metadata.extra=true,d=>d.entity_source_ids[0].raw_data.extra=true,d=>d.known_pages[0].classification.extra=true,d=>d.coffee_facts[0].raw.extra=true,d=>d.crawl_runs[0].meta.extra=true]){const f=fixture(),v=await preview(f);edit(f.data);await assert.rejects(apply(f,v),/fresh_context_changed/);assert.equal(f.writes().length,0);}});
test('continuation probe detects server truncation',async()=>{const f=fixture();f.setFault(({table,offset})=>table==='product_variants'&&offset?new Response(JSON.stringify([p.baseline.variants[0]]),{headers:{'content-type':'application/json','content-range':offset+'-'+offset+'/*'}}):null);await assert.rejects(preview(f),/nonempty_continuation/);});
test('late active claim blocks first PATCH',async()=>{const f=fixture(),v=await preview(f);let n=0;f.setFault(({table,u,data})=>{if(table==='crawl_runs'&&u.searchParams.get('status')==='eq.running'&&++n===2)data.crawl_runs.push({id:'late',entity_id:h.OWNER,status:'running'});});await assert.rejects(apply(f,v),/active_owner_claim/);assert.equal(f.writes().length,0);});
test('late raw parent change blocks before PATCH',async()=>{const f=fixture(),v=await preview(f);let n=0;f.setFault(({table,u,data})=>{if(table==='products'&&u.searchParams.has('id')&&++n===2)data.products[0].metadata.late=true;});await assert.rejects(apply(f,v),/prewrite_parent_changed/);assert.equal(f.writes().length,0);});
test('late ground variant drift after onePATCH stops preserving partialoutcome',async()=>{const f=fixture(),v=await preview(f);f.setFault(({table,data})=>{if(table==='product_variants'&&f.writes().length===1)data.product_variants.find(r=>r.variant_name.includes('Gemahlen')).weight_g=1000;});await assert.rejects(apply(f,v),/variant_baseline_changed/);assert.equal(f.writes().length,1);});
test('CAS mismatch immediately beforedispatch stops without secondwrite',async()=>{const f=fixture(),v=await preview(f);f.setFault(({method,data})=>{if(method==='PATCH')data.product_variants.find(r=>r.id===p.patches[0].variant_id).price_cents++;});await assert.rejects(apply(f,v),/weight_cas_not_one/);assert.equal(f.writes().length,1);});
test('ambiguous thirdPATCH timeout is never replayed or treated asrollback',async()=>{const f=fixture(),v=await preview(f);f.setFault(({method})=>{if(method==='PATCH'&&f.writes().length===3)throw Error('uncertain_network_failure');});await assert.rejects(apply(f,v),/uncertain_network_failure/);assert.equal(f.writes().length,3);assert.equal(f.data.product_variants.filter(v=>v.weight_g!==null).length,2);});
test('returnedrow price mutation stops',async()=>{const f=fixture(),v=await preview(f);f.setFault(({method})=>method==='PATCH'?new Response(JSON.stringify([{...p.patches[0].before,weight_g:250,price_cents:1,updated_at:'2026-09-27T10:05:00Z'}]),{headers:{'content-type':'application/json'}}):null);await assert.rejects(apply(f,v),/variant_preservation:price_cents/);assert.equal(f.writes().length,1);});
test('finalreadback rejects unrelated children/rawclaim/metadata changes',async()=>{for(const edit of[d=>d.products[0].metadata.after=true,d=>d.coffee_facts[0].raw.after=true,d=>d.known_pages[0].classification.after=true,d=>d.crawl_runs[0].meta.after=true,d=>d.media_assets[0].content_hash='changed']){const f=fixture(),v=await preview(f);f.setFault(({table,data})=>{if(table==='entities'&&f.writes().length===6)edit(data);});await assert.rejects(apply(f,v),/preservation/);assert.equal(f.writes().length,6);}});
test('exact JSON404 optionalcrawlstate absence accepted and allothererrors stop',async()=>{const f=fixture();f.setFault(({table})=>table==='entity_crawl_state'?new Response('{"code":"PGRST205"}',{status:404,headers:{'content-type':'application/json'}}):null);assert.equal((await preview(f)).requests,24);assert(f.events.some(e=>e.event==='optional_crawl_state_table_absent'));for(const[status,code,type]of[[503,'PGRST205','application/json'],[404,'42P01','application/json'],[404,'PGRST205','text/html']]){const g=fixture();g.setFault(({table})=>table==='entity_crawl_state'?new Response(JSON.stringify({code}),{status,headers:{'content-type':type}}):null);await assert.rejects(preview(g));}});
test('optional populated crawlstate adds onlytwo completeprobes acrossapply',async()=>{const f=fixture();f.data.entity_crawl_state.push({entity_id:h.OWNER,allow_crawl:true});const v=await preview(f);assert.equal(v.requests,25);assert.equal((await apply(f,v)).requests,104);});
test('transport latches nontransient400 and willnot replay mutation',async()=>{const f=fixture();f.setFault(()=>new Response('{"code":"22003"}',{status:400,headers:{'content-type':'application/json'}}));const c=f.client(true);await assert.rejects(c.request('patch0'));await assert.rejects(c.request('patch0'),/stopped/);assert.equal(f.calls.length,1);});
test('transport strictly allows exact origin, no redirect and previewGETonly',async()=>{const f=fixture();await assert.rejects(f.client().request('patch0'),/preview_write/);assert.equal(f.calls.length,0);const c=h.createClient({plan:p,key:'not-a-key',delegate:async()=>({redirected:true,url:'https://other.invalid/'})});await assert.rejects(c.request('owner'),/response_origin/);});
test('previewhashbinding and15minTTL required',async()=>{const f=fixture(),v=await preview(f);for(const a of[{at:new Date(Date.now()-900001).toISOString()},{helper_sha256:'x'},{plan_sha256:'x'}])assert.throws(()=>h.validatePreview({...v,...a},p));});
test('journal failure before firstintent makes zerowrites',async()=>{const f=fixture(),v=await preview(f);await assert.rejects(h.execute({client:f.client(true),plan:p,mode:'apply',preview:v,append:e=>{if(e.event==='mutation_attempt_no_retry')throw Error('disk_failure');}}),/disk_failure/);assert.equal(f.writes().length,0);});
test('sharedandownerlock helper isexclusive and preserves foreignlock replacement',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'weight-cas-test-')),file=path.join(dir,'lock'),lock=h.acquireLock(file);assert.throws(()=>h.acquireLock(file),/EEXIST/);fs.writeFileSync(file,'foreign');assert.throws(()=>lock.release(),/ownership_lost/);assert.equal(fs.readFileSync(file,'utf8'),'foreign');fs.unlinkSync(file);fs.rmdirSync(dir);});
test('defaultCLI isoffline; apply needs explicit exactconfirmation',()=>{assert.equal(h.cli([]).mode,'check');assert.equal(h.cli(['--preview']).mode,'preview');assert.throws(()=>h.cli(['--apply','anything','a'.repeat(64),'--yes']));});
test('500msbodycompletionpace rechecks earlywake and includesdurableaudit time',async()=>{let time=100000,early=true;const starts=[],waits=[];const c=h.createClient({plan:p,key:'offline',now:()=>time,wait:async ms=>{waits.push(ms);time+=early?(early=false,ms-1):ms;},event:e=>{if(e.event==='request_result')time+=70;},delegate:async()=>{starts.push(time);time+=1200;return new Response('[]',{headers:{'content-type':'application/json','content-range':'*/*'}});}});await c.request('owner');await c.request('roles');assert.deepEqual(waits,[500,1]);assert.equal(starts[1]-starts[0],1770);});
