'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const h=require('./apply-batch4d-eleven-fields-paced.cjs');
// Tests use only local evidence and mocked transports; any real fetch fails.
globalThis.fetch=async()=>{throw Error('NETWORK_FORBIDDEN');};
const bundle=h.loadBundle(),clone=h.copy,now=Date.parse('2026-09-27T11:00:00Z');
function state(){
 const s={...clone(bundle.historical),canonicalOut:[],canonicalIn:[],crawlState:[],activeClaims:[],knownPages:[]};
 for(const p of s.parents)Object.assign(p,{product_type:'coffee',description_raw:'preserve exact description',updated_at:'2026-09-27T01:36:00+00:00',original_image_url:'https://example.invalid/preserve.png'});
 for(const p of s.owners)Object.assign(p,{created_at:'2026-09-26T00:00:00+00:00',contact:{email:'retained@example.invalid'}});
 for(const p of s.sources)Object.assign(p,{raw_data:{retained:true},confidence:0.95});s.sourceKeys=clone(s.sources);
 for(const p of s.roles)Object.assign(p,{role_metadata:{retained:true}});
 for(const p of s.claims)Object.assign(p,{created_at:'2026-09-27T01:00:00+00:00'});s.ownerClaims=clone(s.claims);
 return s;
}
function preview(){return{at:new Date(now).toISOString(),status:'preview_complete',proposal_sha256:h.PROPOSAL_SHA,helper_sha256:h.sha(fs.readFileSync(require.resolve('./apply-batch4d-eleven-fields-paced.cjs'))),before:state()};}
function fakeClient({before,hook,mutate}={}){const current=clone(before||state()),writes=[],calls=[];return{state:current,writes,calls,get requests(){return calls.length;},async request(kind,offset=0,index,expected){
 calls.push({kind,offset,index});if(hook){const r=hook({kind,offset,index,state:current,calls,writes});if(r!==undefined)return r;}
 if(kind!=='mutation')return offset?[]:clone(current[kind]);const a=bundle.actions[index];writes.push(clone(a));const key=a.table==='coffee_facts'?'facts':'variants',isTarget=r=>a.table==='coffee_facts'?r.product_id===a.key.product_id:r.id===a.key.id;
 let row={...current[key].find(isTarget),...clone(a.patch),updated_at:new Date(now).toISOString()};if(mutate)row=mutate(row,a,index);current[key]=current[key].filter(r=>!isTarget(r)).concat(clone(row));return[clone(row)];
 }};}
function response(rows=[],{status=200,offset=0,headers={},body,url}={}){const r=new Response(body===undefined?JSON.stringify(rows):body,{status,headers:{'content-type':'application/json','content-range':rows.length?`${offset}-${offset+rows.length-1}/*`:'*/*',...headers}});if(url)Object.defineProperty(r,'url',{value:url});return r;}
function transport(options={}){let clock=0;const calls=[],events=[],waits=[];const delegate=options.delegate|| (async(url,opts)=>{calls.push({url,opts,at:clock});return response([]);});const client=h.createClient({bundle,key:'test-secret-not-real',allowWrites:true,now:()=>clock,wait:async ms=>{waits.push(ms);clock+=ms;},event:e=>events.push(e),...options,delegate:async(url,opts)=>{const r=await delegate(url,opts);if(!r.url)Object.defineProperty(r,'url',{value:url});return r;}});return{client,calls,events,waits,get clock(){return clock;},advance:n=>{clock+=n;}};}

test('frozen proposal and19 pins resolve11 exact PATCH actions only',()=>{assert.equal(Object.keys(bundle.proposal.evidence_pins).length,19);assert.equal(bundle.actions.length,11);assert.equal(bundle.ids.length,10);assert.equal(bundle.owners.length,6);assert.deepEqual(bundle.actions.slice(0,5).map(a=>a.patch),Array(5).fill({decaf:true}));assert.deepEqual(bundle.actions.slice(5).map(a=>a.patch.weight_g),[250,250,250,283,283,2268]);assert.equal(bundle.proposal.excluded_actions.length,9);});
test('proposal hash mutation stops before requests',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'batch4d-pin-'));try{fs.writeFileSync(path.join(dir,h.PROPOSAL_FILE),'{}');assert.throws(()=>h.loadBundle(dir),/proposal_hash/);}finally{fs.rmSync(dir,{recursive:true});}});
test('all read descriptors are exact six-owner/ten-product scope',()=>{for(const k of h.READS){const d=h.descriptor(k,bundle),u=new URL(d.url);assert.equal(d.method,'GET');assert.equal(u.origin,h.ORIGIN);assert.match(u.pathname,/^\/rest\/v1\/[a-z_]+$/);assert.equal(u.searchParams.get('limit'),'100');assert.equal(d.body,undefined);}const q=new URL(h.descriptor('sourceKeys',bundle).url).searchParams;assert.equal(q.get('source'),'eq.my_coffee_explorer');assert.equal(q.has('entity_id'),false);for(const s of bundle.historical.sources)assert.ok(q.get('source_id').includes(s.source_id));});
test('every write body is one field only and full child row CAS includes null',()=>{for(let i=0;i<11;i++){const a=bundle.actions[i],d=h.descriptor('mutation',bundle,0,i,state()),q=new URL(d.url).searchParams;assert.equal(d.method,'PATCH');assert.deepEqual(d.body,a.patch);assert.equal(Object.keys(d.body).length,1);assert.equal(new URL(d.url).pathname,'/rest/v1/'+a.table);for(const[k,v]of Object.entries(a.retained_before))assert.equal(q.get(k),v===null?'is.null':'eq.'+(typeof v==='object'?JSON.stringify(v):v));assert.ok(d.url.length<4096);}});
test('wrong kind/index/offset cannot authorize another mutation',()=>{assert.throws(()=>h.descriptor('insert',bundle),/request_out_of_scope/);assert.throws(()=>h.descriptor('mutation',bundle,0,11,state()),/mutation_scope/);assert.throws(()=>h.descriptor('owners',bundle,100),/offset_scope/);assert.throws(()=>h.descriptor('mutation',bundle,1,0,state()),/mutation_scope/);});
test('historical projections admit fresh extra owner/product fields, not changed known facts',()=>{h.validateHistorical(state(),bundle);const s=state();s.parents[0].name+=' changed';assert.throws(()=>h.validateHistorical(s,bundle),/parents_historical_drift/);});
test('unknown child schema or extra sibling cannot masquerade as historical baseline',()=>{for(const k of ['variants','facts','media']){const s=state();s[k][0].new_column=null;assert.throws(()=>h.validateHistorical(s,bundle),new RegExp(k+'_schema_drift'));}const s=state();s.variants.push({...s.variants[0],id:'new'});assert.throws(()=>h.validateHistorical(s,bundle),/variants_historical_count/);});
test('six target weights vacant and unique pairs enforced independently',()=>{for(const a of bundle.actions.slice(5))h.weightVacancy(state(),a);const a=bundle.actions[5],s=state();s.variants.push({id:'foreign',product_id:a.key.product_id,weight_g:a.patch.weight_g});assert.throws(()=>h.weightVacancy(s,a),/target_weight_occupied/);assert.throws(()=>h.descriptor('mutation',bundle,0,5,s),/target_weight_occupied/);const d=state(),v=d.variants.find(v=>v.weight_g!==null);d.variants.push({...v,id:'duplicate'});assert.throws(()=>h.validateHistorical(d,bundle),/duplicate_product_weight/);});
test('nonnull target or already repaired field stops, not idempotently skipped',()=>{for(const i of [0,5]){const s=state(),a=bundle.actions[i],rows=a.table==='coffee_facts'?s.facts:s.variants,r=rows.find(r=>a.table==='coffee_facts'?r.product_id===a.key.product_id:r.id===a.key.id);Object.assign(r,a.patch);assert.throws(()=>h.descriptor('mutation',bundle,0,i,s),/target_not_null/);assert.throws(()=>h.validateHistorical(s,bundle));}});
test('nine excluded ground rows are present and never in write descriptors',()=>{const written=new Set(bundle.actions.map(a=>a.key.id).filter(Boolean));for(const e of bundle.proposal.excluded_actions){assert.ok(!written.has(e.key.id));const r=state().variants.find(r=>r.id===e.key.id);assert.equal(r.weight_g,null);assert.equal(r.variant_name,e.retained_variant_name);}});
test('default/check offline, explicit preview and fixed confirmation only',()=>{assert.deepEqual(h.cli([]),{mode:'check'});assert.deepEqual(h.cli(['--check']),{mode:'check'});assert.deepEqual(h.cli(['--preview']),{mode:'preview'});assert.equal(h.cli(['--apply','x','a'.repeat(64),'--confirm-eleven-field-writes']).mode,'apply');for(const args of [['--run'],['--resume'],['--retry'],['--apply','x','a'.repeat(64),'--confirm-ten-null-fill-writes']])assert.throws(()=>h.cli(args),/invalid_cli/);});
test('fresh preview is read-only and explicitly probes EOF for every nonempty set',async()=>{const c=fakeClient(),r=await h.execute({client:c,bundle,now:()=>now});assert.equal(r.status,'preview_complete');assert.equal(r.current_full_rows_captured,true);assert.equal(r.historical_projections_verified,true);assert.equal(r.writes,0);for(const k of h.READS){assert.equal(c.calls.filter(x=>x.kind===k&&!x.offset).length,1);if(state()[k].length)assert.equal(c.calls.filter(x=>x.kind===k&&x.offset).length,1);}assert.equal(c.writes.length,0);});
for(const key of Object.keys(bundle.historical))test('historically known '+key+' drift prevents all writes',async()=>{const before=state(),row=before[key][0],old=bundle.historical[key][0],field=Object.keys(old).find(k=>!['id','entity_id','product_id'].includes(k));row[field]=typeof old[field]==='string'?old[field]+' drift':!old[field];const c=fakeClient({before});await assert.rejects(h.execute({client:c,bundle,mode:'apply',preview:preview(),now:()=>now}));assert.equal(c.writes.length,0);});
for(const key of ['canonicalOut','canonicalIn','activeClaims'])test(key+' conflict prevents preview',async()=>{const s=state();s[key].push({id:'unexpected'});const c=fakeClient({before:s});await assert.rejects(h.execute({client:c,bundle,now:()=>now}),new RegExp(key+'_conflict'));assert.equal(c.writes.length,0);});
test('disabled owner crawl state prevents preview',async()=>{const s=state();s.crawlState=[{entity_id:bundle.owners[0],allow_crawl:false}];await assert.rejects(h.execute({client:fakeClient({before:s}),bundle,now:()=>now}),/crawl_disabled/);});
test('known-page baseline may be captured only exact product-owner URL pairs',()=>{const s=state(),p=bundle.products[0];s.knownPages=[{entity_id:p.entity_id,url:p.source_url,page_type:'product'}];h.validateHistorical(s,bundle);s.knownPages[0].entity_id=bundle.owners.find(x=>x!==p.entity_id);assert.throws(()=>h.validateHistorical(s,bundle),/known_page_scope/);});
test('unknown full owner/product/source/claim drift after preview blocks apply',async()=>{for(const key of ['owners','parents','sources','claims']){const s=state();s[key][0].new_field='new';const c=fakeClient({before:s});await assert.rejects(h.execute({client:c,bundle,mode:'apply',preview:preview(),now:()=>now}),new RegExp(key+'_drift'));assert.equal(c.writes.length,0);}});
test('nonempty continuation is treated as incomplete, not silently truncated',async()=>{const c=fakeClient({hook:({kind,offset})=>kind==='variants'&&offset?[{id:'extra'}]:undefined});await assert.rejects(h.execute({client:c,bundle,now:()=>now}),/nonempty_continuation:variants/);assert.equal(c.writes.length,0);});
test('successful repair11 patches preserves all prices,9 ground rows, parents/links/claims',async()=>{const c=fakeClient(),r=await h.execute({client:c,bundle,mode:'apply',preview:preview(),now:()=>now});assert.equal(r.status,'eleven_field_repair_verified');assert.equal(r.mutation_requests,11);assert.equal(c.writes.length,11);for(const k of h.READS.filter(k=>!['facts','variants'].includes(k)))assert.deepEqual(r.after[k],r.before[k]);for(const e of bundle.proposal.excluded_actions)assert.deepEqual(r.after.variants.find(v=>v.id===e.key.id),r.before.variants.find(v=>v.id===e.key.id));for(const v of r.after.variants){const old=r.before.variants.find(x=>x.id===v.id);assert.equal(v.price_cents,old.price_cents);assert.equal(v.currency,old.currency);assert.equal(v.variant_name,old.variant_name);}assert.equal(r.inserts,0);assert.equal(r.deletes,0);assert.equal(r.full_product_completion,false);});
test('before every PATCH a complete exact-target state is reread',async()=>{const c=fakeClient();await h.execute({client:c,bundle,mode:'apply',preview:preview(),now:()=>now});assert.equal(c.calls.filter(x=>x.kind==='owners'&&!x.offset).length,13);for(let i=0;i<11;i++){const at=c.calls.findIndex(x=>x.kind==='mutation'&&x.index===i),prev=i?c.calls.findIndex(x=>x.kind==='mutation'&&x.index===i-1):-1;for(const k of h.READS)assert.ok(c.calls.slice(prev+1,at).some(x=>x.kind===k&&!x.offset));}});
test('new active claim after a write blocks all later writes',async()=>{const c=fakeClient({hook:({kind,offset,writes,state})=>{if(kind==='activeClaims'&&!offset&&writes.length===1)state.activeClaims.push({id:'running',entity_id:bundle.owners[0]});}});await assert.rejects(h.execute({client:c,bundle,mode:'apply',preview:preview(),now:()=>now}),/activeClaims_conflict/);assert.equal(c.writes.length,1);});
test('new sibling between operations stops before weight update',async()=>{const c=fakeClient({hook:({kind,offset,writes,state})=>{if(kind==='variants'&&!offset&&writes.length===5&&!state.variants.some(v=>v.id==='intruder'))state.variants.push({id:'intruder',product_id:bundle.actions[5].key.product_id,weight_g:250});}});await assert.rejects(h.execute({client:c,bundle,mode:'apply',preview:preview(),now:()=>now}),/variants_drift/);assert.equal(c.writes.length,5);});
test('zero-row CAS fails closed with no retry or later actions',async()=>{const c=fakeClient({hook:({kind})=>kind==='mutation'?[]:undefined});await assert.rejects(h.execute({client:c,bundle,mode:'apply',preview:preview(),now:()=>now}),/mutation_not_one/);assert.equal(c.calls.filter(c=>c.kind==='mutation').length,1);});
test('returned price mutation or fact overwrite is detected immediately',async()=>{for(const field of ['price_cents','variety']){const c=fakeClient({mutate:(r,a)=>field==='price_cents'&&a.table==='product_variants'?{...r,price_cents:999}:field==='variety'&&a.table==='coffee_facts'?{...r,variety:'wrong'}:r});await assert.rejects(h.execute({client:c,bundle,mode:'apply',preview:preview(),now:()=>now}),new RegExp('preservation:'+field));assert.equal(c.writes.length,field==='price_cents'?6:1);}});
test('preview binding and15minute/future boundary gate',()=>{for(const p of [{...preview(),proposal_sha256:'x'},{...preview(),helper_sha256:'x'}])assert.throws(()=>h.validatePreview(p,bundle,now),/preview_binding/);for(const at of [now+h.TTL,now-1])assert.throws(()=>h.validatePreview(preview(),bundle,at),/preview_expired/);h.validatePreview(preview(),bundle,now+h.TTL-1);});
test('preview expiry during pre-write reads prevents subsequent write',async()=>{let time=now;const c=fakeClient({hook:({kind,offset,writes})=>{if(kind==='owners'&&!offset&&writes.length===1)time=now+h.TTL;}});await assert.rejects(h.execute({client:c,bundle,mode:'apply',preview:preview(),now:()=>time}),/preview_expired/);assert.equal(c.writes.length,1);});
test('transport sends fixed origin credential headers and error redirect mode only',async()=>{const t=transport();await t.client.request('owners');assert.equal(t.calls.length,1);assert.equal(new URL(t.calls[0].url).origin,h.ORIGIN);assert.equal(t.calls[0].opts.redirect,'error');assert.equal(t.calls[0].opts.headers.Authorization,'Bearer test-secret-not-real');assert.ok(t.calls[0].opts.signal);assert.equal(JSON.stringify(t.events).includes('test-secret'),false);});
test('transport loops on early wake and measures pacing after body completion',async()=>{let clock=0,waitCalls=0;const dispatches=[];const c=h.createClient({bundle,key:'x',now:()=>clock,wait:async n=>{waitCalls++;clock+=waitCalls===1?n-1:n;},delegate:async url=>{dispatches.push(clock);clock+=77;return response([],{url});}});await c.request('owners');await c.request('roles');assert.deepEqual(dispatches,[0,577]);assert.equal(waitCalls,2);});
test('transport retains active admission until complete response body',async()=>{let finish;const c=h.createClient({bundle,key:'x',delegate:async url=>({url,status:200,redirected:false,headers:new Headers({'content-type':'application/json','content-range':'*/*'}),body:new ReadableStream({start(ctrl){finish=()=>{ctrl.enqueue(Buffer.from('[]'));ctrl.close();};}})})});const first=c.request('owners');await Promise.resolve();await assert.rejects(c.request('roles'),/transport_stopped_or_concurrent/);finish();await first;await assert.rejects(c.request('owners'),/transport_stopped_or_concurrent/);});
test('concurrent denial during pacing prevents admitted dispatch after wait',async()=>{let clock=0,release;const calls=[];const c=h.createClient({bundle,key:'x',now:()=>clock,wait:async ms=>new Promise(r=>{release=()=>{clock+=ms;r();};}),delegate:async url=>{calls.push(1);return response([],{url});}});await c.request('owners');const pending=c.request('roles');await Promise.resolve();await assert.rejects(c.request('sources'),/transport_stopped_or_concurrent/);release();await assert.rejects(pending,/transport_stopped_or_time_bound/);assert.equal(calls.length,1);});
test('preview transport cannot dispatch write; latch prevents later reads',async()=>{const t=transport({allowWrites:false});await assert.rejects(t.client.request('mutation',0,0,state()),/preview_write_refused/);await assert.rejects(t.client.request('owners'),/transport_stopped_or_concurrent/);assert.equal(t.calls.length,0);});
test('write TTL revalidated after cooldown before intent or dispatch',async()=>{let valid=true;const t=transport({validateWrite:()=>{assert.ok(valid,'expired');},wait:async()=>{valid=false;t.advance(500);}});await t.client.request('owners');await assert.rejects(t.client.request('mutation',0,0,state()),/expired/);assert.equal(t.calls.length,1);assert.equal(t.events.filter(e=>e.method==='PATCH').length,0);});
test('each mutation index may be dispatched once, never replayed',async()=>{const t=transport({delegate:async()=>response([], {status:200})});await t.client.request('mutation',0,0,state());await assert.rejects(t.client.request('mutation',0,0,state()),/mutation_retry_forbidden/);});
test('PATCH intent persists exact one-field body and full CAS before dispatch',async()=>{const events=[];const t=transport({event:e=>events.push(e),delegate:async()=>{assert.equal(events.at(-1).event,'request_intent');assert.equal(events.at(-1).method,'PATCH');assert.deepEqual(events.at(-1).body,{decaf:true});assert.ok(events.at(-1).cas_url.includes('decaf=is.null'));return response([]);}});await t.client.request('mutation',0,0,state());assert.equal(events.at(-1).event,'request_result');assert.equal(JSON.stringify(events).includes('test-secret'),false);});
test('write journal failure prevents dispatch and latches transport',async()=>{let calls=0;const c=h.createClient({bundle,key:'x',allowWrites:true,event:()=>{throw Error('disk_full');},delegate:async()=>{calls++;return response([]);}});await assert.rejects(c.request('mutation',0,0,state()),/disk_full/);await assert.rejects(c.request('owners'));assert.equal(calls,0);});
test('HTTP failure is redacted, stops immediately and never retries ambiguous POST',async()=>{let calls=0;const events=[];const c=h.createClient({bundle,key:'SECRET',allowWrites:true,event:e=>events.push(e),delegate:async url=>{calls++;return response([],{url,status:503,body:JSON.stringify({code:'PGRST002',message:'secret SQL SECRET'})});}});await assert.rejects(c.request('mutation',0,1,state()),/database_http_error/);await assert.rejects(c.request('mutation',0,1,state()),/transport_stopped_or_concurrent/);assert.equal(calls,1);assert.equal(JSON.stringify(events).includes('SECRET'),false);});
test('same-origin changed response URL is rejected and no follow-up dispatch allowed',async()=>{const t=transport({delegate:async()=>response([],{url:h.ORIGIN+'/rest/v1/entities?different=true'})});await assert.rejects(t.client.request('owners'),/response_url_redirect/);await assert.rejects(t.client.request('owners'),/transport_stopped_or_concurrent/);});
for(const config of [{status:200,headers:{'content-type':'text/html'}},{status:200,headers:{'content-range':'0-9/*'}},{status:200,body:'{}'},{status:200,url:'https://elsewhere.invalid/'}])test('bad response rejected '+JSON.stringify(config),async()=>{const t=transport({delegate:async()=>response([],config)});await assert.rejects(t.client.request('owners'));await assert.rejects(t.client.request('roles'),/transport_stopped_or_concurrent/);});
test('100-row cap is incomplete and rejected',async()=>{const t=transport({delegate:async()=>response(Array.from({length:100},()=>({id:'x'})))});await assert.rejects(t.client.request('owners'),/response_shape_or_bound/);});
test('optional missing crawl-state only exact 404/PGRST205 is admissible',async()=>{const t=transport({delegate:async()=>response([],{status:404,body:'{"code":"PGRST205"}'})});assert.deepEqual(await t.client.request('crawlState'),[]);assert.ok(t.events.some(e=>e.event==='optional_crawl_state_table_absent'));const bad=transport({delegate:async()=>response([],{status:404,body:'{"code":"PGRST205"}'})});await assert.rejects(bad.client.request('owners'),/database_http_error/);});
test('4 MiB streaming cap rejects oversized body',async()=>{const t=transport({delegate:async()=>response([],{body:' '.repeat(4*1024*1024+1)})});await assert.rejects(t.client.request('owners'),/response_too_large/);});
test('20-second timeout covers streaming body',async t=>{t.mock.timers.enable({apis:['setTimeout']});const c=h.createClient({bundle,key:'x',delegate:async(url,opts)=>({url,status:200,redirected:false,headers:new Headers({'content-type':'application/json','content-range':'*/*'}),body:new ReadableStream({start(controller){opts.signal.addEventListener('abort',()=>controller.error(Object.assign(Error('aborted'),{code:'ABORT_ERR'})));}})})});const pending=c.request('owners');await Promise.resolve();t.mock.timers.tick(20000);await assert.rejects(pending,/aborted/);});
test('request and total elapsed bounds fail before dispatch',async()=>{let calls=0;const t=transport({delegate:async()=>{calls++;return response([]);}});for(let i=0;i<h.MAX_REQUESTS;i++)await t.client.request('owners');await assert.rejects(t.client.request('owners'),/request_or_time_bound/);assert.equal(calls,h.MAX_REQUESTS);const old=transport();old.advance(h.MAX_TIME);await assert.rejects(old.client.request('owners'),/request_or_time_bound/);assert.equal(old.calls.length,0);});
test('exclusive lock refuses existing file and checks inode/token before release',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'null-fills-lock-')),file=path.join(dir,'lock');try{const lock=h.acquireLock(file);assert.throws(()=>h.acquireLock(file),/EEXIST/);lock.check();lock.release();assert.equal(fs.existsSync(file),false);const second=h.acquireLock(file);fs.writeFileSync(file,'changed');assert.throws(()=>second.check(),/lock_ownership_lost/);assert.throws(()=>second.release(),/lock_ownership_lost/);assert.equal(fs.readFileSync(file,'utf8'),'changed');}finally{fs.rmSync(dir,{recursive:true});}});
test('main uses fixed one-shot apply dir, exclusive output and fsynced journal',()=>{const source=fs.readFileSync(require.resolve('./apply-batch4d-eleven-fields-paced.cjs'),'utf8');assert.ok(source.includes("opts.mode==='apply'?'-apply':'-preview-'+crypto.randomUUID()"));assert.ok(source.includes("fs.mkdirSync(dir,{mode:0o700})"));assert.ok(source.includes("fs.openSync(path.join(dir,'events.ndjson'),'wx',0o600)"));assert.ok(source.includes('fs.fsyncSync(fd)'));assert.ok(source.includes("process.env.NODE_TLS_REJECT_UNAUTHORIZED='1'"));assert.equal(source.includes("resolution=merge-duplicates"),false);});

