'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const h=require('./apply-batch5a-partial-null-fills.cjs');
// Every transport in this file is mocked. Accidental real dispatch is a test failure.
globalThis.fetch=async()=>{throw Error('NETWORK_FORBIDDEN');};
const bundle=h.loadBundle(),clone=h.copy,now=Date.parse('2026-09-27T10:30:00Z');
function preview(){return{at:new Date(now).toISOString(),status:'preview_complete',proposal_sha256:h.PROPOSAL_SHA,helper_sha256:h.sha(fs.readFileSync(require.resolve('./apply-batch5a-partial-null-fills.cjs'))),before:clone(bundle.baseline)};}
function fakeClient({before,hook,mutate}={}){const state=clone(before||bundle.baseline),writes=[],calls=[];return{state,writes,calls,get requests(){return calls.length;},async request(kind,offset=0,index,expected){calls.push({kind,offset,index});if(hook){const result=hook({kind,offset,index,state,calls,writes});if(result!==undefined)return result;}
 if(kind!=='mutation')return offset?[]:clone(state[kind]);const a=bundle.actions[index];writes.push(clone(a));const key=a.kind==='patchImage'?'parents':'facts';let row;
 if(a.kind==='insertFact')row={...clone(a.body),created_at:new Date(now).toISOString(),updated_at:new Date(now).toISOString()};else row={...state[key].find(r=>(r.product_id||r.id)===a.product_id),...clone(a.body),updated_at:new Date(now).toISOString()};
 if(mutate)row=mutate(row,a,index);state[key]=state[key].filter(r=>(r.product_id||r.id)!==a.product_id).concat(clone(row));return[clone(row)];}};}
function response(rows=[],{status=200,offset=0,headers={},body,url}={}){const r=new Response(body===undefined?JSON.stringify(rows):body,{status,headers:{'content-type':'application/json','content-range':rows.length?`${offset}-${offset+rows.length-1}/*`:'*/*',...headers}});if(url)Object.defineProperty(r,'url',{value:url});return r;}
function transport(options={}){let clock=0;const calls=[],events=[],waits=[];const delegate=options.delegate|| (async(url,opts)=>{calls.push({url,opts,at:clock});return response([]);});const client=h.createClient({bundle,key:'test-secret-not-real',allowWrites:true,now:()=>clock,wait:async ms=>{waits.push(ms);clock+=ms;},event:e=>events.push(e),...options,delegate:async(url,opts)=>{const r=await delegate(url,opts);if(!r.url)Object.defineProperty(r,'url',{value:url});return r;}});return{client,calls,events,waits,get clock(){return clock;},advance:n=>{clock+=n;}};}

test('exact pinned local proposal closure yields only ten allowed actions',()=>{assert.equal(bundle.actions.length,10);assert.deepEqual(bundle.actions.map(a=>a.kind),['patchFact',...Array(4).fill('insertFact'),...Array(5).fill('patchImage')]);assert.equal(bundle.baseline.variants.length,9);assert.equal(bundle.baseline.facts.length,1);});
test('unknown inserted facts including decaf are explicitly null',()=>{for(const a of bundle.actions.filter(a=>a.kind==='insertFact')){for(const k of ['origin_hub_id','variety','elevation_m','decaf'])assert.equal(a.body[k],null);if(a.product_id!==h.IDS[3])assert.equal(a.body.roast_level,null);}});
test('proposal pin change stops before any requests',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'null-fills-pin-'));try{fs.writeFileSync(path.join(dir,h.PROPOSAL_FILE),'{}');assert.throws(()=>h.loadBundle(dir),/proposal_hash/);}finally{fs.rmSync(dir,{recursive:true});}});
test('each fixed GET targets only allowed Supabase tables and five owners/products',()=>{for(const k of h.READS){const d=h.descriptor(k,bundle),u=new URL(d.url);assert.equal(d.method,'GET');assert.equal(u.origin,h.ORIGIN);assert.match(u.pathname,/^\/rest\/v1\/[a-z_]+$/);assert.equal(d.body,undefined);assert.equal(u.searchParams.get('limit'),'100');assert.equal(u.searchParams.get('select'),k==='sourceProducts'?'id,entity_id,source_url':'*');}});
test('source-key ownership probe is global exact five source keys, not owner-filtered',()=>{const q=new URL(h.descriptor('sourceKeys',bundle).url).searchParams;assert.equal(q.get('source'),'eq.my_coffee_explorer');assert.equal(q.has('entity_id'),false);for(const s of bundle.baseline.sources)assert.ok(q.get('source_id').includes(s.source_id));});
test('canonical probes include forward and inbound links only',()=>{for(const k of ['canonicalOut','canonicalIn']){const q=new URL(h.descriptor(k,bundle).url).searchParams;assert.equal(q.get('attribute_key'),'eq.canonical_roaster_entity_id');assert.ok(q.get(k==='canonicalOut'?'entity_id':'attribute_value').includes(bundle.products[0].entity_id));}});
test('all claims history and active claims are separately bounded',()=>{assert.equal(new URL(h.descriptor('ownerClaims',bundle).url).searchParams.has('status'),false);assert.equal(new URL(h.descriptor('activeClaims',bundle).url).searchParams.get('status'),'eq.running');});
test('image PATCH body has only original_image_url with null/version/identity CAS',()=>{for(let i=5;i<10;i++){const d=h.descriptor('mutation',bundle,0,i,bundle.baseline),q=new URL(d.url).searchParams;assert.equal(d.method,'PATCH');assert.equal(new URL(d.url).pathname,'/rest/v1/products');assert.deepEqual(Object.keys(d.body),['original_image_url']);assert.equal(q.get('original_image_url'),'is.null');for(const k of ['id','entity_id','source_url','updated_at'])assert.ok(q.get(k).startsWith('eq.'));assert.equal(q.has('description'),false);assert.equal(q.has('metadata'),false);assert.ok(d.url.length<2048);}});
test('Cognito fact PATCH uses full old row CAS including two null fields',()=>{const d=h.descriptor('mutation',bundle,0,0,bundle.baseline),q=new URL(d.url).searchParams;assert.deepEqual(d.body,{process:'Anaerobic Natural',elevation_m:1950});for(const[k,v]of Object.entries(bundle.baseline.facts[0]))assert.equal(q.get(k),v===null?'is.null':'eq.'+v);});
test('missing-fact writes are plain POST without upsert, timestamp or invented fields',()=>{for(let i=1;i<5;i++){const d=h.descriptor('mutation',bundle,0,i,bundle.baseline);assert.equal(d.method,'POST');assert.equal(new URL(d.url).pathname,'/rest/v1/coffee_facts');assert.equal(d.body.created_at,undefined);assert.equal(d.body.updated_at,undefined);assert.equal(d.body.decaf,null);assert.equal(new URL(d.url).searchParams.has('on_conflict'),false);}});
test('arbitrary kind, action, offset, non-null image and existing insert denied',()=>{assert.throws(()=>h.descriptor('delete',bundle),/request_out_of_scope/);assert.throws(()=>h.descriptor('mutation',bundle,0,10,bundle.baseline),/mutation_scope/);assert.throws(()=>h.descriptor('owners',bundle,100),/offset_scope/);let b=clone(bundle.baseline);b.parents[0].original_image_url='already';assert.throws(()=>h.descriptor('mutation',bundle,0,5,b),/image_not_null/);b=clone(bundle.baseline);b.facts.push({product_id:h.IDS[1]});assert.throws(()=>h.descriptor('mutation',bundle,0,1,b),/fact_already_exists/);});
test('default/check is offline, no retry/resume/arbitrary CLI accepted',()=>{assert.deepEqual(h.cli([]),{mode:'check'});assert.deepEqual(h.cli(['--check']),{mode:'check'});assert.deepEqual(h.cli(['--preview']),{mode:'preview'});for(const args of [['--run'],['--resume'],['--apply','x','a'.repeat(64),'--retry'],['--preview','x']])assert.throws(()=>h.cli(args),/invalid_cli/);assert.equal(h.cli(['--apply','x','a'.repeat(64),'--confirm-ten-null-fill-writes']).mode,'apply');});
test('preview performs only exact reads and explicit empty continuation proofs',async()=>{const c=fakeClient(),r=await h.execute({client:c,bundle,now:()=>now});assert.equal(r.status,'preview_complete');assert.equal(r.writes,0);assert.equal(c.writes.length,0);for(const k of h.READS){assert.equal(c.calls.filter(x=>x.kind===k&&!x.offset).length,1);if(bundle.baseline[k].length)assert.equal(c.calls.filter(x=>x.kind===k&&x.offset).length,1);}});
for(const key of ['owners','roles','sources','sourceKeys','canonicalOut','canonicalIn','crawlState','activeClaims','parents','sourceProducts','variants','facts','media','assets','knownPages','claims','ownerClaims'])test('fresh '+key+' drift prevents every write',async()=>{const before=clone(bundle.baseline);if(before[key].length)before[key][0].unexpected_drift=true;else before[key].push({unexpected_drift:true});const c=fakeClient({before});await assert.rejects(h.execute({client:c,bundle,mode:'apply',preview:preview(),now:()=>now}),new RegExp(key+'_drift'));assert.equal(c.writes.length,0);});
test('unexpected continuation refuses truncated snapshot',async()=>{const c=fakeClient({hook:({kind,offset})=>kind==='variants'&&offset?[{id:'extra'}]:undefined});await assert.rejects(h.execute({client:c,bundle,now:()=>now}),/nonempty_continuation:variants/);assert.equal(c.writes.length,0);});
test('apply exactly ten writes; all unspecified rows/fields preserved and unknown decaf remains null',async()=>{const c=fakeClient(),events=[],r=await h.execute({client:c,bundle,mode:'apply',preview:preview(),now:()=>now,append:e=>events.push(e)});assert.equal(r.status,'partial_null_fills_verified');assert.equal(c.writes.length,10);assert.equal(r.after.facts.length,5);assert.ok(r.after.facts.every(f=>f.decaf===null));assert.equal(r.full_product_completion,false);for(const k of h.READS.filter(k=>!['parents','facts'].includes(k)))assert.deepEqual(r.after[k],r.before[k]);for(const p of r.after.parents){const old=r.before.parents.find(x=>x.id===p.id);for(const k of Object.keys(old).filter(k=>!['updated_at','original_image_url'].includes(k)))assert.deepEqual(p[k],old[k]);}assert.equal(events.filter(e=>e.event==='mutation_attempt_no_retry').length,10);});
test('full targeted state re-read before every one of ten writes',async()=>{const c=fakeClient();await h.execute({client:c,bundle,mode:'apply',preview:preview(),now:()=>now});assert.equal(c.calls.filter(x=>x.kind==='owners'&&!x.offset).length,12);for(let i=0;i<10;i++){const at=c.calls.findIndex(x=>x.kind==='mutation'&&x.index===i),previous=i?c.calls.findIndex(x=>x.kind==='mutation'&&x.index===i-1):-1;for(const k of h.READS)assert.ok(c.calls.slice(previous+1,at).some(x=>x.kind===k&&!x.offset));}});
test('drift after first mutation stops before second, never silently success',async()=>{const c=fakeClient({hook:({kind,offset,state,writes})=>{if(kind==='owners'&&!offset&&writes.length===1)state.owners[0].website_url='https://changed.invalid/';}});await assert.rejects(h.execute({client:c,bundle,mode:'apply',preview:preview(),now:()=>now}),/owners_drift/);assert.equal(c.writes.length,1);});
test('failed/empty CAS stops all remaining mutations',async()=>{const c=fakeClient({hook:({kind})=>kind==='mutation'?[]:undefined});await assert.rejects(h.execute({client:c,bundle,mode:'apply',preview:preview(),now:()=>now}),/mutation_not_one/);assert.equal(c.calls.filter(c=>c.kind==='mutation').length,1);});
test('server changing unrelated parent field is detected at first image write',async()=>{const c=fakeClient({mutate:(row,a)=>a.kind==='patchImage'?{...row,description:'changed'}:row});await assert.rejects(h.execute({client:c,bundle,mode:'apply',preview:preview(),now:()=>now}),/preservation:description/);assert.equal(c.writes.length,6);});
test('server invented decaf false is refused on first fact insert',async()=>{const c=fakeClient({mutate:(row,a)=>a.kind==='insertFact'?{...row,decaf:false}:row});await assert.rejects(h.execute({client:c,bundle,mode:'apply',preview:preview(),now:()=>now}),/insert_fact_value:decaf/);assert.equal(c.writes.length,2);});
test('unknown fact schema or malformed timestamps rejected',()=>{const a=bundle.actions[1],row={...a.body,created_at:new Date(now).toISOString(),updated_at:new Date(now).toISOString()};assert.throws(()=>h.validateReturned([{...row,surprise:null}],a,bundle.baseline),/fact_schema/);assert.throws(()=>h.validateReturned([{...row,updated_at:null}],a,bundle.baseline),/fact_timestamp/);});
test('preview hash/helper/timestamp binding and stale/future age stop writes',()=>{for(const p of [{...preview(),proposal_sha256:'x'},{...preview(),helper_sha256:'x'}])assert.throws(()=>h.validatePreview(p,bundle,now),/preview_binding/);for(const at of [now+h.TTL,now-1])assert.throws(()=>h.validatePreview(preview(),bundle,at),/preview_expired/);h.validatePreview(preview(),bundle,now+h.TTL-1);});
test('preview expiry during a repeated context read stops subsequent write',async()=>{let time=now;const c=fakeClient({hook:({kind,offset,writes})=>{if(kind==='owners'&&!offset&&writes.length===1)time=now+h.TTL;}});await assert.rejects(h.execute({client:c,bundle,mode:'apply',preview:preview(),now:()=>time}),/preview_expired/);assert.equal(c.writes.length,1);});
test('transport sends fixed origin credential headers and error redirect mode only',async()=>{const t=transport();await t.client.request('owners');assert.equal(t.calls.length,1);assert.equal(new URL(t.calls[0].url).origin,h.ORIGIN);assert.equal(t.calls[0].opts.redirect,'error');assert.equal(t.calls[0].opts.headers.Authorization,'Bearer test-secret-not-real');assert.ok(t.calls[0].opts.signal);assert.equal(JSON.stringify(t.events).includes('test-secret'),false);});
test('transport loops on early wake and measures pacing after body completion',async()=>{let clock=0,waitCalls=0;const dispatches=[];const c=h.createClient({bundle,key:'x',now:()=>clock,wait:async n=>{waitCalls++;clock+=waitCalls===1?n-1:n;},delegate:async url=>{dispatches.push(clock);clock+=77;return response([],{url});}});await c.request('owners');await c.request('roles');assert.deepEqual(dispatches,[0,577]);assert.equal(waitCalls,2);});
test('transport retains active admission until complete response body',async()=>{let finish;const c=h.createClient({bundle,key:'x',delegate:async url=>({url,status:200,redirected:false,headers:new Headers({'content-type':'application/json','content-range':'*/*'}),body:new ReadableStream({start(ctrl){finish=()=>{ctrl.enqueue(Buffer.from('[]'));ctrl.close();};}})})});const first=c.request('owners');await Promise.resolve();await assert.rejects(c.request('roles'),/transport_stopped_or_concurrent/);finish();await first;await assert.rejects(c.request('owners'),/transport_stopped_or_concurrent/);});
test('concurrent denial during pacing prevents admitted dispatch after wait',async()=>{let clock=0,release;const calls=[];const c=h.createClient({bundle,key:'x',now:()=>clock,wait:async ms=>new Promise(r=>{release=()=>{clock+=ms;r();};}),delegate:async url=>{calls.push(1);return response([],{url});}});await c.request('owners');const pending=c.request('roles');await Promise.resolve();await assert.rejects(c.request('sources'),/transport_stopped_or_concurrent/);release();await assert.rejects(pending,/transport_stopped_or_time_bound/);assert.equal(calls.length,1);});
test('preview transport cannot dispatch write; latch prevents later reads',async()=>{const t=transport({allowWrites:false});await assert.rejects(t.client.request('mutation',0,0,bundle.baseline),/preview_write_refused/);await assert.rejects(t.client.request('owners'),/transport_stopped_or_concurrent/);assert.equal(t.calls.length,0);});
test('write TTL revalidated after cooldown before intent or dispatch',async()=>{let valid=true;const t=transport({validateWrite:()=>{assert.ok(valid,'expired');},wait:async()=>{valid=false;t.advance(500);}});await t.client.request('owners');await assert.rejects(t.client.request('mutation',0,0,bundle.baseline),/expired/);assert.equal(t.calls.length,1);assert.equal(t.events.filter(e=>e.method==='PATCH').length,0);});
test('each mutation index may be dispatched once, never replayed',async()=>{const t=transport({delegate:async()=>response([], {status:200})});await t.client.request('mutation',0,0,bundle.baseline);await assert.rejects(t.client.request('mutation',0,0,bundle.baseline),/mutation_retry_forbidden/);});
test('POST intent precedes dispatch; exact body persisted without credentials',async()=>{const events=[];const t=transport({event:e=>events.push(e),delegate:async()=>{assert.equal(events.at(-1).event,'request_intent');assert.equal(events.at(-1).method,'POST');assert.deepEqual(events.at(-1).body,bundle.actions[1].body);return response([{...bundle.actions[1].body}],{status:201});}});await t.client.request('mutation',0,1,bundle.baseline);assert.equal(events.at(-1).event,'request_result');assert.equal(JSON.stringify(events).includes('test-secret'),false);});
test('write journal failure prevents dispatch and latches transport',async()=>{let calls=0;const c=h.createClient({bundle,key:'x',allowWrites:true,event:()=>{throw Error('disk_full');},delegate:async()=>{calls++;return response([]);}});await assert.rejects(c.request('mutation',0,0,bundle.baseline),/disk_full/);await assert.rejects(c.request('owners'));assert.equal(calls,0);});
test('HTTP failure is redacted, stops immediately and never retries ambiguous POST',async()=>{let calls=0;const events=[];const c=h.createClient({bundle,key:'SECRET',allowWrites:true,event:e=>events.push(e),delegate:async url=>{calls++;return response([],{url,status:503,body:JSON.stringify({code:'PGRST002',message:'secret SQL SECRET'})});}});await assert.rejects(c.request('mutation',0,1,bundle.baseline),/database_http_error/);await assert.rejects(c.request('mutation',0,1,bundle.baseline),/transport_stopped_or_concurrent/);assert.equal(calls,1);assert.equal(JSON.stringify(events).includes('SECRET'),false);});
test('same-origin changed response URL is rejected and no follow-up dispatch allowed',async()=>{const t=transport({delegate:async()=>response([],{url:h.ORIGIN+'/rest/v1/entities?different=true'})});await assert.rejects(t.client.request('owners'),/response_url_redirect/);await assert.rejects(t.client.request('owners'),/transport_stopped_or_concurrent/);});
for(const config of [{status:200,headers:{'content-type':'text/html'}},{status:200,headers:{'content-range':'0-9/*'}},{status:200,body:'{}'},{status:200,url:'https://elsewhere.invalid/'}])test('bad response rejected '+JSON.stringify(config),async()=>{const t=transport({delegate:async()=>response([],config)});await assert.rejects(t.client.request('owners'));await assert.rejects(t.client.request('roles'),/transport_stopped_or_concurrent/);});
test('100-row cap is incomplete and rejected',async()=>{const t=transport({delegate:async()=>response(Array.from({length:100},()=>({id:'x'})))});await assert.rejects(t.client.request('owners'),/response_shape_or_bound/);});
test('optional missing crawl-state only exact 404/PGRST205 is admissible',async()=>{const t=transport({delegate:async()=>response([],{status:404,body:'{"code":"PGRST205"}'})});assert.deepEqual(await t.client.request('crawlState'),[]);assert.ok(t.events.some(e=>e.event==='optional_crawl_state_table_absent'));const bad=transport({delegate:async()=>response([],{status:404,body:'{"code":"PGRST205"}'})});await assert.rejects(bad.client.request('owners'),/database_http_error/);});
test('4 MiB streaming cap rejects oversized body',async()=>{const t=transport({delegate:async()=>response([],{body:' '.repeat(4*1024*1024+1)})});await assert.rejects(t.client.request('owners'),/response_too_large/);});
test('20-second timeout covers streaming body',async t=>{t.mock.timers.enable({apis:['setTimeout']});const c=h.createClient({bundle,key:'x',delegate:async(url,opts)=>({url,status:200,redirected:false,headers:new Headers({'content-type':'application/json','content-range':'*/*'}),body:new ReadableStream({start(controller){opts.signal.addEventListener('abort',()=>controller.error(Object.assign(Error('aborted'),{code:'ABORT_ERR'})));}})})});const pending=c.request('owners');await Promise.resolve();t.mock.timers.tick(20000);await assert.rejects(pending,/aborted/);});
test('request and total elapsed bounds fail before dispatch',async()=>{let calls=0;const t=transport({delegate:async()=>{calls++;return response([]);}});for(let i=0;i<h.MAX_REQUESTS;i++)await t.client.request('owners');await assert.rejects(t.client.request('owners'),/request_or_time_bound/);assert.equal(calls,h.MAX_REQUESTS);const old=transport();old.advance(h.MAX_TIME);await assert.rejects(old.client.request('owners'),/request_or_time_bound/);assert.equal(old.calls.length,0);});
test('exclusive lock refuses existing file and checks inode/token before release',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'null-fills-lock-')),file=path.join(dir,'lock');try{const lock=h.acquireLock(file);assert.throws(()=>h.acquireLock(file),/EEXIST/);lock.check();lock.release();assert.equal(fs.existsSync(file),false);const second=h.acquireLock(file);fs.writeFileSync(file,'changed');assert.throws(()=>second.check(),/lock_ownership_lost/);assert.throws(()=>second.release(),/lock_ownership_lost/);assert.equal(fs.readFileSync(file,'utf8'),'changed');}finally{fs.rmSync(dir,{recursive:true});}});
test('main uses fixed one-shot apply dir, exclusive output and fsynced journal',()=>{const source=fs.readFileSync(require.resolve('./apply-batch5a-partial-null-fills.cjs'),'utf8');assert.ok(source.includes("opts.mode==='apply'?'-apply':'-preview-'+crypto.randomUUID()"));assert.ok(source.includes("fs.mkdirSync(dir,{mode:0o700})"));assert.ok(source.includes("fs.openSync(path.join(dir,'events.ndjson'),'wx',0o600)"));assert.ok(source.includes('fs.fsyncSync(fd)'));assert.ok(source.includes("process.env.NODE_TLS_REJECT_UNAUTHORIZED='1'"));assert.equal(source.includes("resolution=merge-duplicates"),false);});
