'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
// Every request below uses a literal local fake delegate. Actual dispatch is forbidden.
globalThis.fetch=()=>{throw Error('LIVE_FETCH_FORBIDDEN');};
for(const p of ['node:http','node:https']){const m=require(p);m.request=m.get=()=>{throw Error('LIVE_HTTP_FORBIDDEN');};}
const h=require('./apply-profile-five-sources.cjs'),bundle=h.loadBundle(),clone=x=>structuredClone(x),T0=Date.parse('2026-09-27T19:00:00Z');
function preview(b=bundle,t=T0){return{at:new Date(t).toISOString(),status:'preview_complete',helper_sha256:h.helperSha(),plan_sha256:h.PLAN_SHA,before:clone(b.before),constraints_confirmed:true,writes:0};}
function response(url,rows,status=200,offset=0,overrides={}){const r=new Response(typeof rows==='string'?rows:JSON.stringify(rows),{status,headers:{'Content-Type':'application/json','Content-Range':Array.isArray(rows)&&rows.length?offset+'-'+(offset+rows.length-1)+'/*':'*/*',...overrides.headers}});Object.defineProperty(r,'url',{value:overrides.url||url});if(overrides.redirected)Object.defineProperty(r,'redirected',{value:true});return r;}
function fixture({b=bundle,state=clone(bundle.before),allowWrites=true,delegateHook,eventHook,beforeWriteHook,earlyWake=false}={}){
 let clock=T0,readAt=null,post=0;const calls=[],events=[],waits=[];
 const now=()=>clock,wait=async ms=>{waits.push(ms);clock+=earlyWake&&ms>1?ms-1:ms;};
 const event=e=>{events.push({...e,clock});eventHook?.(e);};
 const delegate=async(url,init)=>{const u=new URL(url),offset=Number(u.searchParams.get('offset')||0),write=init.method==='POST';const kind=write?'insertSources':b.pre.KINDS.find(k=>h.descriptor(k,b,offset).url===url);assert(kind);calls.push({url,init,kind,clock});
  if(delegateHook){const value=await delegateHook({url,init,kind,offset,state,calls,advance:ms=>{clock+=ms;}});if(value)return value;}
  if(write){post++;assert.equal(u.pathname,'/rest/v1/entity_source_ids');assert.equal(u.searchParams.has('on_conflict'),false);assert.equal(init.headers.Prefer,'return=representation');const rows=JSON.parse(init.body).map(r=>({...r,last_synced_at:r.last_synced_at.replace('Z','+00:00'),created_at:new Date(clock).toISOString().replace('Z','+00:00')}));state.ownerSources.push(...rows);state.sourceKeys.push(...rows);return response(url,rows,201);}
  const rows=state[kind].slice().sort((a,z)=>{const akey=kind==='roles'?a.entity_id+'\n'+a.role:a.id,zkey=kind==='roles'?z.entity_id+'\n'+z.role:z.id;return akey<zkey?-1:akey>zkey?1:0;}).slice(offset,offset?offset+1:101);return response(url,rows,200,offset);
 };
 let pv=preview(b);const client=h.createClient({bundle:b,key:'fixture-only-secret',allowWrites,delegate,event,now,wait,beforeWrite:()=>{h.validatePreview(pv,b,clock);assert(readAt!==null&&clock-readAt<5000);beforeWriteHook?.({clock,calls});}});
 return{b,state,client,calls,events,waits,now,advance:ms=>{clock+=ms;},setPreview:p=>{pv=p;},get posts(){return post;},run:mode=>h.execute({bundle:b,client,mode,preview:pv,constraintsConfirmed:true,event,now,authorizeWrite:t=>{readAt=t;}})};
}
test('fixed plan is exactly five source rows for five existing owners and two preserved competitors',()=>{assert.equal(bundle.plan.actions.length,5);assert.equal(bundle.scope.owners.length,7);assert.equal(bundle.before.ownerSources.length,12);assert.equal(bundle.before.canonical.length,0);assert.equal(h.cli([]).mode,'check');assert.equal(h.cli(['--check']).mode,'check');});
test('all insert fields preserve literal profile identity and exclude enrichment/crawl fields',()=>{const d=h.descriptor('insertSources',bundle,0,new Date(T0).toISOString());assert.equal(d.method,'POST');assert.equal(d.body.length,5);for(const r of d.body){assert.deepEqual(Object.keys(r).sort(),['confidence','entity_id','id','last_synced_at','raw_data','source','source_id','source_url']);assert.equal(r.raw_data.asserts_own_roasting,false);assert.equal(r.raw_data.products,undefined);assert.equal(r.raw_data.website_url,undefined);}});
test('source-key GET also checks the five new UUIDs for global primary-key collisions',()=>{const u=new URL(h.descriptor('sourceKeys',bundle).url);for(const a of bundle.plan.actions)assert(u.searchParams.get('or').includes(a.source_insert.id));assert.equal(u.searchParams.get('limit'),'101');});
test('complete preview has fifteen GETs, EOF confirmations, zero POSTs',async()=>{const f=fixture({allowWrites:false});const r=await f.run('preview');assert.equal(r.requests,15);assert.equal(r.writes,0);assert.equal(f.posts,0);assert.equal(f.calls.filter(c=>new URL(c.url).searchParams.has('offset')).length,7);h.validatePreview(r,bundle,f.now());});
test('complete apply is one five-row POST and thirty GETs, preserving full seven-identity state',async()=>{const f=fixture(),r=await f.run('apply');assert.equal(r.status,'complete');assert.equal(r.requests,31);assert.equal(f.posts,1);assert.equal(r.source_inserts,5);assert.equal(r.after.ownerSources.length,17);for(const k of bundle.pre.KINDS.filter(k=>!['sourceKeys','ownerSources'].includes(k)))assert(h.same(h.sorted(r.before[k]),h.sorted(r.after[k])));assert.equal(r.after.entities.length,7);assert.equal(r.after.roles.length,11);assert.equal(r.after.locations.length,9);assert(!JSON.stringify(f.events).includes('fixture-only-secret'));assert(f.calls.every(c=>['GET','POST'].includes(c.init.method)));});
test('completion pacing loops after an early wake and every next intent is at least500ms later',async()=>{const f=fixture({earlyWake:true});await f.run('apply');assert(f.waits.includes(1));for(let i=1;i<f.calls.length;i++)assert(f.calls[i].clock-f.calls[i-1].clock>=500);});
for(const k of ['entities','roles','locations','ownerSources','sourceKeys','canonical','entityConflicts','locationConflicts'])test('full-row '+k+' drift blocks all writes',async()=>{const f=fixture();if(k==='canonical')f.state[k].push({id:'unexpected',entity_id:bundle.scope.owners[0],attribute_value:bundle.scope.owners[1]});else f.state[k][0]={...f.state[k][0],unexpected_drift:'changed'};await assert.rejects(f.run('apply'),/state_drift/);assert.equal(f.posts,0);});
test('new source binding blocks apply instead of upsert or ignore-duplicate',async()=>{const f=fixture();f.state.sourceKeys.push({...bundle.plan.actions[0].source_insert,created_at:new Date(T0).toISOString()});await assert.rejects(f.run('apply'),/state_drift/);assert.equal(f.posts,0);});
test('planned source UUID occupied by another key blocks apply',async()=>{const f=fixture();f.state.sourceKeys.push({...bundle.plan.actions[0].source_insert,source_id:'different-key',created_at:new Date(T0).toISOString()});await assert.rejects(f.run('apply'),/state_drift/);assert.equal(f.posts,0);});
test('unexpected EOF row blocks a false complete preview',async()=>{const f=fixture({delegateHook:({url,offset})=>offset?response(url,[{id:'overflow'}],200,offset):null});await assert.rejects(f.run('preview'),/nonempty_continuation/);assert.equal(f.posts,0);});
test('101-row response is incomplete and refused',async()=>{const f=fixture({delegateHook:({url})=>response(url,Array.from({length:101},(_,i)=>({id:String(i)})))});await assert.rejects(f.run('preview'),/row_bound/);assert.equal(f.calls.length,1);});
test('HTTP500 latches a stop with no automatic read retry',async()=>{const f=fixture({delegateHook:({url})=>response(url,{code:'57014'},500)});await assert.rejects(f.run('preview'),/database_http_error/);await assert.rejects(f.client.request('entities'),/transport_stopped/);assert.equal(f.calls.length,1);});
test('uncertain POST response ends once and cannot replay',async()=>{const f=fixture({delegateHook:({kind})=>{if(kind==='insertSources')throw Error('socket lost after possible commit');}});await assert.rejects(f.run('apply'),/socket lost/);await assert.rejects(f.client.request('insertSources',0,new Date(T0).toISOString()),/transport_stopped/);assert.equal(f.calls.filter(c=>c.kind==='insertSources').length,1);});
test('duplicate-key POST response is a failure, never resolved by overwrite',async()=>{const f=fixture({delegateHook:({url,kind})=>kind==='insertSources'?response(url,{code:'23505'},409):null});await assert.rejects(f.run('apply'),/database_http_error/);assert.equal(f.calls.filter(c=>c.kind==='insertSources').length,1);});
test('returned partial insert representation stops without automatic rollback or second POST',async()=>{const f=fixture({delegateHook:({url,kind})=>kind==='insertSources'?response(url,[],201):null});await assert.rejects(f.run('apply'),/insert_count/);assert.equal(f.calls.filter(c=>c.kind==='insertSources').length,1);});
test('post-insert drift is retained as a failed verification, not silent success',async()=>{const f=fixture({delegateHook:({kind,state,calls})=>{if(kind==='entities'&&calls.some(c=>c.kind==='insertSources'))state.entities[0].name='concurrent change';}});await assert.rejects(f.run('apply'),/state_drift:entities/);assert.equal(f.posts,1);});
test('returned SQL timestamp uses equal instant, not spelling; different instant is rejected',()=>{const wanted=h.descriptor('insertSources',bundle,0,new Date(T0).toISOString()).body,rows=wanted.map(x=>({...x,last_synced_at:x.last_synced_at.replace('Z','+00:00'),created_at:new Date(T0).toISOString()}));h.verifyInserted(rows,wanted);rows[0].last_synced_at=new Date(T0+1).toISOString();assert.throws(()=>h.verifyInserted(rows,wanted),/synced_timestamp/);});
test('returned nonrequested field or changed metadata is refused',()=>{const w=h.descriptor('insertSources',bundle,0,new Date(T0).toISOString()).body,r=w.map(x=>({...x,created_at:new Date(T0).toISOString()}));r[0].other='x';assert.throws(()=>h.verifyInserted(r,w),/insert_schema/);delete r[0].other;r[0].raw_data={};assert.throws(()=>h.verifyInserted(r,w),/insert_representation/);});
for(const age of [-1,h.TTL,h.TTL+1])test('preview age '+age+' blocks before requests',async()=>{const f=fixture();f.setPreview(preview(bundle,T0-age));await assert.rejects(f.run('apply'),/preview_expired/);assert.equal(f.calls.length,0);});
test('preview expiring during fresh reads blocks the sole POST',async()=>{const f=fixture();f.setPreview(preview(bundle,T0-h.TTL+1000));await assert.rejects(f.run('apply'),/preview_expired/);assert.equal(f.posts,0);});
test('preview expiry during post cooldown is rechecked at actual dispatch',async()=>{const f=fixture();f.setPreview(preview(bundle,T0-h.TTL+7200));await assert.rejects(f.run('apply'),/preview_expired/);assert.equal(f.posts,0);});
test('missing confirmed uniqueness gate blocks apply before network',async()=>{const f=fixture(),p=preview();p.constraints_confirmed=false;f.setPreview(p);await assert.rejects(f.run('apply'),/preview_identity/);assert.equal(f.calls.length,0);});
test('preview cannot write even with literal valid insert descriptor',async()=>{const f=fixture({allowWrites:false});await assert.rejects(f.client.request('insertSources',0,new Date(T0).toISOString()),/write_denied/);assert.equal(f.calls.length,0);});
test('same-origin changed response URL is refused',async()=>{const f=fixture({delegateHook:({url})=>response(url,[],200,0,{url:h.ORIGIN+'/rest/v1/entities?select=id'})});await assert.rejects(f.run('preview'),/exact_response_url/);assert.equal(f.calls.length,1);});
test('redirected response is refused',async()=>{const f=fixture({delegateHook:({url})=>response(url,[],200,0,{redirected:true})});await assert.rejects(f.run('preview'),/exact_response_url/);});
test('wrong content range/total cannot assert complete data',async()=>{const f=fixture({delegateHook:({url})=>response(url,[],200,0,{headers:{'Content-Range':'*/1000'}})});await assert.rejects(f.run('preview'),/reported_total_incomplete/);});
test('body limit is enforced before parsing',async()=>{const f=fixture({delegateHook:({url})=>response(url,' '.repeat(h.MAX_BODY+1))});await assert.rejects(f.run('preview'),/body_bound/);});
test('body timeout includes reads and ends without another request',async()=>{let aborted=false;const f=fixture({delegateHook:({url,init})=>new Promise((resolve,reject)=>{init.signal.addEventListener('abort',()=>{aborted=true;reject(Error('aborted'));},{once:true});})});const c=h.createClient({bundle,key:'fake',timeoutMs:5,delegate:async(url,init)=>new Promise((resolve,reject)=>init.signal.addEventListener('abort',()=>{aborted=true;reject(Error('aborted'));},{once:true}))});await assert.rejects(c.request('entities'),/aborted/);assert(aborted);await assert.rejects(c.request('entities'),/transport_stopped/);});
test('workflow deadline after a response prevents success and further dispatch',async()=>{const f=fixture({delegateHook:({advance})=>{advance(h.MAX_MS);}});await assert.rejects(f.run('preview'),/response_deadline/);assert.equal(f.calls.length,1);});
test('durable POST-intent failure sends no POST',async()=>{const f=fixture({eventHook:e=>{if(e.event==='post_intent_no_retry')throw Error('disk full');}});await assert.rejects(f.run('apply'),/disk full/);assert.equal(f.posts,0);assert.equal(f.calls.filter(c=>c.kind==='insertSources').length,0);});
test('plan hash mismatch fails offline before loading or requesting anything',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'five-source-pin-'));try{fs.writeFileSync(path.join(dir,h.PLAN),'{}');assert.throws(()=>h.loadBundle(dir),/plan_hash/);}finally{fs.rmSync(dir,{recursive:true});}});
test('independent audit must bind exact helper and plan hashes',()=>{const r={status:'PASS',independent:true,helper_sha256:h.helperSha(),plan_sha256:h.PLAN_SHA};h.validateReview(r);assert.throws(()=>h.validateReview({...r,helper_sha256:'0'.repeat(64)}),/independent_review/);});
test('read-only default and exact CLI reject unsafe or resume arguments',()=>{for(const a of [['--read'],['--apply'],['--resume'],['--apply','x','0'.repeat(64),'--review-sha','1'.repeat(64),'wrong']])assert.throws(()=>h.cli(a),/invalid_cli/);assert.equal(h.cli(['--preview','--review-sha','0'.repeat(64),'--confirmed-source-unique-constraints']).constraintsConfirmed,true);});
test('exclusive immutable output and journal retain precise scope without credentials',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'five-source-journal-'));try{h.save(path.join(dir,'reservation.json'),{scope:'source-only'});assert.throws(()=>h.save(path.join(dir,'reservation.json'),{}),/EEXIST/);let checks=0;const j=h.journal(path.join(dir,'events.ndjson'),()=>checks++);j.append({event:'post_intent_no_retry',rows:5});j.close();assert.equal(checks,1);assert.equal(JSON.parse(fs.readFileSync(path.join(dir,'events.ndjson'),'utf8')).rows,5);}finally{fs.rmSync(dir,{recursive:true});}});
