'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),h=require('./apply-blommers-two-prices.cjs'),bundle=h.loadBundle(),clone=x=>JSON.parse(JSON.stringify(x));
function initial(){return{owner:[{...bundle.owner,metadata:{preserve:true}}],parent:[clone(bundle.product)],variants:clone(bundle.variants),roles:[{entity_id:h.OWNER,role:'roaster',metadata:{keep:true}}],sources:[],canonicalOut:[],canonicalIn:[],activeClaims:[]};}
function response(url,rows,status=200,offset=0){const r=new Response(JSON.stringify(rows),{status,headers:{'content-type':'application/json','content-range':Array.isArray(rows)&&rows.length?`${offset}-${offset+rows.length-1}/*`:'*/*'}});Object.defineProperty(r,'url',{value:url});return r;}
function fixture(state=initial(),hook){let clock=Date.parse(bundle.baseline_at)+60000;const calls=[],events=[];const delegate=async(url,req)=>{const u=new URL(url),q=u.searchParams,table=u.pathname.split('/').pop(),offset=Number(q.get('offset')||0);calls.push({url,method:req.method,body:req.body&&JSON.parse(req.body)});clock+=50;if(hook){const v=await hook({url,req,state,calls,offset});if(v)return v;}
 const kind={entities:'owner',products:'parent',product_variants:'variants',entity_roles:'roles',entity_source_ids:'sources',crawl_runs:'activeClaims'}[table],rows=table==='entity_attributes'?(q.has('attribute_value')?state.canonicalIn:state.canonicalOut):state[kind];assert(rows,'unexpected table');const matches=r=>[...q].filter(([k])=>!['select','order','limit','offset'].includes(k)).every(([k,v])=>v==='is.null'?r[k]===null:v.startsWith('eq.')&&String(r[k])===v.slice(3));let selected=rows.filter(matches);
 if(req.method==='PATCH'){if(selected.length===1)Object.assign(selected[0],JSON.parse(req.body),{updated_at:new Date(clock).toISOString()});return response(url,clone(selected));}assert.equal(req.method,'GET');const keys=(q.get('order')||'').split(',').filter(Boolean);selected.sort((a,b)=>{for(const p of keys){const k=p.split('.')[0],x=String(a[k]).localeCompare(String(b[k]));if(x)return x;}return 0;});return response(url,clone(selected.slice(offset,offset+Number(q.get('limit')))),200,offset);
 };return{state,calls,events,now:()=>clock,advance:n=>clock+=n,client(mode='preview',extra={}){return h.createClient({bundle,key:'offline-fixture',mode,delegate,event:e=>events.push(e),now:()=>clock,wait:async n=>clock+=n,...extra});}};}
async function preview(f){return h.execute({client:f.client(),bundle,now:f.now});}
async function apply(f,p,extra={}){return h.execute({client:f.client('apply',{validateWrite:()=>h.validatePreview(p,bundle,f.now())}),bundle,mode:'apply',preview:p,now:f.now,...extra});}
test('frozen plan, raw source fragments and exact two prices load',()=>{assert.equal(bundle.actions.length,2);assert.deepEqual(bundle.actions.map(a=>a.patch),[{price_cents:2895},{price_cents:8995}]);assert.deepEqual(bundle.variants.map(v=>v.weight_g),[250,1000]);});
test('default is offline check and apply needs exact confirmation',()=>{assert.equal(h.cli([]).mode,'check');assert.equal(h.cli(['--preview']).mode,'preview');for(const a of [['--run'],['--apply'],['--apply','p','a'.repeat(64),'--yes']])assert.throws(()=>h.cli(a));});
test('preview10 GETs no mutation',async()=>{const f=fixture(),p=await preview(f);assert.equal(p.requests,10);assert.equal(p.writes,0);assert(f.calls.every(c=>c.method==='GET'));});
test('apply30 requests exactly two prices; parents weights stock and all unrelated fields preserved',async()=>{const f=fixture(),p=await preview(f),before=clone(f.state);f.calls.length=0;const r=await apply(f,p);assert.equal(r.requests,30);assert.equal(r.writes,2);assert.equal(f.calls.filter(c=>c.method==='PATCH').length,2);assert.deepEqual(r.after.parent,before.parent);for(let i=0;i<2;i++){const old=before.variants[i],actual=r.after.variants[i],want={...old,price_cents:bundle.actions[i].patch.price_cents,updated_at:actual.updated_at};assert.deepEqual(actual,want);}assert.equal(r.full_inventory_complete,false);});
test('nonempty exact-owner sources preserved with32 total apply requests',async()=>{const s=initial();s.sources=[{id:'00000000-0000-4000-8000-000000000001',entity_id:h.OWNER,source:'some_source',source_id:'fixed',raw_data:{keep:true}}];const f=fixture(s),p=await preview(f);assert.equal(p.requests,11);const r=await apply(f,p);assert.equal(r.requests,32);assert.deepEqual(r.after.sources,s.sources);});
for(const[label,edit]of [['owner name',s=>s.owner[0].name='wrong'],['owner host',s=>s.owner[0].website_url='https://wrong.example'],['roaster missing',s=>s.roles=[]],['canonical outgoing',s=>s.canonicalOut=[{entity_id:h.OWNER,attribute_key:'canonical_roaster_entity_id',attribute_value:'x'}]],['canonical incoming',s=>s.canonicalIn=[{entity_id:'x',attribute_key:'canonical_roaster_entity_id',attribute_value:h.OWNER}]],['running claim',s=>s.activeClaims=[{id:'x',entity_id:h.OWNER,status:'running'}]],['parent version',s=>s.parent[0].updated_at='2026-09-27T17:00:00Z'],['parent source',s=>s.parent[0].source_url='https://wrong.example'],['first price already changed',s=>s.variants[0].price_cents=2895],['sibling changed',s=>s.variants[1].price_cents=8995],['weight changed',s=>s.variants[0].weight_g=500],['stock changed',s=>s.variants[0].availability='out_of_stock'],['additional sibling',s=>s.variants.push({...s.variants[0],id:'extra'})]])test('preview holds '+label,async()=>{const s=initial();edit(s);const f=fixture(s);await assert.rejects(preview(f));assert(!f.calls.some(c=>c.method==='PATCH'));});
test('both CAS descriptors include every captured scalar field and only price payload',()=>{const s=initial();for(let i=0;i<2;i++){const d=h.descriptor('mutation',bundle,0,i,s),q=new URL(d.url).searchParams;assert.equal(new URL(d.url).pathname,'/rest/v1/product_variants');assert.deepEqual(d.body,bundle.actions[i].patch);for(const[k,v]of Object.entries(bundle.variants[i]))assert.equal(q.get(k),v===null?'is.null':'eq.'+v);}});
test('no altered scope payload or third action is admitted',()=>{for(const mutate of [b=>b.actions[0].patch.weight_g=500,b=>b.actions[0].patch.price_cents=1,b=>b.actions[0].table='products',b=>b.actions[0].id=b.actions[1].id]){const b=clone(bundle);mutate(b);assert.throws(()=>h.descriptor('mutation',b,0,0,initial()));}assert.throws(()=>h.descriptor('mutation',bundle,0,2,initial()));});
test('preview expired/future/helper mismatch refuses before DB',async()=>{const f=fixture(),p=await preview(f);for(const q of [{...p,at:'2000-01-01T00:00:00Z'},{...p,at:'2100-01-01T00:00:00Z'},{...p,helper_sha256:'x'}]){const c=f.client('apply');await assert.rejects(h.execute({client:c,bundle,mode:'apply',preview:q,now:f.now}));assert.equal(c.requests,0);}});
test('new owner metadata drift between preview and apply stops before writes',async()=>{const f=fixture(),p=await preview(f);f.state.owner[0].metadata.keep='changed';await assert.rejects(apply(f,p));assert(!f.calls.some(c=>c.method==='PATCH'));});
test('new claim after full preflight stops before first mutation',async()=>{const f=fixture(),p=await preview(f);await assert.rejects(apply(f,p,{append:e=>{if(e.event==='all_preconditions_pass')f.state.activeClaims.push({id:'new',entity_id:h.OWNER,status:'running'});}}));assert(!f.calls.some(c=>c.method==='PATCH'));});
test('owner drift before critical reads stops without mutation',async()=>{const f=fixture(),p=await preview(f);await assert.rejects(apply(f,p,{append:e=>{if(e.event==='all_preconditions_pass')f.state.owner[0].metadata.changed=true;}}));assert(!f.calls.some(c=>c.method==='PATCH'));});
test('second-row drift after first commit stops without retry or second PATCH',async()=>{const f=fixture(),p=await preview(f);await assert.rejects(apply(f,p,{append:e=>{if(e.event==='mutation_returned_preserved'&&e.index===0)f.state.variants[1].availability='unknown';}}));assert.equal(f.calls.filter(c=>c.method==='PATCH').length,1);assert.equal(f.state.variants[0].price_cents,2895);});
test('returned weight change or zero/multi representations fail',()=>{const a=bundle.actions[0],b=bundle.variants[0];assert.throws(()=>h.afterRow([{...b,...a.patch,weight_g:500}],b,a),/preservation/);assert.throws(()=>h.afterRow([],b,a));assert.throws(()=>h.afterRow([b,b],b,a));});
test('SQL timestamp format-equivalence remains accepted without losing microsecond changes',()=>{const a=bundle.actions[0],b=bundle.variants[0],r={...b,...a.patch,created_at:b.created_at.replace('+00:00','Z')};assert.doesNotThrow(()=>h.afterRow([r],b,a));assert.throws(()=>h.afterRow([{...r,created_at:'2026-08-11T02:29:49.276453Z'}],b,a),/created_at/);});
test('ambiguous PATCH stops gate and cannot replay',async()=>{const f=fixture(initial(),({url,req})=>req.method==='PATCH'?response(url,{code:'57014'},500):null),c=f.client('apply');await assert.rejects(c.request('mutation',0,0,f.state));await assert.rejects(c.request('mutation',0,0,f.state));assert.equal(f.calls.length,1);});
test('preview never admits PATCH',async()=>{const f=fixture(),c=f.client();await assert.rejects(c.request('mutation',0,0,f.state));assert.equal(f.calls.length,0);});
for(const[label,respond]of [['changed URL',u=>response(u+'x',[])],['empty URL',()=>new Response('[]')],['content type',u=>{const r=response(u,[]);r.headers.set('content-type','text/html');return r;}],['content range',u=>{const r=response(u,[]);r.headers.set('content-range','0-0/*');return r;}],['row bound',u=>response(u,Array.from({length:25},()=>({})))],['http error',u=>response(u,{code:'57014'},500)]])test('transport stops '+label,async()=>{const f=fixture(initial(),({url})=>respond(url)),c=f.client();await assert.rejects(c.request('owner'));await assert.rejects(c.request('owner'));assert.equal(f.calls.length,1);});
test('nonempty continuation refuses hidden rows',async()=>{const f=fixture(initial(),({url,offset})=>offset?response(url,[{}],200,offset):null);await assert.rejects(preview(f),/nonempty_eof/);});
test('strict500ms completion interval despite early timer wake',async()=>{let clock=0,last=0,n=0;const waits=[];const c=h.createClient({bundle,key:'x',now:()=>clock,wait:async ms=>{waits.push(ms);clock+=ms===500?499:ms;},delegate:async u=>{if(n++)assert(clock-last>=500);clock+=1000;last=clock;return response(u,[]);}});await c.request('activeClaims');await c.request('activeClaims');assert.deepEqual(waits,[500,1]);});
test('deadline and write TTL are checked after pacing before dispatch',async()=>{let clock=0,n=0;const c=h.createClient({bundle,key:'x',now:()=>clock,wait:async()=>clock=300001,delegate:async u=>{n++;return response(u,[]);}});await c.request('activeClaims');await assert.rejects(c.request('activeClaims'));assert.equal(n,1);const f=fixture(),d=f.client('apply',{validateWrite:()=>{throw Error('expired');}});await assert.rejects(d.request('mutation',0,0,f.state));assert.equal(f.calls.length,0);});
test('journal failure prevents actual mutation',async()=>{const f=fixture(),c=f.client('apply',{event:()=>{throw Error('disk failure');}});await assert.rejects(c.request('mutation',0,0,f.state));assert.equal(f.calls.length,0);});
