'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const h=require('./apply-cafe-source-links.cjs'),plan=h.loadPlan(),clone=structuredClone;
function fixture(){let time=100000;const data={entities:plan.actions.map(a=>({...clone(a.before.entity),updated_at:'2026-09-27T00:00:00Z'})),entity_locations:plan.actions.flatMap(a=>clone(a.before.locations)),entity_roles:plan.actions.flatMap(a=>a.before.roles.map(r=>({...clone(r),role_metadata:{existing:true}}))),entity_source_ids:plan.actions.flatMap(a=>a.before.sources.map(r=>({...clone(r),raw_data:{existing:true}}))),entity_attributes:[]},calls=[],events=[];let fault=null;
 const delegate=async(url,init)=>{const u=new URL(url),table=u.pathname.split('/').at(-1),offset=Number(u.searchParams.get('offset')||0),method=init.method;calls.push({url,method,body:init.body&&JSON.parse(init.body)});if(fault){const response=await fault({u,table,offset,method,calls,data});if(response)return response;}
  let rows;if(method==='POST'){rows=JSON.parse(init.body).map(x=>({...x,created_at:'2026-09-27T09:50:00Z'}));data[table].push(...clone(rows));}else{rows=clone(data[table]);if(table==='entity_source_ids'&&u.searchParams.has('source_id'))rows=rows.filter(r=>r.source==='my_coffee_explorer'&&plan.actions.some(a=>a.source_id===r.source_id));if(table==='entity_attributes'){rows=rows.filter(r=>r.attribute_key==='canonical_roaster_entity_id'&&plan.actions.some(a=>a.entity_id===r[u.searchParams.has('entity_id')?'entity_id':'attribute_value']));}rows=rows.slice(offset,offset+Number(u.searchParams.get('limit')));}
  return new Response(JSON.stringify(rows),{status:method==='POST'?201:200,headers:{'content-type':'application/json','content-range':rows.length?offset+'-'+(offset+rows.length-1)+'/*':'*/*'}});};
 const client=(writes=false)=>h.createClient({plan,key:'offline-not-a-key',allowWrites:writes,delegate,event:e=>events.push(e),now:()=>time,wait:async ms=>{time+=ms;}});
 return{data,calls,events,client,setFault:f=>fault=f,posts:()=>calls.filter(x=>x.method==='POST')};
}
async function preview(f,confirmed=true){return h.execute({client:f.client(),plan,mode:'preview',constraintsConfirmed:confirmed});}
async function apply(f,p){return h.execute({client:f.client(true),plan,mode:'apply',preview:p});}
test('offline frozen plan is exactly ten sources plus four cafe roles with unchanged raw provenance',()=>{assert.equal(plan.actions.length,10);assert.equal(plan.actions.filter(x=>x.role_insert).length,4);for(const a of plan.actions){assert.equal(a.source_insert.raw_data.kind,'shop');assert.equal(a.source_insert.raw_data.sourceUrl,a.source_insert.source_url);assert.equal(a.role_insert?.role||'cafe','cafe');}assert.equal(plan.summary.new_entities,0);});
test('preview has ten sequential bounded GETs and no writes',async()=>{const f=fixture(),p=await preview(f);assert.equal(p.requests,10);assert.equal(f.calls.length,10);assert.equal(f.posts().length,0);assert.equal(p.status,'preview_complete');});
test('apply has ten fresh reads then two exact plain bulk POSTs and ten readback GETs',async()=>{const f=fixture(),p=await preview(f);f.calls.length=0;const r=await apply(f,p);assert.equal(r.status,'complete');assert.equal(r.requests,22);assert.equal(f.calls.length,22);assert.deepEqual(f.calls.slice(10,12).map(x=>[x.method,new URL(x.url).pathname,x.body.length]),[['POST','/rest/v1/entity_source_ids',10],['POST','/rest/v1/entity_roles',4]]);assert(f.calls.slice(0,10).every(x=>x.method==='GET'));assert(f.calls.slice(12).every(x=>x.method==='GET'));assert.equal(r.after.entities.length,10);});
test('preview without constraint confirmation cannot authorize apply',async()=>{const f=fixture(),p=await preview(f,false);await assert.rejects(apply(f,p),/constraints/);assert.equal(f.posts().length,0);});
for(const [name,mutate]of[
 ['renamed target',d=>d.entities[0].name='Other'],['changed website',d=>d.entities[0].website_url='https://other.example'],['changed address',d=>d.entity_locations[0].address1='1 Other St'],['missing target',d=>d.entities.shift()],['existing roaster role',d=>d.entity_roles.push({entity_id:plan.actions[1].entity_id,role:'roaster'})],['source key on foreign owner',d=>d.entity_source_ids.push({...plan.actions[0].source_insert,entity_id:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'})],['source key already on same owner',d=>d.entity_source_ids.push(clone(plan.actions[0].source_insert))],['outgoing canonical alias',d=>d.entity_attributes.push({entity_id:plan.actions[0].entity_id,attribute_key:'canonical_roaster_entity_id',attribute_value:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'})],['incoming canonical alias',d=>d.entity_attributes.push({entity_id:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',attribute_key:'canonical_roaster_entity_id',attribute_value:plan.actions[0].entity_id})],['missing existing source',d=>d.entity_source_ids.shift()]
])test('preflight refuses '+name,async()=>{const f=fixture();mutate(f.data);await assert.rejects(preview(f));assert.equal(f.posts().length,0);});
test('fresh role metadata or unrelated parent field change after preview refuses all writes',async()=>{for(const fn of[d=>d.entity_roles[0].role_metadata.changed=true,d=>d.entities[0].updated_at='2026-09-27T10:00:00Z']){const f=fixture(),p=await preview(f);fn(f.data);await assert.rejects(apply(f,p),/fresh_context/);assert.equal(f.posts().length,0);}});
test('nonempty continuation refuses truncated roles even when first page equals baseline',async()=>{const f=fixture();f.setFault(({table,offset})=>table==='entity_roles'&&offset?new Response(JSON.stringify([{entity_id:plan.actions[0].entity_id,role:'roaster'}]),{headers:{'content-type':'application/json','content-range':offset+'-'+offset+'/*'}}):null);await assert.rejects(preview(f),/nonempty_continuation/);});
test('first HTTP failure latches transport, no automatic retry or later read',async()=>{const f=fixture();f.setFault(()=>new Response(JSON.stringify({code:'57014'}),{status:500,headers:{'content-type':'application/json'}}));const c=f.client();await assert.rejects(h.execute({client:c,plan}),/database_http/);await assert.rejects(c.request('entities'),/transport_stopped/);assert.equal(f.calls.length,1);});
test('source POST ambiguous timeout stops before roles and cannot retry',async()=>{const f=fixture(),p=await preview(f);f.calls.length=0;f.setFault(({method})=>{if(method==='POST')throw Object.assign(Error('request_timeout'),{code:'request_timeout'});});await assert.rejects(apply(f,p),/request_timeout/);assert.equal(f.posts().length,1);assert.equal(f.calls.length,11);});
test('role POST failure preserves source result and stops without rollback/retry',async()=>{const f=fixture(),p=await preview(f);f.calls.length=0;f.setFault(({method,table})=>method==='POST'&&table==='entity_roles'?new Response(JSON.stringify({code:'23505'}),{status:409,headers:{'content-type':'application/json'}}):null);await assert.rejects(apply(f,p),/database_http/);assert.equal(f.posts().length,2);assert.equal(f.data.entity_source_ids.length,21);assert.equal(f.data.entity_roles.length,6);});
test('POST representation must contain all ten exact requested rows',async()=>{const f=fixture(),p=await preview(f);f.setFault(({method,table})=>method==='POST'&&table==='entity_source_ids'?new Response(JSON.stringify([plan.actions[0].source_insert]),{status:201,headers:{'content-type':'application/json'}}):null);await assert.rejects(apply(f,p),/row_count/);assert.equal(f.posts().length,1);});
test('changed returned raw source or role metadata is refused',()=>{for(const spec of [plan.actions.map(a=>a.source_insert),plan.actions.flatMap(a=>a.role_insert?[a.role_insert]:[])]){const rows=clone(spec);if(rows[0].raw_data)rows[0].raw_data.name='Changed';else rows[0].role_metadata={};assert.throws(()=>h.validateInserted(rows,spec,'test'),/changed/);}});
test('post-write parent drift or new canonical alias is reported, never overwritten',async()=>{for(const mutate of[d=>d.entities[0].name='Changed',d=>d.entity_attributes.push({entity_id:plan.actions[0].entity_id,attribute_key:'canonical_roaster_entity_id',attribute_value:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'})]){const f=fixture(),p=await preview(f);let changed=false;f.setFault(({method,table,data})=>{if(!changed&&method==='GET'&&table==='entities'&&f.posts().length===2){changed=true;mutate(data);}});await assert.rejects(apply(f,p));assert.equal(f.posts().length,2);}});
test('wrong JSON type, malformed range, redirects and overfull response fail closed',async()=>{for(const response of [()=>new Response('[]',{headers:{'content-type':'text/html','content-range':'*/*'}}),()=>new Response('[]',{headers:{'content-type':'application/json'}}),()=>({redirected:true}),()=>new Response(JSON.stringify(Array(100).fill({})),{headers:{'content-type':'application/json','content-range':'0-99/*'}})]){const f=fixture();f.setFault(response);await assert.rejects(preview(f));assert.equal(f.posts().length,0);}});
test('read-only client and unknown request kinds cannot mutate',async()=>{const f=fixture();await assert.rejects(f.client().request('insertSources'),/preview_write/);await assert.rejects(f.client().request('patchEntities'),/out_of_scope/);assert.equal(f.calls.length,0);});
test('exact descriptors have fixed origin, no upsert/update/delete/RPC and no foreign IDs',()=>{for(const kind of ['entities','locations','roles','ownerSources','sourceKeys','canonicalOut','canonicalIn','insertSources','insertRoles']){const d=h.descriptor(kind,plan),u=new URL(d.url);assert.equal(u.origin,h.ORIGIN);assert(!u.searchParams.has('on_conflict'));assert(['GET','POST'].includes(d.method));assert(u.pathname.startsWith('/rest/v1/'));}assert.throws(()=>h.descriptor('roles',plan,100),/offset/);});
test('CLI defaults offline and apply requires exact explicit confirmation',()=>{assert.equal(h.cli([]).mode,'check');assert.equal(h.cli(['--preview']).constraintsConfirmed,false);assert.throws(()=>h.cli(['--apply','x','0'.repeat(64),'yes']));});
test('stale, unconfirmed, wrong-plan and wrong-helper previews are rejected',async()=>{const f=fixture(),p=await preview(f);for(const patch of [{at:new Date(Date.now()-900001).toISOString()},{at:new Date(Date.now()+10000).toISOString()},{plan_sha256:'x'},{helper_sha256:'x'},{constraints_confirmed:false}])assert.throws(()=>h.validatePreview({...p,...patch},plan));});
test('journal/lock failure before first POST prevents all writes',async()=>{const f=fixture(),p=await preview(f);await assert.rejects(h.execute({client:f.client(true),plan,mode:'apply',preview:p,append:e=>{if(e.event==='write_attempt_no_retry')throw Error('journal failure');}}),/journal/);assert.equal(f.posts().length,0);});
test('shared lock refuses existing file and releases only its own inode and token',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cafe-link-test-')),file=path.join(dir,'apply.lock'),a=h.acquireLock(file);assert.throws(()=>h.acquireLock(file),/EEXIST/);a.check();a.release();assert(!fs.existsSync(file));fs.rmdirSync(dir);});
test('slow response plus body/audit processing is followed by a full 500ms cooldown',async()=>{let time=100000;const starts=[],waits=[];const c=h.createClient({plan,key:'offline',now:()=>time,wait:async ms=>{waits.push(ms);time+=ms;},event:e=>{if(e.event==='request_result')time+=70;},delegate:async()=>{starts.push(time);time+=1200;return new Response('[]',{headers:{'content-type':'application/json','content-range':'*/*'}});}});await c.request('entities');await c.request('roles');assert.deepEqual(waits,[500]);assert.equal(starts[1]-starts[0],1200+70+500);});
