'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),h=require('./capture-blommers-exact-product.cjs');
const parent={id:h.PRODUCT,entity_id:'11111111-1111-4111-8111-111111111111',source_url:'https://www.blommers.coffee/nl/microlot-espresso-proefpakket-2x-250-gram.html'},variant={id:'22222222-2222-4222-8222-222222222222',product_id:h.PRODUCT,variant_name:'2x 250 Gram',price_cents:289500,currency:'EUR',weight_g:500};
function fixture({products=[parent],variants=[variant],badEOF=false,responseURL,failStatus,early=false}={}){let time=0,done=null;const calls=[],gaps=[],event=[];const r=h.reader({key:'fixture',now:()=>time,wait:async ms=>{time+=early&&ms>1?ms-1:ms;},event:e=>event.push(e),delegate:async(req)=>{if(done!==null)gaps.push(time-done);const u=new URL(req.url),offset=Number(u.searchParams.get('offset')||0),rows=offset?(badEOF?[variant]:[]):u.pathname.endsWith('/products')?products:variants;calls.push({method:req.method,url:req.url});time+=50;done=time;const response=new Response(JSON.stringify(rows),{status:failStatus||200,headers:{'content-type':'application/json','content-range':rows.length?offset+'-'+(offset+rows.length-1)+'/*':'*/*'}});Object.defineProperty(response,'url',{value:responseURL===undefined?req.url:responseURL});return response;}});return{r,calls,gaps,event};}
test('all frozen evidence pins pass offline',()=>assert.equal(h.check().products[0].id,h.PRODUCT));
test('exact product and variants only,4GET with explicit empty continuations',async()=>{const f=fixture(),r=await h.capture(f.r);assert.equal(r.requests,4);assert.equal(r.writes,0);assert.deepEqual(r.variants,[variant]);for(const c of f.calls){const u=new URL(c.url);assert.equal(c.method,'GET');assert.equal(u.origin,h.ORIGIN);assert.equal(u.searchParams.get(u.pathname.endsWith('/products')?'id':'product_id'),'in.('+h.PRODUCT+')');}assert(f.gaps.every(x=>x>=500));});
test('zero variants are reported literally, no incomplete filter',async()=>{const f=fixture({variants:[]}),r=await h.capture(f.r);assert.equal(r.requests,3);assert.deepEqual(r.variants,[]);});
test('missing product stops before children',async()=>{const f=fixture({products:[]});await assert.rejects(h.capture(f.r),/exact_product/);assert.equal(f.calls.length,1);});
test('foreign product source stops',async()=>{const f=fixture({products:[{...parent,source_url:'https://example.com/item'}]});await assert.rejects(h.capture(f.r),/product_source/);assert.equal(f.calls.length,1);});
test('unrelated query/path/credentials are not accepted as merchant identity',()=>{for(const url of ['https://www.blommers.coffee/nl/other.html','https://user@www.blommers.coffee/nl/microlot-espresso-proefpakket-2x-250-gram.html','https://www.blommers.coffee/nl/microlot-espresso-proefpakket-2x-250-gram.html?other=1'])assert.throws(()=>h.validProduct({...parent,source_url:url}));});
test('foreign or duplicate variants stop',async()=>{for(const variants of [[{...variant,product_id:parent.entity_id}],[variant,variant]]){const f=fixture({variants});await assert.rejects(h.capture(f.r),/variant_identity/);assert.equal(f.calls.length,3);}});
test('nonempty EOF fails closed',async()=>{const f=fixture({badEOF:true});await assert.rejects(h.capture(f.r),/product_nonempty_eof/);assert.equal(f.calls.length,2);});
test('changed response URL hard-stops before followup',async()=>{const f=fixture({responseURL:h.ORIGIN+'/rest/v1/products?wrong=1'});await assert.rejects(h.capture(f.r),/exact_response_url/);await assert.rejects(f.r.request('variants'));assert.equal(f.calls.length,1);});
test('HTTP500 has no retry',async()=>{const f=fixture({failStatus:500});await assert.rejects(h.capture(f.r));await assert.rejects(f.r.request('products'));assert.equal(f.calls.length,1);});
test('early wake never dispatches inside500ms',async()=>{const f=fixture({early:true});await h.capture(f.r);assert(f.gaps.every(x=>x>=500));});
test('no arbitrary read groups/mutations or fifth request',async()=>{const f=fixture();await assert.rejects(f.r.request('facts'));assert.equal(f.calls.length,0);const g=fixture();await h.capture(g.r);await assert.rejects(g.r.request('variants'));assert.equal(g.calls.length,4);});
