'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
require('./prepare-lulo-followup.cjs').offlineOnly();
const h=require('./collect-eleventh-identity-followup.cjs'),{createTransport}=require('./product-only-network.cjs'),{installQuerylessGuard}=require('./plan8-product-link-discovery.cjs'),{latchedEvents}=require('./collect-tenth-sites.cjs');
const m=h.loadManifest(),read=f=>fs.readFileSync(path.join(__dirname,f)),clone=()=>structuredClone(m);
const htmlResponse=(text='<title>About the roastery</title><p>We roast our coffee here.</p>')=>({status:200,contentType:'text/html',body:Buffer.from(text)});
function factory(send,resolver=async()=>[{address:'1.1.1.1',family:4}]){return opts=>createTransport({...opts,resolver,send,sleep:async()=>{}});}
test('frozen manifest contains exact3 new identity pages for3 held owners, no DB authority',()=>{assert.equal(m.targets.length,3);assert.equal(new Set(m.targets.map(t=>t.input_index)).size,3);assert(m.targets.every(t=>t.fetched===false&&t.identityVerified===false));assert.equal(m.staleCatalog,true);assert.equal(m.databasePlanningAllowed,false);assert.equal(m.databaseMutationAllowed,false);assert.equal(m.requiresFreshCatalogBeforeAnyDatabasePlanOrApply,true);assert.deepEqual(m.targets.map(t=>t.url),h.EXPECTED.map(t=>t.url));assert.equal(h.sha(read(h.MANIFEST_FILE)),h.MANIFEST_SHA256);});
test('all original helper hashes remain unchanged',()=>{for(const[f,pin]of Object.entries(h.HELPER_PINS))assert.equal(h.sha(read(f)),pin,f);});
test('default transport cannot run through exported fixture function without private CLI context',async()=>{await assert.rejects(h.collectPages(m),/explicit_verified_run_required/);});
test('source input/cache/review/anchor receipts are hash bound before any transport',()=>{const bad=clone();bad.inputHashes['eleventh-reviewed-site-input.json']='0'.repeat(64);assert.throws(()=>h.validateManifest(bad,read),/Pinned evidence changed/);});
for(const field of ['url','raw_href','anchor_sha256','source_raw_html_sha256','source_static_text_sha256','source_cache_key'])test('tampered target field refuses '+field,()=>{const bad=clone();bad.targets[0][field]+='tampered';assert.throws(()=>h.validateManifest(bad,read));});
test('exact UTF16 range and original receipt pointers cannot be rebound',()=>{for(const mutate of [t=>t.raw_html_utf16_range[0]++,t=>t.raw_href_html_utf16_range[0]++,t=>t.source_page_index++,t=>t.input_index=4,t=>t.source_cache_line++]){const bad=clone();mutate(bad.targets[0]);assert.throws(()=>h.validateManifest(bad,read));}});
test('URL count and unique scope cannot expand',()=>{const bad=clone();bad.targets.push(...bad.targets.slice(0,2));assert.throws(()=>h.validateManifest(bad,read));const duplicate=clone();duplicate.targets[1]=duplicate.targets[0];assert.throws(()=>h.validateManifest(duplicate,read));});
test('query/legal/auth/HTTP/foreign/private/fragment initial URLs are refused',()=>{for(const u of ['https://sastostadores.com/terms','https://sastostadores.com/%2574erms','https://sastostadores.com/quienes-somos/?action=add','https://sastostadores.com/account','http://sastostadores.com/quienes-somos/','https://elsewhere.example/quienes-somos/','https://127.0.0.1/','https://sastostadores.com/quienes-somos/#section'])assert.throws(()=>h.strictUrl(u,'https://sastostadores.com/'));});
test('three exact requests execute sequentially,20sec1MiB, no discovered links or image/JSON calls',async()=>{let active=0,maximum=0;const requests=[];const out=await h.collectPages(m,{transportFactory:factory(async(u,_address,opts)=>{active++;maximum=Math.max(maximum,active);requests.push(u.href);assert.equal(opts.kind,'html');assert.equal(opts.timeoutMs,20000);assert.equal(opts.maxBytes,1048576);await new Promise(r=>setImmediate(r));active--;return htmlResponse('<title>About</title><p>Our roastery</p><a href="/extra">About more</a><img src="/photo.jpg">');})});assert.deepEqual(requests,m.targets.map(t=>t.url));assert.equal(maximum,1);assert.equal(out.length,3);assert(out.every(p=>p.fetched&&p.captureComplete&&p.rawHtml&&p.staticBodyText));});
test('full text beyond200k and rawHTML remain exact and hash-bound',async()=>{const text='<title>Our operation</title><main>'+('coffee '.repeat(35000))+'END_OF_COMPLETE_TEXT</main>',out=await h.collectPages({...m,targets:[m.targets[0]]},{transportFactory:factory(async()=>htmlResponse(text))});assert.equal(out[0].rawHtml,text);assert.equal(out[0].rawHtmlSha256,h.sha(text));assert(out[0].staticBodyTextChars>200000);assert(out[0].staticBodyText.endsWith('END_OF_COMPLETE_TEXT'));assert.equal(out[0].staticBodyTextSha256,h.sha(out[0].staticBodyText));});
for(const status of [401,403,407,429])test('access'+status+' stops remaining owner pages without body retention or retry',async()=>{let calls=0;const targets=[...[m.targets[0],m.targets[0]],m.targets.at(-1)];const out=await h.collectPages({...m,targets},{transportFactory:factory(async()=>{calls++;return calls===1?{status,contentType:'text/html',body:Buffer.from('DO_NOT_CAPTURE')}:htmlResponse();})});assert.equal(calls,2);assert.equal(out[0].status,'failed');assert.equal(out[1].status,'not_requested_prior_owner_stop');assert(!out[0].rawHtml&&!out[1].rawHtml);assert.equal(out[2].fetched,true);});
for(const text of ['<title>Terms &amp; Conditions</title>DO_NOT_CAPTURE','<title>Datenschutz</title>DO_NOT_CAPTURE','<title>Just a moment</title>DO_NOT_CAPTURE','<input type="password">DO_NOT_CAPTURE'])test('legal/challenge response never reaches capture '+text.slice(0,28),async()=>{let calls=0;const out=await h.collectPages({...m,targets:[m.targets[0],m.targets[0]]},{transportFactory:factory(async()=>{calls++;return htmlResponse(text);})});assert.equal(calls,1);assert.equal(out[0].status,'failed');assert(!out[0].rawHtml&&!out[0].staticBodyText);assert.equal(out[1].fetched,false);});
for(const location of ['/terms','/%2574erms','/login','https://foreign.example/quienes-somos/','http://sastostadores.com/quienes-somos/','/different-page'])test('strict transport stops redirect before second dispatch '+location,async()=>{let calls=0;const out=await h.collectPages({...m,targets:[m.targets[0]]},{transportFactory:factory(async()=>{calls++;return{status:302,location,body:Buffer.alloc(0)};})});assert.equal(calls,1);assert.equal(out[0].status,'failed');});
test('native queryless guard blocks same-path action-query redirect despite legacy same-path exception',async()=>{let sends=0;const mockHttp={request(){throw Error('HTTP not allowed');},get(){}},mockHttps={request(){sends++;return{status:302,location:'/quienes-somos/?add-to-cart=1',body:Buffer.alloc(0)};},get(){}},guard=installQuerylessGuard({httpModule:mockHttp,httpsModule:mockHttps});try{const out=await h.collectPages({...m,targets:[m.targets[0]]},{transportFactory:factory(async u=>mockHttps.request(u,{method:'GET'}))});assert.equal(sends,1);assert.equal(out[0].error,'unmanifested_discovery_query');assert.equal(guard.stats.blocked,1);}finally{guard.uninstall();}});
test('mixed public/private or reserved IPv6 DNS fails before any dispatch',async()=>{for(const address of ['127.0.0.1','2002:0a00:0001::1','2001::1']){let sends=0;const out=await h.collectPages({...m,targets:[m.targets[0]]},{transportFactory:factory(async()=>{sends++;return htmlResponse();},async()=>[{address:'1.1.1.1',family:4},{address,family:address.includes(':')?6:4}])});assert.equal(sends,0);assert.equal(out[0].error,'private_or_reserved_dns');}});
test('timeout and size errors stop that owner and never retry',async()=>{for(const code of ['request_timeout','response_too_large']){let calls=0;const out=await h.collectPages({...m,targets:[m.targets[0],m.targets[0]]},{transportFactory:factory(async()=>{calls++;throw Object.assign(Error(code),{code});})});assert.equal(calls,1);assert.equal(out[0].error,code);assert.equal(out[1].fetched,false);}});
test('unexpected audit/output I/O failures remain fatal, never ordinary site failures',async()=>{let sends=0;const event=latchedEvents(()=>{throw Error('audit_failed');});await assert.rejects(h.collectPages(m,{event,transportFactory:factory(async()=>{sends++;return htmlResponse();})}),/audit_failed/);assert.equal(sends,0);await assert.rejects(h.collectPages(m,{transportFactory:factory(async()=>htmlResponse()),onPage:()=>{throw Error('output_failed');}}),/output_failed/);});
test('no real network/process calls can occur in this suite',()=>{assert.throws(()=>fetch('https://example.com/'),/offline_builder/);assert.throws(()=>require('node:https').get('https://example.com/'),/offline_builder/);assert.throws(()=>require('node:child_process').spawn('anything'),/offline_builder/);});

test('all transitive parser and source capture pins present; current held reviews pinned separately',()=>{for(const f of ['brand-site-review.cjs','collect-ninth-sites.cjs','validate-sites.cjs','collect-tenth-identity-followup.cjs'])assert(h.HELPER_PINS[f]);for(const[f,pin]of Object.entries(h.REVIEW_PINS))assert.equal(h.sha(read(f)),pin);});
test('separately pinned factual reviews cannot drift',()=>{assert.throws(()=>h.validateManifest(m,f=>f==='eleventh-public-review-a.json'?Buffer.concat([read(f),Buffer.from(' ')]):read(f)),/Pinned evidence changed/);});
test('exact new subdomain has original anchor proof but transport is restricted to that target host',async()=>{const t=m.targets[2];assert.equal(t.owner_url,'https://en.sarutahiko.jp/');assert.equal(h.transportOwner(t),'https://brand.sarutahiko.jp/');let calls=0;const out=await h.collectPages({...m,targets:[t]},{transportFactory:factory(async u=>{calls++;assert.equal(u.href,t.url);return{status:302,location:'https://other.sarutahiko.jp/brand',body:Buffer.alloc(0)};})});assert.equal(calls,1);assert.equal(out[0].error,'owner_host_mismatch');});
test('source cache line/raw literal anchor/href ownership cannot be rebound',()=>{for(const mutate of [t=>t.source_cache_line_sha256='0'.repeat(64),t=>t.source_cache_file='other.ndjson',t=>t.source_cache_sha256='0'.repeat(64),t=>t.anchor_html+=' ',t=>t.owner_url='https://elsewhere.example/',t=>t.observed_same_domain_family='elsewhere.example']){const bad=clone();mutate(bad.targets[0]);assert.throws(()=>h.validateManifest(bad,read));}});
test('missing pinned prior request file blocks novelty verification',()=>{const bad=clone();delete bad.inputHashes['requests.ndjson'];assert.throws(()=>h.validateManifest(bad,read),/Missing novelty ledger/);});

