'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
globalThis.fetch=async()=>{throw Error('LIVE_NETWORK_FORBIDDEN');};
for(const n of ['node:http','node:https']){const m=require(n);m.request=m.get=()=>{throw Error('LIVE_NETWORK_FORBIDDEN');};}
for(const n of ['exec','execSync','spawn','spawnSync','execFile','execFileSync','fork'])require('node:child_process')[n]=()=>{throw Error('PROCESS_FORBIDDEN');};
const h=require('./compare-au79-letz-identities.cjs'),base=h.loadScope(),clone=structuredClone;
const E='11111111-1111-4111-8111-111111111111',L='22222222-2222-4222-8222-222222222222',S='33333333-3333-4333-8333-333333333333',C='44444444-4444-4444-8444-444444444444',OTHER='55555555-5555-4555-8555-555555555555';
function fixtures(){const e={id:E,name:'AU79',website_url:'https://au79cafe.com.au',fresh_extra:'preserve'},l={id:L,entity_id:E,address1:'27-29 Nicholson Street',city:'Abbotsford'},s={id:S,entity_id:E,source:'my_coffee_explorer',source_id:'roaster:public-catalog:au79cafe.com.au',raw_data:{all:'retained'}};return{nameHost:[e],address:[l],sourceProbe:[s],entities:[e],roles:[{entity_id:E,role:'cafe'},{entity_id:E,role:'roaster'}],locations:[l],sources:[s],canonical:[]};}
function response(url,rows,{status=200,range,type='application/json',raw}={}){const r=new Response(raw??JSON.stringify(rows),{status,headers:{'content-type':type,'content-range':range??(rows?.length?'0-'+(rows.length-1)+'/*':'*/*')}});Object.defineProperty(r,'url',{value:url});return r;}
function harness({data=fixtures(),...opts}={}){const scope=clone(base),calls=[],events=[];let clock=0;const reader=h.createReader({scope,key:'fixture',now:()=>clock,wait:async ms=>{clock+=ms;},event:e=>events.push(e),delegate:async(request,init)=>{calls.push({method:request.method,url:request.url,at:clock,init});const offset=Number(new URL(request.url).searchParams.get('offset')||0);const kind=[...h.INITIAL,...h.CONTEXT].find(k=>{try{return h.descriptor(k,scope,offset).url===request.url;}catch{return false;}});return response(request.url,offset?[]:data[kind]);},...opts});return{scope,reader,calls,events,data};}
test('offline pins: only two factual candidates, five pages and six original product source rows',()=>{assert.deepEqual(base.candidates.map(c=>c.name),['AU79','Lëtz Coffee']);assert.equal(base.candidates.flatMap(c=>c.pages).length,5);assert.equal(base.candidates.flatMap(c=>c.productEvidence).length,6);assert.equal(Object.keys(base.pins).length,6);assert.deepEqual(base.owners,[]);});
test('source assertions are literal pinned excerpts, not production keyword inference',()=>{for(const c of base.candidates)for(const f of c.fragments){assert.equal(h.sha(f.text),f.sha256);assert.ok(f.utf16_start>=0);}assert.equal(base.candidates[1].observed_contact_host,'letzcoffee.com');});
test('default CLI offline; no apply, IDs, URLs, or arbitrary output accepted',()=>{assert.equal(h.cli([]),'--check');assert.equal(h.cli(['--read']),'--read');for(const a of [['--apply'],['--read','x'],['--url','x']])assert.throws(()=>h.cli(a));});
test('fixed current name/host/source/address probes with no owner/role restriction',()=>{for(const kind of h.INITIAL){const d=h.descriptor(kind,base),u=new URL(d.url);assert.equal(d.method,'GET');assert.equal(u.origin,h.ORIGIN);assert.equal(u.searchParams.get('select'),'*');assert.equal(u.searchParams.get('limit'),'51');assert.equal(u.searchParams.has('entity_id'),false);}const q=new URL(h.descriptor('nameHost',base).url).searchParams.get('or');for(const host of ['au79cafe.com.au','au79coffee.com.au','letz.coffee','letzcoffee.com'])assert.ok(q.includes(host));});
test('global exact source keys and caution source-host probes remain present',()=>{const q=new URL(h.descriptor('sourceProbe',base).url).searchParams.get('or');for(const c of base.candidates)assert.ok(q.includes(c.expected_source_key));assert.ok(q.includes('source_url.ilike'));});
test('observed address probes include both local language variants without guessing parent',()=>{const q=new URL(h.descriptor('address',base).url).searchParams.get('or');for(const part of ['Nicholson','Abbotsford','Riesenhaff','Koetschette'])assert.ok(q.includes(part));});
test('only bounded discovered UUIDs may enter child and canonical selectors',()=>{for(const kind of h.CONTEXT){assert.throws(()=>h.descriptor(kind,base));const s=clone(base);s.owners=[E];const u=new URL(h.descriptor(kind,s).url);assert.ok(u.search.includes(E));}const s=clone(base);s.owners=['bad'];assert.throws(()=>h.descriptor('roles',s));assert.throws(()=>h.descriptor('products',base));});
test('matched context retains all roles and full metadata without approving identity',async()=>{const x=harness(),r=await h.capture(x);assert.equal(r.requests,15);assert.equal(r.captureComplete,true);assert.equal(r.identityApproved,false);assert.equal(r.databasePlanningAllowed,false);assert.equal(r.full_catalog_current,false);assert.equal(r.writes,0);assert.deepEqual(r.state.sources[0].raw_data,{all:'retained'});assert.equal(r.state.roles.length,2);assert.ok(x.calls.every(c=>c.method==='GET'&&c.init.redirect==='error'));});
test('zero matches use only three reads and explicit skipped context, no empty filters',async()=>{const x=harness({data:{nameHost:[],address:[],sourceProbe:[]}}),r=await h.capture(x);assert.equal(r.requests,3);assert.deepEqual(r.matched_owner_ids,[]);assert.equal(r.coverage.filter(c=>c.skipped).length,5);assert.equal(r.full_catalog_current,false);assert.ok(x.calls.every(c=>!c.url.includes('in.%28%29')));});
test('canonical forward and inbound rows retained as hold; no recursive calls',async()=>{const d=fixtures();d.canonical=[{id:C,entity_id:OTHER,attribute_key:'canonical_roaster_entity_id',attribute_value:E}];const x=harness({data:d}),r=await h.capture(x);assert.equal(r.canonical_review_required,true);assert.equal(r.requests,16);assert.deepEqual(r.matched_owner_ids,[E]);const q=new URL(h.descriptor('canonical',x.scope).url).searchParams.get('or');assert.ok(q.includes('entity_id.in.')&&q.includes('attribute_value.in.'));});
test('source-only matching owner is not lost when name and location probes are empty',async()=>{const d=fixtures();d.nameHost=[];d.address=[];const x=harness({data:d}),r=await h.capture(x);assert.deepEqual(r.matched_owner_ids,[E]);assert.equal(r.state.entities[0].id,E);});
test('same-address unrelated owner is evidence only, never automatically merged',async()=>{const d=fixtures();d.nameHost=[];d.sourceProbe=[];d.entities[0].name='Other Business';const r=await h.capture(harness({data:d}));assert.equal(r.identityApproved,false);assert.equal(r.state.entities[0].name,'Other Business');});
test('missing matched entity and changing full rows stop after retaining partial evidence',async()=>{for(const mode of ['missing','drift']){const d=fixtures();d.entities=mode==='missing'?[]:[{...d.entities[0],fresh_extra:'changed'}];await assert.rejects(h.capture(harness({data:d})),/matched_owner_missing|row_changed_during_reads/);}});
test('51 rows fail rather than silently truncating',async()=>{const x=harness({delegate:async r=>response(r.url,Array.from({length:51},()=>({})))});await assert.rejects(x.reader.request('nameHost'),/row_bound/);});
test('nonempty continuation stops; a short server page is never inferred complete',async()=>{let n=0;const reader={requests:0,async request(){this.requests++;return n++===0?fixtures().nameHost:[{id:OTHER}];}};await assert.rejects(h.capture({scope:clone(base),reader}),/nonempty_continuation/);assert.equal(reader.requests,2);});
test('matched owners capped20 including source and location owners',async()=>{const data={nameHost:[],address:Array.from({length:21},(_,i)=>({id:'22222222-2222-4222-8222-'+String(i).padStart(12,'0'),entity_id:'11111111-1111-4111-8111-'+String(i).padStart(12,'0')})),sourceProbe:[]};await assert.rejects(h.capture(harness({data})),/owner_bound/);});
test('duplicate keys, out-of-order rows, malformed identities rejected',()=>{for(const rows of [[fixtures().nameHost[0],fixtures().nameHost[0]],[{id:'bad'}],[{id:OTHER},{id:E}]])assert.throws(()=>h.validateRows('nameHost',rows,base));const s=clone(base);s.owners=[E];assert.throws(()=>h.validateRows('roles',[{entity_id:OTHER,role:'cafe'}],s),/foreign_context_row/);assert.throws(()=>h.validateRows('canonical',[{id:C,entity_id:E,attribute_key:'wrong',attribute_value:OTHER}],s),/canonical_scope/);});
test('source natural-key duplicates rejected even with unique row IDs',()=>{const rows=[fixtures().sourceProbe[0],{...fixtures().sourceProbe[0],id:OTHER}];assert.throws(()=>h.validateRows('sourceProbe',rows,base),/duplicate_source_key/);});
test('JSON shape and media type fail closed',async()=>{for(const opt of [{raw:'null'},{raw:'{}'},{type:'text/html'}]){const x=harness({delegate:async r=>response(r.url,[],opt)});await assert.rejects(x.reader.request('nameHost'),/row_bound|content_type/);}});
test('missing and inconsistent Content-Range rejected',async()=>{for(const range of ['','bad','1-1/*','0-0/2']){const x=harness({delegate:async r=>response(r.url,[{}],{range})});await assert.rejects(x.reader.request('nameHost'),/content_range|reported_total_incomplete/);}});
test('foreign, same-origin changed, and empty response URLs rejected',async()=>{for(const url of ['',h.ORIGIN+'/rest/v1/other','https://invalid.test']){const x=harness({delegate:async()=>response(url,[])});await assert.rejects(x.reader.request('nameHost'),/exact_response_url/);}});
test('500/57014 error latches with no second GET or retry',async()=>{let n=0;const x=harness({delegate:async r=>{n++;return response(r.url,[],{status:500,raw:'{"code":"57014"}'});}});await assert.rejects(x.reader.request('nameHost'),e=>e.httpStatus===500&&e.dbCode==='57014');await assert.rejects(x.reader.request('address'));assert.equal(n,1);});
test('missing identity/alias table is not optional absence',async()=>{const x=harness({delegate:async r=>response(r.url,[],{status:404,raw:'{"code":"PGRST205"}'})});await assert.rejects(x.reader.request('nameHost'),e=>e.httpStatus===404);});
test('redirect response, deadline and oversized body stop without fallback',async()=>{for(const opt of [{status:302},{raw:'x'.repeat(h.MAX_BODY+1)}]){const x=harness({delegate:async r=>response(r.url,[],opt)});await assert.rejects(x.reader.request('nameHost'));}const x=harness({timeoutMs:5,delegate:()=>new Promise(()=>{})});await assert.rejects(x.reader.request('nameHost'),/timeout_or_abort/);});
test('completion pacing survives slow requests and early waking sleeps',async()=>{let clock=0,last=0;const starts=[];const x=harness({now:()=>clock,wait:async ms=>{clock+=Math.max(1,ms-1);},delegate:async r=>{starts.push(clock);clock+=700;last=clock;return response(r.url,[]);}});await x.reader.request('nameHost');const done=last;await x.reader.request('address');assert.ok(starts[1]-done>=500);});
test('global deadline after pacing or body prevents further successful read',async()=>{let clock=0,n=0;const x=harness({now:()=>clock,wait:async()=>{clock+=h.MAX_MS;},delegate:async r=>{n++;return response(r.url,[]);}});await x.reader.request('nameHost');await assert.rejects(x.reader.request('address'));assert.equal(n,1);const y=harness({now:()=>clock,delegate:async r=>{clock+=h.MAX_MS;return response(r.url,[]);}});await assert.rejects(y.reader.request('nameHost'),/reader_stopped_or_bound/);});
test('lock loss and journal failure stop before dispatch',async()=>{for(const opt of [{checkLock:()=>{throw Error('lock');}},{event:()=>{throw Error('journal');}}]){let n=0;const x=harness({...opt,delegate:async r=>{n++;return response(r.url,[]);}});await assert.rejects(x.reader.request('nameHost'));assert.equal(n,0);}});
test('concurrent request rejects both, not just the second',async()=>{let release,n=0;const x=harness({delegate:r=>{n++;return new Promise(resolve=>{release=()=>resolve(response(r.url,[]));});}});const first=x.reader.request('nameHost');await new Promise(setImmediate);await assert.rejects(x.reader.request('address'));release();await assert.rejects(first);assert.equal(n,1);});
test('strict16request bound',async()=>{const x=harness({delegate:async r=>response(r.url,[])});for(let i=0;i<16;i++)await x.reader.request('nameHost');await assert.rejects(x.reader.request('nameHost'));});
test('exclusive receipt cannot overwrite earlier evidence',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'two-identity-fixture-')),file=path.join(dir,'receipt.json');h.save(file,{readOnly:true});assert.throws(()=>h.save(file,{}),/EEXIST/);assert.deepEqual(JSON.parse(fs.readFileSync(file)),{readOnly:true});fs.unlinkSync(file);fs.rmdirSync(dir);});
