'use strict';
// Offline only: all real network/process entrypoints denied before loading the adapter.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
for(const name of ['node:http','node:https','node:net','node:tls','node:dns','node:child_process']){const m=require(name);for(const k of ['request','get','connect','createConnection','lookup','resolve','resolve4','resolve6','exec','execFile','spawn','fork','execSync','execFileSync','spawnSync'])if(typeof m[k]==='function')m[k]=()=>{throw Error('real_external_api_denied');};}
globalThis.fetch=()=>{throw Error('real_fetch_denied');};
const h=require('./import-reviewed-seven-paced-v2.cjs'),core=require('./import-plan11-paced.cjs'),bundle=h.loadBundle();
const clone=x=>JSON.parse(JSON.stringify(x)),uid=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
const C=bundle.contexts[0],spec=h.probeSpec(C,'nameHost');
function response(req,rows=[],status=200,{url=req.url,type='application/json',range=rows.length?'0-'+(rows.length-1)+'/*':'*/*'}={}){const r=new Response(JSON.stringify(rows),{status,headers:{'Content-Type':type,'Content-Range':range}});Object.defineProperty(r,'url',{value:url});return r;}
function clock(){let at=1000000;return{now:()=>at,wait:async n=>{at+=n;},advance:n=>{at+=n;}};}
function clientFixture(delegate,extra={}){const time=clock(),events=[];return{time,events,client:h.createClient({bundle,key:'test-key',delegate,event:e=>events.push(e),now:time.now,wait:time.wait,...extra})};}
function fakeDatabase(){const baseline=h.snapshotContext(bundle.snapshot,[...new Set(bundle.contexts.flatMap(c=>c.expected.ids))]),db=clone(baseline),actions=[],events=[];db.entities.push({id:uid(90000),name:'Unrelated Sentinel',slug:'sentinel',name_slug:'sentinel',website_url:null,primary_location:'Unrelated City',google_place_id:null});let requests=0,posts=0,seq=100000;
 const client={get requests(){return requests;},get posts(){return posts;},assertHealthy(){},async read(s,{cursor=null,offset=0}={}){requests++;let rows;
   if(s.tag.startsWith('context:')){const k=s.tag.split(':')[1];rows=db[k].filter(r=>s.ids.includes(k==='entities'?r.id:r.entity_id)||(k==='canonical'&&s.ids.includes(r.attribute_value)));}
   else {const [group,id]=s.tag.split(':'),c=bundle.contexts.find(c=>c.action.entity_id===id),k={nameHost:'entities',address:'locations',sourceProbe:'sources'}[group];rows=db[k].filter(r=>h.matches(c,group,r));}
   const roles=s.table==='entity_roles';rows=rows.sort((a,b)=>String(roles?a.entity_id+'\n'+a.role:a.id).localeCompare(String(roles?b.entity_id+'\n'+b.role:b.id)));return clone(roles?rows.slice(offset,offset+h.PAGE):rows.filter(r=>!cursor||r.id>cursor).slice(0,h.PAGE));
  },async request(kind,c,o={}){requests++;const id=c.action.entity_id;if(kind.startsWith('insert')){o.validateWrite();posts++;const body=core.descriptor(kind,c,o).body,key={insertEntity:'entities',insertRole:'roles',insertSource:'sources'}[kind];const row={...clone(body),...(kind==='insertRole'?{}:{id:body.id||uid(seq++)}),created_at:o.at};db[key].push(row);actions.push({kind,id,body:clone(body)});return[clone(row)];}
   let rows=db[kind].filter(r=>kind==='entities'?r.id===id:kind==='canonical'?(r.entity_id===id||r.attribute_value===id):kind==='sources'?(r.entity_id===id||r.source==='my_coffee_explorer'&&r.source_id===c.action.sources[0].source_id):r.entity_id===id);return clone(o.offset?rows.slice(o.offset,o.offset+1):rows);
  }};return{db,client,actions,events};}
test('pinned plan has seven create-only owners and all61 evidence pins validate',()=>{assert.equal(bundle.plan.actions.length,7);assert.equal(Object.keys(bundle.plan.preparationEvidenceHashes).length,61);assert.equal(bundle.contexts.flatMap(c=>c.expected.ids).length,6);assert(!bundle.contexts.some(c=>c.action.candidate_key==='centricoffee.com'));});
test('all requested street cues occur in literal evidence; no city-only descriptor',()=>{assert.equal(h.ADDRESS['yardstickcoffee.com'].length,0);for(const c of bundle.contexts){for(const a of c.address)assert(!['savannah','toronto','thatcham','wa u watosa'].includes(a.phrase));for(const g of ['nameHost','sourceProbe'])assert.equal(new URL(h.readDescriptor(h.probeSpec(c,g)).url).origin,h.ORIGIN);}});
test('default and --queries are offline; apply requires exact explicit confirmation',()=>{assert.equal(h.cli([]).mode,'check');assert.equal(h.cli(['--queries']).mode,'queries');assert.throws(()=>h.cli(['--apply','x','0'.repeat(64)]));assert.equal(h.cli(['--apply','x','0'.repeat(64),'--confirm-seven-new-roasters-and-identity-writers-paused']).mode,'apply');});
test('plan modification rejected even if attacker recomputes planHash',()=>{const p=clone(bundle.plan);p.actions[0].entity.name='changed';const{planHash,...body}=p;p.planHash=h.sha(JSON.stringify(body));assert.throws(()=>h.validatePlan(p),/plan_scope/);});
test('host boundary rejects suffix-neighbor and permits actual subdomain',()=>{assert(!h.hostMatch('https://evilcaffemorandini.it/',C.hosts));assert(h.hostMatch('https://shop.caffemorandini.it/',C.hosts));});
test('address word matching does not turn Spruce into Ruc or Subway into Way',()=>{assert(!h.matches(C,'address',{address1:'1101 Spruce Street'}));assert(h.matches(C,'address',{address1:'1/C V. RUC, Esine'}));const c=bundle.contexts.find(c=>c.action.candidate_key==='wbroast.co.uk');assert(!h.matches(c,'address',{address1:'Lower, Vista Park, 31 Subway St'}));});
test('source key host-bearing caution is retained even outside MCE source namespace',()=>{assert(h.matches(C,'sourceProbe',{source:'other',source_id:'business:caffemorandini.it',source_url:null}));});
test('empty context IDs and query injection rejected offline',()=>{assert.throws(()=>h.contextSpec('sources',[]));assert.throws(()=>h.contextSpec('sources',['abc']));assert.throws(()=>h.readDescriptor(spec,{cursor:'abc'}));});
test('changed or broad GET descriptor rejected without dispatch and latches',async()=>{let calls=0;const{client}=clientFixture(async r=>{calls++;return response(r);});await assert.rejects(client.read({...spec,filters:{}},{}),/descriptor_changed/);await assert.rejects(client.read(spec,{}),/stopped/);assert.equal(calls,0);});
test('arbitrary table and context filters cannot be dispatched',async()=>{const{client}=clientFixture(async()=>assert.fail());await assert.rejects(client.read({...h.contextSpec('entities',[uid(1)]),table:'products'},{}),/descriptor_changed/);});
test('GET actual full encoded URL journaled; no count or mutation preference',async()=>{const{client,events}=clientFixture(async req=>{assert.equal(req.method,'GET');assert(!req.headers.has('Prefer'));assert.equal(new URL(req.url).searchParams.get('limit'),'100');return response(req);});await client.read(spec,{});assert.equal(events.find(e=>e.event==='read_intent').url,h.readDescriptor(spec).url);});
test('strict completion pacing handles early wake and slow response',async()=>{let t=0,waits=0;const starts=[];const c=h.createClient({bundle,key:'fake',now:()=>t,wait:async ms=>{t+=++waits===1?ms-1:ms;},delegate:async req=>{starts.push(t);t+=750;return response(req);}});await c.read(spec,{});await c.read(spec,{});assert(starts[1]-starts[0]>=1250);assert(waits>=2);});
for(const [name,make,code]of [
 ['changed response URL',r=>response(r,[],200,{url:r.url+'&changed=1'}),'exact_response_url'],
 ['empty response URL',r=>response(r,[],200,{url:''}),'exact_response_url'],
 ['bad content type',r=>response(r,[],200,{type:'text/html'}),'content_type'],
 ['bad range',r=>response(r,[{id:uid(1)}],200,{range:'1-1/*'}),'content_range'],
 ['empty with total still remaining',r=>response(r,[],200,{range:'*/3'}),'empty_before_reported_total'],
 ['more than100 rows',r=>response(r,Array.from({length:101},(_,i)=>({id:uid(i)}))),'row_bound'],
 ['HTTP error',r=>response(r,[],404),'database_http_error']
])test(name+' fails and stops subsequent request',async()=>{let n=0;const{client}=clientFixture(async req=>{n++;return make(req);});await assert.rejects(client.read(spec,{}),new RegExp(code));await assert.rejects(client.read(spec,{}));assert.equal(n,1);});
test('500 stops before second dispatch',async()=>{let n=0;const{client}=clientFixture(async req=>{n++;return response(req,{code:'57014'},500);});await assert.rejects(client.read(spec,{}));await assert.rejects(client.read(spec,{}));assert.equal(n,1);});
test('body >4MiB fails before use',async()=>{const{client}=clientFixture(async req=>response(req,[{id:uid(1),x:'x'.repeat(4*1024*1024)}]));await assert.rejects(client.read(spec,{}),/response_too_large/);});
test('request timeout ignores late delegate and latches',async()=>{const{client}=clientFixture(()=>new Promise(()=>{}),{timeoutMs:5});await assert.rejects(client.read(spec,{}),/timeout/);await assert.rejects(client.read(spec,{}));});
test('concurrent denial prevents in-flight response acceptance',async()=>{let release,started;const ready=new Promise(r=>started=r),{client}=clientFixture(req=>new Promise(r=>{release=()=>r(response(req));started();}));const first=client.read(spec,{});await ready;await assert.rejects(client.read(spec,{}),/concurrent/);release();await assert.rejects(first,/stopped/);});
test('deadline crossing after body processing stops',async()=>{const time=clock(),c=h.createClient({bundle,key:'fake',now:time.now,wait:time.wait,delegate:async req=>{time.advance(h.MAX_MS);return response(req);}});await assert.rejects(c.read(spec,{}),/deadline/);});
test('no POST in preview, unknown context refused',async()=>{const{client}=clientFixture(async()=>assert.fail());await assert.rejects(client.request('insertEntity',C,{at:new Date().toISOString(),validateWrite(){}}),/post_scope/);});
test('plain POST sends only exact entity payload and no upsert',async()=>{let calls=0;const{client}=clientFixture(async req=>{calls++;assert.equal(req.method,'POST');assert.equal(req.headers.get('Prefer'),'return=representation');const b=await req.json();assert.deepEqual(b,C.action.entity);return response(req,[b],201);},{allowWrites:true});const opts={at:new Date().toISOString(),validateWrite(){}};await client.request('insertEntity',C,opts);await assert.rejects(client.request('insertEntity',C,opts),/replay/);assert.equal(calls,1);});
test('write authorization runs again after pacing and can stop dispatch',async()=>{let calls=0,auth=0;const{client}=clientFixture(async req=>{calls++;return response(req);},{allowWrites:true});await client.read(spec,{});await assert.rejects(client.request('insertEntity',C,{at:new Date().toISOString(),validateWrite(){if(++auth===2)throw Error('authorization_expired');}}),/authorization_expired/);assert.equal(calls,1);});
test('500UUID rows require explicit sixth empty page',async()=>{const rows=Array.from({length:500},(_,i)=>({id:uid(i+1)})),cursors=[];const c={read:async(s,o)=>{cursors.push(o.cursor);return rows.filter(r=>!o.cursor||r.id>o.cursor).slice(0,100);}};assert.equal((await h.collect(c,spec)).length,500);assert.equal(cursors.length,6);});
test('501UUID rows fail rather than truncate',async()=>{const rows=Array.from({length:501},(_,i)=>({id:uid(i+1)}));await assert.rejects(h.collect({read:async(s,o)=>rows.filter(r=>!o.cursor||r.id>o.cursor).slice(0,100)},spec),/group_row_bound/);});
test('short server pages continue until empty',async()=>{let n=0;const rows=Array.from({length:5},(_,i)=>({id:uid(i+1)}));assert.equal((await h.collect({read:async(s,o)=>{n++;return rows.filter(r=>!o.cursor||r.id>o.cursor).slice(0,2);}},spec)).length,5);assert.equal(n,4);});
test('duplicate and cursor regression fail closed',async()=>{let n=0;await assert.rejects(h.collect({read:async()=>++n===1?[{id:uid(2)}]:[{id:uid(1)}]},spec),/duplicate_or_unordered/);});
test('malformed row fails before continuation',async()=>{await assert.rejects(h.collect({read:async()=>[{id:'bad'}]},spec),/row_shape/);});
test('role cap1 proves next-offset empty and retains all roles',async()=>{const s=h.contextSpec('roles',[uid(1)]),rows=['cafe','roaster'].map(role=>({entity_id:uid(1),role})),offsets=[];assert.deepEqual(await h.collect({read:async(s,o)=>{offsets.push(o.offset);return rows.slice(o.offset,o.offset+1);}},s),rows);assert.deepEqual(offsets,[0,0,1,1,2]);});
test('role boundary shift fails, no guessed enum ordering',async()=>{let n=0;const s=h.contextSpec('roles',[uid(1)]);await assert.rejects(h.collect({read:async()=>++n===1?[{entity_id:uid(1),role:'cafe'}]:[{entity_id:uid(1),role:'roaster'}]},s),/role_boundary_changed/);});
test('lost overlap row is not terminal success',async()=>{let n=0;await assert.rejects(h.collect({read:async()=>++n===1?[{entity_id:uid(1),role:'cafe'}]:[]},h.contextSpec('roles',[uid(1)])),/lost_role_overlap/);});
test('canonical closure traverses both directions and detects cycles',()=>{const s={canonicalLinks:[{entity_id:uid(1),attribute_value:uid(2)},{entity_id:uid(3),attribute_value:uid(2)}]};assert.deepEqual(h.closure(s,[uid(1)]),[uid(1),uid(2),uid(3)]);assert.throws(()=>h.checkCycles([{entity_id:uid(1),attribute_value:uid(2)},{entity_id:uid(2),attribute_value:uid(1)}]),/cycle/);});
test('projected current drift rejected while SQL non-identity metadata stays in full preview',()=>{const row={id:uid(1),entity_id:uid(2),source:'x',source_id:'a',source_url:null};assert.throws(()=>h.compareProjection([{...row,source_id:'b'}],[row],'sources'),/identity_drift/);h.compareProjection([{...row,raw_data:{x:1}}],[row],'sources');});
test('new address candidate is held after full hydration',async()=>{const f=fakeDatabase(),c=bundle.contexts.find(c=>c.action.candidate_key==='starbeanscoffeeroasters.com');f.db.entities.push({id:uid(11),name:'Other',slug:'other',name_slug:'other',website_url:null});f.db.locations.push({id:uid(12),entity_id:uid(11),address1:'4307 Ogeechee Road'});await assert.rejects(h.captureCandidate(f.client,c),/new_or_missing_candidate/);});
test('new incoming canonical edge is held',async()=>{const f=fakeDatabase(),c=bundle.contexts.find(c=>c.expected.ids.length);f.db.entities.push({id:uid(11),name:'Alias',slug:'alias',name_slug:'alias',website_url:null});f.db.canonical.push({id:uid(12),entity_id:uid(11),attribute_key:'canonical_roaster_entity_id',attribute_value:c.expected.ids[0],source:'manual'});await assert.rejects(h.captureCandidate(f.client,c),/new_or_missing_candidate/);});
test('preview completes with zero inserts and six only directly matched caution IDs',async t=>{const f=fakeDatabase(),r=await h.execute({bundle,client:f.client});assert.equal(r.status,'preview_complete');assert.equal(r.writes,0);assert.equal(f.actions.length,0);assert.equal(r.before.flatMap(x=>x.ids).length,6);assert(r.requests<h.MAX_REQUESTS);t.diagnostic('Expected-match fixture preview requests: '+r.requests);});
test('entire apply makes exact21INSERTs; preserves all old rows; individual+final readback',async t=>{const f=fakeDatabase(),original=clone(f.db),p=await h.execute({bundle,client:f.client});const fresh=fakeDatabase(),r=await h.execute({bundle,client:fresh.client,mode:'apply',preview:p,event:e=>fresh.events.push(e)});assert.equal(r.status,'complete');assert.equal(r.verified,7);assert.equal(fresh.actions.length,21);assert.equal(fresh.events.filter(e=>e.event==='owner_complete').length,7);for(const k of Object.keys(original))assert.deepEqual(fresh.db[k].slice(0,original[k].length),original[k]);for(let i=0;i<7;i++){assert.deepEqual(fresh.actions.slice(i*3,i*3+3).map(a=>a.kind),['insertEntity','insertRole','insertSource']);assert.deepEqual(fresh.actions[i*3].body,bundle.plan.actions[i].entity);}assert(r.requests<h.MAX_REQUESTS);t.diagnostic('Expected-match fixture apply requests: '+r.requests);});
test('expired preview blocks before any request or write',async()=>{const f=fakeDatabase(),p=await h.execute({bundle,client:f.client}),next=fakeDatabase();await assert.rejects(h.execute({bundle,client:next.client,mode:'apply',preview:p,now:()=>Date.parse(p.at)+h.TTL_MS}),/preview_expired/);assert.equal(next.client.requests,0);});
test('all seven preflight before first write catches later occupied ID',async()=>{const f=fakeDatabase(),p=await h.execute({bundle,client:f.client}),fresh=fakeDatabase();fresh.db.entities.push(clone(bundle.plan.actions[6].entity));await assert.rejects(h.execute({bundle,client:fresh.client,mode:'apply',preview:p}));assert.equal(fresh.actions.length,0);});
test('partial POST failure stops without retry or later owner',async()=>{const f=fakeDatabase(),p=await h.execute({bundle,client:f.client}),fresh=fakeDatabase(),orig=fresh.client.request;fresh.client.request=async(k,c,o)=>{if(k==='insertRole')throw Error('uncertain_POST');return orig(k,c,o);};await assert.rejects(h.execute({bundle,client:fresh.client,mode:'apply',preview:p}),/uncertain_POST/);assert.equal(fresh.actions.length,1);});
test('returned source SQL timestamp equivalent spelling accepted by frozen primitive',()=>{const e={last_synced_at:'2026-09-27T20:00:00.000Z',source_id:'x'};assert.equal(core.checkInserted([{...e,last_synced_at:'2026-09-27T20:00:00+00:00'}],e).source_id,'x');});
test('v1 incident reproduced: set(id,cursor) loses IN, v2 getAll(id) retains both',()=>{const ids=[uid(1),uid(2)],s=h.contextSpec('entities',ids),old=require('./import-reviewed-seven-paced.cjs');const before=new URL(h.readDescriptor(s).url).searchParams,broken=new URL(old.readDescriptor(s,{cursor:uid(1)}).url).searchParams,fixed=new URL(h.readDescriptor(s,{cursor:uid(1)}).url).searchParams;assert.equal(before.getAll('id').length,1);assert.deepEqual(broken.getAll('id'),['gt.'+uid(1)]);assert.deepEqual(fixed.getAll('id'),[before.get('id'),'gt.'+uid(1)]);});
test('every serialized UUID continuation retains all original probe/context predicates',()=>{const specs=bundle.contexts.flatMap(c=>['nameHost','address','sourceProbe'].filter(k=>k!=='address'||c.address.length).map(k=>h.probeSpec(c,k))).concat(['entities','locations','sources','canonical'].map(k=>h.contextSpec(k,[uid(1),uid(2)])));for(const s of specs){const initial=new URL(h.readDescriptor(s).url).searchParams;for(const cursor of [uid(1),uid(2)]){const next=new URL(h.readDescriptor(s,{cursor}).url).searchParams;for(const[k,v]of initial)assert(next.getAll(k).includes(v),s.tag+' lost '+k);assert(next.getAll('id').includes('gt.'+cursor));assert.equal(next.getAll('id').length,initial.getAll('id').length+1);}}});
test('real transport plus collect evaluates serialized IN AND cursor, never global tail',async()=>{const ids=Array.from({length:6},(_,i)=>uid(i+1)),rows=[...ids.map(id=>({id})),{id:uid(90000)}],s=h.contextSpec('entities',ids),urls=[];const{client}=clientFixture(async req=>{urls.push(req.url);const q=new URL(req.url).searchParams,filters=q.getAll('id'),inFilter=filters.find(x=>x.startsWith('in.'));assert(inFilter,'physical request lost owner IN');assert.equal(inFilter,s.filters.id);const gt=filters.find(x=>x.startsWith('gt.'))?.slice(3),allowed=[...inFilter.matchAll(/"([0-9a-f-]{36})"/g)].map(m=>m[1]);const page=rows.filter(r=>allowed.includes(r.id)&&(!gt||r.id>gt)).slice(0,2);return response(req,page);});assert.deepEqual(await h.collect(client,s),ids.map(id=>({id})));assert.equal(urls.length,4);assert(urls.slice(1).every(url=>new URL(url).searchParams.getAll('id').length===2));});
test('serialized roles continuation retains owner IN alongside offset',()=>{const s=h.contextSpec('roles',[uid(1)]),initial=new URL(h.readDescriptor(s).url).searchParams,next=new URL(h.readDescriptor(s,{offset:1}).url).searchParams;assert.deepEqual(next.getAll('entity_id'),initial.getAll('entity_id'));assert.equal(next.get('offset'),'1');assert.equal(next.getAll('id').length,0);});
