'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const h=require('./preflight-batch8b-paced-six.cjs'),s=h.loadScope();
function fixture(){let time=100000,fault=null;const data={entities:s.targets.map(t=>({id:t.entity_id,name:t.name,website_url:t.website_url,slug:'retained',name_slug:'retained',primary_location:null,google_place_id:null})),entity_roles:s.owners.map(id=>({entity_id:id,role:'roaster'})),entity_source_ids:s.sources.map((r,i)=>({id:'source-'+i,...r,source_url:'https://mycoffeeexplorer.com/coffees'})),entity_attributes:[],entity_crawl_state:[],crawl_runs:[],products:[],known_pages:[]},calls=[],events=[];
 const delegate=async(url,init)=>{const u=new URL(url),table=u.pathname.split('/').at(-1),offset=Number(u.searchParams.get('offset')||0);calls.push({url,init});if(fault){const r=await fault({u,table,offset,data,calls});if(r)return r;}let rows=structuredClone(data[table]);for(const[k,v]of u.searchParams){if(['select','limit','offset','order'].includes(k))continue;if(v.startsWith('in.(')){const allowed=v.slice(4,-1).split(',');rows=rows.filter(r=>allowed.includes(String(r[k])));}else if(v.startsWith('eq.'))rows=rows.filter(r=>String(r[k])===v.slice(3));}rows=rows.slice(offset,offset+Number(u.searchParams.get('limit'))).map(r=>Object.fromEntries(u.searchParams.get('select').split(',').map(k=>[k,r[k]])));return new Response(JSON.stringify(rows),{status:200,headers:{'content-type':'application/json','content-range':rows.length?offset+'-'+(offset+rows.length-1)+'/*':'*/*'}});};
 const client=h.createClient({scope:s,key:'offline-not-a-key',delegate,event:e=>events.push(e),now:()=>time,wait:async ms=>{time+=ms;}});return{data,calls,events,client,setFault:f=>fault=f};
}
test('manifest/sourceclosure/transitive runtime/parser pins validate offline',()=>{assert.equal(s.manifest_sha256,h.MANIFEST_SHA);assert.equal(s.targets.length,4);assert.equal(s.urls.length,6);assert.equal(s.canonical_schema.fields,'id,entity_id,attribute_key,attribute_value,source');});
test('clean preflight performs12GETs, no body/mutation/count/RPC and doesnot authorizecrawl',async()=>{const f=fixture(),r=await h.run({client:f.client,scope:s});assert.equal(r.status,'read_only_preflight_pass');assert.equal(r.requests,12);assert.equal(r.writes,0);assert.equal(r.activation_authorized,false);for(const c of f.calls){assert.equal(c.init.method,'GET');assert.equal(c.init.body,undefined);assert.equal(c.init.redirect,'error');assert(c.init.signal instanceof AbortSignal);assert.equal(c.init.headers.Prefer,undefined);assert.equal(new URL(c.url).origin,h.ORIGIN);}});
test('source-key/URL queries are global; inbound canonical matches attribute_value',()=>{for(const k of['products','knownPages','sourceBindings'])assert(!new URL(h.descriptor(k,s).url).searchParams.has('entity_id'));assert.equal(new URL(h.descriptor('canonicalIn',s).url).searchParams.get('attribute_value'),'in.('+s.owners.join(',')+')');assert.equal(new URL(h.descriptor('canonicalOut',s).url).searchParams.get('attribute_key'),'eq.canonical_roaster_entity_id');});
for(const[name,edit,code]of[
 ['missing owner',f=>f.data.entities.pop(),'owner_count'],['owner site drift',f=>f.data.entities[0].website_url='https://other.invalid/','owner_identity_drift'],['owner name drift',f=>f.data.entities[0].name='changed','owner_identity_drift'],['missing roaster role',f=>f.data.entity_roles.pop(),'roaster_role_missing'],['reassigned source',f=>f.data.entity_source_ids[0].entity_id='other','source_binding_conflict'],['duplicate source',f=>f.data.entity_source_ids.push({...f.data.entity_source_ids[0],id:'other',entity_id:'other'}),'source_count'],['outgoing canonical',f=>f.data.entity_attributes.push({id:'alias',entity_id:s.owners[0],attribute_key:'canonical_roaster_entity_id',attribute_value:'other',source:'my_coffee_explorer'}),'canonical_link_conflict'],['incoming canonical',f=>f.data.entity_attributes.push({id:'alias',entity_id:'other',attribute_key:'canonical_roaster_entity_id',attribute_value:s.owners[0],source:'my_coffee_explorer'}),'canonical_link_conflict'],['crawl denied',f=>f.data.entity_crawl_state.push({entity_id:s.owners[0],allow_crawl:false}),'crawl_permission_denied'],['running owner claim',f=>f.data.crawl_runs.push({id:'running',entity_id:s.owners[0],status:'running',started_at:'2026-09-27T10:00:00Z'}),'active_crawl_conflict'],['same-owner existing product',f=>f.data.products.push({id:'product',entity_id:s.targets[0].entity_id,source_url:s.urls[0],name:'prior',is_active:true}),'existing_product_url_conflict'],['cross-owner inactive partial product',f=>f.data.products.push({id:'product',entity_id:'other',source_url:s.urls[0],name:'prior',is_active:false}),'existing_product_url_conflict'],['same-owner knownpage',f=>f.data.known_pages.push({id:'page',entity_id:s.targets[0].entity_id,url:s.urls[0],status:'coffee'}),'existing_known_page_url_conflict'],['cross-owner knownpage skip',f=>f.data.known_pages.push({id:'page',entity_id:'other',url:s.urls[0],status:'skip'}),'existing_known_page_url_conflict']
])test('holds '+name,async()=>{const f=fixture();edit(f);await assert.rejects(h.run({client:f.client,scope:s}),new RegExp(code));assert(f.calls.every(c=>c.init.method==='GET'));});
test('additional role collection is complete and preserved, not silentlytruncated',async()=>{const f=fixture();f.data.entity_roles.push({entity_id:s.owners[0],role:'cafe'});const r=await h.run({client:f.client,scope:s});assert.equal(r.state.roles.length,5);const g=fixture();g.setFault(({table,offset})=>table==='entity_roles'&&offset?new Response(JSON.stringify([{entity_id:s.owners[0],role:'cafe'}]),{headers:{'content-type':'application/json','content-range':offset+'-'+offset+'/*'}}):null);await assert.rejects(h.run({client:g.client,scope:s}),/nonempty_continuation/);});
test('optional JSON404 PGRST205 is explicitunknown not fabricatedpermission',async()=>{const f=fixture();f.setFault(({table})=>table==='entity_crawl_state'?new Response('{"code":"PGRST205"}',{status:404,headers:{'content-type':'application/json'}}):null);const r=await h.run({client:f.client,scope:s});assert.equal(r.crawl_permission.table_available,false);assert.equal(r.crawl_permission.permission_inferred,false);assert(f.events.some(e=>e.event==='optional_crawl_state_table_absent'));});
test('populated optionalpermission collection adds one emptyprobe only',async()=>{const f=fixture();f.data.entity_crawl_state.push({entity_id:s.owners[0],allow_crawl:true});const r=await h.run({client:f.client,scope:s});assert.equal(r.requests,13);assert.equal(r.crawl_permission.permission_inferred,false);});
test('all other HTTP/schema errors latch and prohibit another request',async()=>{for(const[status,code,type]of[[429,'rate_limit','application/json'],[503,'PGRST205','application/json'],[400,'57014','application/json'],[500,'53300','application/json'],[404,'42P01','application/json'],[404,'PGRST205','text/html'],[401,'no_auth','application/json'],[403,'no_auth','application/json']]){const f=fixture();f.setFault(()=>new Response(JSON.stringify({code}),{status,headers:{'content-type':type}}));await assert.rejects(f.client.request('crawlState'));await assert.rejects(f.client.request('owners'),/stopped/);assert.equal(f.calls.length,1);}});
test('optional table error on another table failsclosed',async()=>{const f=fixture();f.setFault(()=>new Response('{"code":"PGRST205"}',{status:404,headers:{'content-type':'application/json'}}));await assert.rejects(f.client.request('owners'),/database_http_error/);});
test('wrong contentrange/contenttype/JSON/rowlimit stops',async()=>{for(const response of[
 ()=>new Response('[]',{headers:{'content-type':'application/json'}}),
 ()=>new Response('[]',{headers:{'content-type':'text/html','content-range':'*/*'}}),
 ()=>new Response('{bad',{headers:{'content-type':'application/json','content-range':'*/*'}}),
 ()=>new Response(JSON.stringify(Array(25).fill({})),{headers:{'content-type':'application/json','content-range':'0-24/*'}}),
 ()=>new Response('[{}]',{headers:{'content-type':'application/json','content-range':'1-1/*'}})
 ]){const f=fixture();f.setFault(response);await assert.rejects(f.client.request('owners'));assert.equal(f.calls.length,1);}});
test('oversized body fails before success and network failure is not retried',async()=>{const f=fixture();f.setFault(()=>new Response('x'.repeat(h.MAX_BODY+1),{headers:{'content-type':'application/json','content-range':'*/*'}}));await assert.rejects(f.client.request('owners'),/response_too_large/);const g=fixture();g.setFault(()=>{throw Error('socket_reset');});await assert.rejects(g.client.request('owners'),/socket_reset/);await assert.rejects(g.client.request('owners'),/stopped/);assert.equal(g.calls.length,1);});
test('redirected or wrongorigin response is rejected',async()=>{for(const response of[{redirected:true,url:h.ORIGIN+'/'},{redirected:false,url:'https://other.invalid/'}]){const f=fixture();f.setFault(()=>response);await assert.rejects(f.client.request('owners'),/response_origin/);}});
test('outofscope mutation/RPC/offset cannot dispatch',async()=>{const f=fixture();for(const name of['patch','insert','delete','rpc'])assert.throws(()=>h.descriptor(name,s),/out_of_scope/);assert.throws(()=>h.descriptor('products',s,1),/offset/);assert.throws(()=>h.descriptor('owners',s,25),/offset/);assert.equal(f.calls.length,0);});
test('500ms spacing starts after complete stream plusaudit and rechecks earlywake',async()=>{let time=100000,early=true;const starts=[],waits=[];const c=h.createClient({scope:s,key:'offline',now:()=>time,wait:async ms=>{waits.push(ms);time+=early?(early=false,ms-1):ms;},event:e=>{if(e.event==='request_result')time+=70;},delegate:async()=>{starts.push(time);return new Response(new ReadableStream({pull(controller){time+=1200;controller.enqueue(new TextEncoder().encode('[]'));controller.close();}}),{headers:{'content-type':'application/json','content-range':'*/*'}});}});await c.request('roles');await c.request('roles');assert.deepEqual(waits,[500,1]);assert.equal(starts[1]-starts[0],1770);});
test('concurrent request latches without dispatching asecond call',async()=>{let release,calls=0;const c=h.createClient({scope:s,key:'offline',delegate:async()=>{calls++;await new Promise(r=>release=r);return new Response('[]',{headers:{'content-type':'application/json','content-range':'*/*'}});}});const first=c.request('roles');await assert.rejects(c.request('roles'),/concurrent/);release();await first;await assert.rejects(c.request('roles'),/stopped/);assert.equal(calls,1);});
test('request hardcap and elapsed cap stopbefore dispatch',async()=>{const f=fixture();for(let i=0;i<h.MAX_REQUESTS;i++)await f.client.request('activeClaims');await assert.rejects(f.client.request('activeClaims'),/request_or_time_bound/);assert.equal(f.calls.length,h.MAX_REQUESTS);let time=0,calls=0;const c=h.createClient({scope:s,key:'offline',now:()=>time,delegate:async()=>{calls++;}});time=h.MAX_ELAPSED_MS+1;await assert.rejects(c.request('roles'),/request_or_time_bound/);assert.equal(calls,0);});
test('journal failure prevents request dispatch',async()=>{let calls=0;const c=h.createClient({scope:s,key:'offline',event:()=>{throw Error('disk_failure');},delegate:async()=>calls++});await assert.rejects(c.request('roles'),/disk_failure/);assert.equal(calls,0);});
test('lock exclusivity and ownership protection',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'six-preflight-')),file=path.join(dir,'lock'),lock=h.acquireLock(file);assert.throws(()=>h.acquireLock(file),/EEXIST/);lock.check();lock.release();assert(!fs.existsSync(file));fs.rmdirSync(dir);});
test('default CLI offline; no arbitrary output or mutationmode',()=>{assert.equal(h.cli([]),'check');assert.equal(h.cli(['--check']),'check');assert.equal(h.cli(['--run']),'run');for(const args of[['--apply'],['--run','arbitrary'],['--preview']])assert.throws(()=>h.cli(args),/invalid_cli/);});
test('cooldown oversleep past the run deadline cannot dispatch',async()=>{let time=0,calls=0;const c=h.createClient({scope:s,key:'offline',now:()=>time,wait:async()=>{time=h.MAX_ELAPSED_MS+1;},delegate:async()=>{calls++;return new Response('[]',{headers:{'content-type':'application/json','content-range':'*/*'}});}});await c.request('roles');await assert.rejects(c.request('roles'),/transport_stopped_or_time_bound/);assert.equal(calls,1);});
test('same-origin changed response URL is rejected',async()=>{const f=fixture();f.setFault(()=>({redirected:false,url:h.ORIGIN+'/rest/v1/other'}));await assert.rejects(f.client.request('owners'),/response_origin_redirect/);assert.equal(f.calls.length,1);});
