'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const h=require('./profile-five-source-preflight.cjs'),scope=h.loadScope(),clone=x=>structuredClone(x);
// No fixture is allowed to contact a service or start a child process.
globalThis.fetch=async()=>{throw Error('LIVE_NETWORK_FORBIDDEN');};
for(const name of ['node:http','node:https']){const m=require(name);m.request=m.get=()=>{throw Error('LIVE_NETWORK_FORBIDDEN');};}
for(const key of ['exec','execSync','spawn','spawnSync','execFile','execFileSync','fork'])require('node:child_process')[key]=()=>{throw Error('PROCESS_FORBIDDEN');};
const sort=(rows,kind)=>clone(rows).sort((a,b)=>{const k=r=>kind==='roles'?r.entity_id+'\n'+r.role:r.id;return k(a)<k(b)?-1:k(a)>k(b)?1:0;});
function fixtures(){const out={};for(const kind of ['entities','roles','locations','ownerSources'])out[kind]=sort(scope.baseline[kind],kind);out.sourceKeys=sort(out.ownerSources,'sourceKeys');out.canonical=[];out.entityConflicts=sort(out.entities,'entityConflicts');out.locationConflicts=sort(out.locations.filter(r=>scope.addresses.includes(r.address1)),'locationConflicts');return out;}
function response(url,rows,{status=200,range,contentType='application/json',raw}={}){const r=new Response(raw===undefined?JSON.stringify(rows):raw,{status,headers:{'content-type':contentType,'content-range':range||(!rows?.length?'*/*':'0-'+(rows.length-1)+'/*')}});Object.defineProperty(r,'url',{value:url});return r;}
function readerHarness(options={}){let clock=0;const calls=[],events=[],data=fixtures();const reader=h.createReader({scope,key:'fixture-key',now:()=>clock,wait:async ms=>{clock+=ms;},event:e=>events.push(e),delegate:async(request,init)=>{calls.push({url:request.url,method:request.method,started:clock,init});const d=h.KINDS.find(k=>h.descriptor(k,scope).url===request.url);const offset=Number(new URL(request.url).searchParams.get('offset')||0);return response(request.url,offset?[]:data[d]);},...options});return{reader,calls,events,data,get clock(){return clock;},advance(ms){clock+=ms;}};}
test('frozen offline pins and exact five target/two competitor scope',()=>{assert.equal(scope.targets.length,5);assert.equal(scope.owners.length,7);assert.deepEqual(scope.competitors,h.COMPETITORS);assert.equal(scope.sourceKeys.length,17);assert.equal(scope.baseline.locations.length,9);assert.equal(scope.baseline.ownerSources.length,12);assert.ok(scope.websites.includes('https://experiencethepeacock.com/'));assert.ok(scope.websites.includes('http://meanmugcoffee.com/'));});
test('Macy bakery and Mammoth merchant evidence keys remain globally checked',()=>{assert.ok(scope.sourceKeys.some(k=>k.source_id==='roaster:macys-european-coffeehouse-bakery'));assert.ok(scope.sourceKeys.some(k=>k.source_id==='roaster:public-catalog:mammothcoffee.co'));assert.ok(scope.sourceKeys.some(k=>k.source_id==='osm:node/11386068869'));});
test('default/check CLI is offline; no apply or arbitrary output/IDs',()=>{assert.equal(h.cli([]),'--check');assert.equal(h.cli(['--check']),'--check');assert.equal(h.cli(['--read']),'--read');for(const args of [['--apply'],['--read','x'],['--url','https://elsewhere']])assert.throws(()=>h.cli(args),/invalid_cli/);});
test('descriptors only exact GET selectors; no broad pattern, HEAD, RPC, or count',()=>{for(const kind of h.KINDS){const d=h.descriptor(kind,scope),u=new URL(d.url);assert.equal(d.method,'GET');assert.equal(u.origin,h.ORIGIN);assert.equal(u.searchParams.get('select'),'*');assert.equal(u.searchParams.get('limit'),'101');assert.ok(!/ilike|like|rpc|count=|\*/.test(u.searchParams.get('or')||''));assert.ok(['id','entity_id','address1','or'].some(k=>u.searchParams.has(k)));}assert.throws(()=>h.descriptor('products',scope));assert.throws(()=>h.descriptor('entities',scope,101));assert.throws(()=>h.descriptor('entities',scope,-1));});
test('global source keys include five exact proposed vacancies without owner filter',()=>{const u=new URL(h.descriptor('sourceKeys',scope).url);assert.equal(u.searchParams.has('entity_id'),false);for(const key of h.SOURCE_IDS)assert.ok(u.searchParams.get('or').includes(key));});
test('canonical forward and inbound closure includes all seven identities',()=>{const u=new URL(h.descriptor('canonical',scope).url);assert.equal(u.searchParams.get('attribute_key'),'eq.canonical_roaster_entity_id');assert.ok(u.searchParams.get('or').includes('entity_id.in.'));assert.ok(u.searchParams.get('or').includes('attribute_value.in.'));for(const id of scope.owners)assert.equal(u.searchParams.get('or').split(id).length-1,2);});
test('all fresh full rows preserved; known Mean Mug hold survives complete capture',async()=>{const x=readerHarness();const r=await h.capture({scope,reader:x.reader});assert.equal(r.captureComplete,true);assert.equal(r.status,'read_only_exact_target_evidence_complete_with_holds');assert.equal(r.requests,15);assert.equal(r.writes,0);assert.equal(r.identityApproved,false);assert.equal(r.mutation_authorized,false);assert.equal(r.full_catalog_current,false);assert.deepEqual(r.holds[0].competitor_ids,h.COMPETITORS);assert.equal(r.state.entities.length,7);assert.ok(x.calls.every(c=>c.method==='GET'&&c.init.redirect==='error'));assert.ok(x.calls.slice(1).every((c,i)=>c.started-x.calls[i].started>=500));});
test('reported entities may carry additional fields but historical projection cannot drift',()=>{const d=fixtures();d.entities[0].description_raw='fresh full field retained';h.validate('entities',d.entities,scope);d.entities[0].website_url='https://different.invalid';assert.throws(()=>h.validate('entities',d.entities,scope),/baseline_drift/);});
for(const kind of ['entities','roles','locations','ownerSources'])test(kind+' missing row/field or duplicate fails',()=>{const d=fixtures();assert.throws(()=>h.validate(kind,d[kind].slice(1),scope),/baseline_count/);const bad=clone(d[kind]);delete bad[0][kind==='roles'?'role':kind==='entities'?'name':kind==='locations'?'address1':'source_url'];assert.throws(()=>h.validate(kind,bad,scope));assert.throws(()=>h.validate(kind,[d[kind][0],...d[kind]],scope),/duplicate_or_unordered/);});
test('existing proposed profile key is not silently idempotently approved',()=>{const d=fixtures();d.sourceKeys.push({id:'ffffffff-ffff-ffff-ffff-ffffffffffff',entity_id:h.IDS[0],source:'my_coffee_explorer',source_id:h.SOURCE_IDS[0]});assert.throws(()=>h.validate('sourceKeys',sort(d.sourceKeys,'sourceKeys'),scope,d),/source_key_vacancy_or_conflict/);});
test('corroborating source reparent or metadata change fails full fresh consistency',()=>{for(const field of ['entity_id','raw_data']){const d=fixtures();d.sourceKeys[0][field]='changed';assert.throws(()=>h.validate('sourceKeys',d.sourceKeys,scope,d),/source_owner_or_row_drift/);}});
test('outbound/inbound canonical links hold without graph expansion',()=>{for(const r of [{id:'a',entity_id:h.IDS[0],attribute_value:'other'},{id:'a',entity_id:'other',attribute_value:h.IDS[0]}])assert.throws(()=>h.validate('canonical',[r],scope),/canonical_closure_requires_review/);});
test('new exact-name/website competitor fails; known two remain held not approved',()=>{const d=fixtures();d.entityConflicts.push({id:'ffffffff-ffff-ffff-ffff-ffffffffffff',name:'Mean Mug Coffeehouse'});assert.throws(()=>h.validate('entityConflicts',sort(d.entityConflicts,'entities'),scope,d),/exact_identity_competitor/);});
test('new same-address owner fails without branch assumptions',()=>{const d=fixtures();d.locationConflicts.push({id:'ffffffff-ffff-ffff-ffff-ffffffffffff',entity_id:'foreign',address1:scope.addresses[0]});assert.throws(()=>h.validate('locationConflicts',sort(d.locationConflicts,'locations'),scope,d),/exact_location_competitor/);});
test('fresh entity/locations changing between repeated group reads hold',()=>{for(const k of ['entityConflicts','locationConflicts']){const d=fixtures();d[k][0].fresh_extra='changed';assert.throws(()=>h.validate(k,d[k],scope,d),/changed_during_reads/);}});
test('short server cap does not imply complete; explicit nonempty EOF holds',async()=>{let n=0;const reader={requests:0,async request(){this.requests++;return n++===0?fixtures().entities.slice(0,1):fixtures().entities.slice(1,2);}};await assert.rejects(h.capture({scope,reader}),/nonempty_continuation/);assert.equal(reader.requests,2);});
test('first semantic failure stops all later groups',async()=>{let n=0;const reader={requests:0,async request(){this.requests++;n++;return[];}};await assert.rejects(h.capture({scope,reader}),/baseline_count/);assert.equal(n,1);});
test('101-row cap fails rather than truncating',async()=>{const x=readerHarness({delegate:async r=>response(r.url,Array.from({length:101},()=>({})))});await assert.rejects(x.reader.request('entities'),/row_bound/);});
test('missing/numeric-incomplete/incorrect content ranges fail',async()=>{for(const range of ['bad','1-1/*','0-0/2']){const x=readerHarness({delegate:async r=>response(r.url,[{}],{range})});await assert.rejects(x.reader.request('entities'),/content_range|reported_total_incomplete/);}});
test('JSON null/object and non-JSON media type are rejected',async()=>{for(const opts of [{raw:'null'},{raw:'{}'},{contentType:'text/html'}]){const x=readerHarness({delegate:async r=>response(r.url,[],opts)});await assert.rejects(x.reader.request('entities'),/row_bound|content_type/);}});
test('same-origin changed, empty, and foreign response URLs fail',async()=>{for(const wrong of ['',h.ORIGIN+'/rest/v1/other','https://elsewhere.invalid/']){const x=readerHarness({delegate:async()=>response(wrong,[])});await assert.rejects(x.reader.request('entities'),/exact_response_url/);}});
test('HTTP failure has no retry and latches later reads',async()=>{let calls=0;const x=readerHarness({delegate:async r=>{calls++;return response(r.url,null,{status:500,raw:'{"code":"57014"}'});}});await assert.rejects(x.reader.request('entities'),e=>e.httpStatus===500&&e.dbCode==='57014');await assert.rejects(x.reader.request('roles'),/reader_stopped_or_bound/);assert.equal(calls,1);});
test('missing required tables are errors, never optional success',async()=>{const x=readerHarness({delegate:async r=>response(r.url,null,{status:404,raw:'{"code":"PGRST205"}'})});await assert.rejects(x.reader.request('canonical'),e=>e.httpStatus===404);});
test('redirect and timeout fail without a second dispatch',async()=>{const x=readerHarness({delegate:async r=>response(r.url,[],{status:302})});await assert.rejects(x.reader.request('entities'),/database_redirect_forbidden/);let count=0;const y=readerHarness({timeoutMs:5,delegate:()=>{count++;return new Promise(()=>{});}});await assert.rejects(y.reader.request('entities'),/database_request_timeout_or_abort/);await assert.rejects(y.reader.request('roles'));assert.equal(count,1);});
test('body size is bounded before JSON parsing',async()=>{const x=readerHarness({delegate:async r=>response(r.url,[],{raw:'x'.repeat(h.MAX_BODY+1)})});await assert.rejects(x.reader.request('entities'),/database_response_too_large/);});
test('slow body completion and early waking sleeps retain full 500ms spacing',async()=>{let clock=0,completed=0,dispatch=[];const x=h.createReader({scope,key:'fixture',now:()=>clock,wait:async ms=>{clock+=Math.max(1,ms-1);},delegate:async r=>{dispatch.push(clock);clock+=700;completed=clock;return response(r.url,[]);}});await x.request('canonical');const firstDone=completed;await x.request('canonical');assert.ok(dispatch[1]-firstDone>=500);});
test('global deadline during cooldown prevents dispatch',async()=>{let clock=0,calls=0;const x=h.createReader({scope,key:'fixture',now:()=>clock,wait:async()=>{clock+=h.MAX_MS;},delegate:async r=>{calls++;return response(r.url,[]);}});await x.request('canonical');await assert.rejects(x.request('canonical'),/dispatch_deadline/);assert.equal(calls,1);});
test('lock loss during pacing prevents dispatch',async()=>{let clock=0,locked=true,calls=0;const x=h.createReader({scope,key:'fixture',now:()=>clock,wait:async ms=>{clock+=ms;locked=false;},checkLock:()=>assert.ok(locked,'lost lock'),delegate:async r=>{calls++;return response(r.url,[]);}});await x.request('canonical');await assert.rejects(x.request('canonical'),/lost lock/);assert.equal(calls,1);});
test('concurrent attempt stops both readers and emits no second request',async()=>{let release,count=0;const x=readerHarness({delegate:r=>{count++;return new Promise(resolve=>{release=()=>resolve(response(r.url,[]));});}});const pending=x.reader.request('canonical');await new Promise(setImmediate);await assert.rejects(x.reader.request('canonical'),/reader_stopped_or_bound/);release();await assert.rejects(pending,/reader_stopped_or_bound/);assert.equal(count,1);});
test('journal error before request prevents dispatch',async()=>{let calls=0;const x=readerHarness({event:()=>{throw Error('disk failed');},delegate:async r=>{calls++;return response(r.url,[]);}});await assert.rejects(x.reader.request('entities'),/disk failed/);assert.equal(calls,0);});
test('16 request bound cannot be exceeded',async()=>{const x=readerHarness();for(let n=0;n<h.MAX_REQUESTS;n++)await x.reader.request('canonical');await assert.rejects(x.reader.request('canonical'),/reader_stopped_or_bound/);assert.equal(x.calls.length,h.MAX_REQUESTS);});
test('immutable fsynced receipt refuses overwrite',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'profile-five-fixture-')),file=path.join(dir,'result.json');h.save(file,{readOnly:true});assert.deepEqual(JSON.parse(fs.readFileSync(file)),{readOnly:true});assert.throws(()=>h.save(file,{}),/EEXIST/);fs.unlinkSync(file);fs.rmdirSync(dir);});
