'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const m=require('./reconcile-original-two-failed-claims.cjs');
const NOW=Date.parse('2026-09-27T21:00:00.000Z');
function row(i){const t=m.TARGETS[i];return{id:t.id,entity_id:t.entity_id,status:'running',started_at:t.started_at.replace('Z','+00:00'),finished_at:null,created_at:t.started_at.replace('Z','+00:00'),platform:'custom',pages_discovered:0,pages_visited:0,pages_sent_to_gpt:0,coffees_found:0,error:null,meta:{}};}
function preview(rows=[row(0),row(1)]){return{at:new Date(NOW-1000).toISOString(),status:'preview_complete',helper_sha256:m.helperSha(),evidence_pins:m.PINS,before:rows,requests:1,writes:0};}
function response(url,rows,status=200,headers={}){const r=new Response(JSON.stringify(rows),{status,headers:{'content-type':'application/json','content-range':rows.length?`0-${rows.length-1}/${rows.length}`:'*/0',...headers}});Object.defineProperty(r,'url',{value:url});return r;}
function fixture({mode='apply',mutate,failAt,changedURL=false,earlyWake=false,timeoutMs=20000}={}){
 let time=NOW,count=0;const rows=[row(0),row(1)],calls=[],events=[];const client=m.createClient({mode,key:'not-a-real-credential',now:()=>time,wait:async ms=>{time+=earlyWake&&ms>1?ms-1:ms;},timeoutMs,event:e=>events.push(e),delegate:async(req,opts)=>{
  const body=req.method==='PATCH'?await req.json():null;calls.push({url:req.url,method:req.method,body,at:time,redirect:opts.redirect});count++;if(count===failAt)throw Error('simulated offline outage');
  const q=new URL(req.url).searchParams,id=q.get('id')?.slice(3);let result=id?rows.filter(r=>r.id===id):rows.slice();if(mutate)result=mutate({count,rows,result,req,body})??result;if(body){for(const r of result)Object.assign(r,body,{finished_at:body.finished_at.replace('Z','+00:00')});}
  time+=7;return response(changedURL?req.url+'&changed=1':req.url,result);
 }});return{client,rows,calls,events,now:()=>time};
}
test('literal provenance pins and offline default validate without HTTP',()=>{const old=global.fetch;global.fetch=()=>{throw Error('no HTTP')};try{assert.equal(m.loadEvidence().targets.length,2);assert.deepEqual(m.cli([]),{mode:'check'});}finally{global.fetch=old;}});
test('fixed targets bind both exact IDs and owners in read filter',()=>{const d=m.descriptor('all'),q=new URL(d.url).searchParams;assert.equal(d.method,'GET');assert.equal(q.get('select'),'*');assert.equal(q.get('limit'),'3');for(const t of m.TARGETS){assert(q.get('or').includes(`and(id.eq.${t.id},entity_id.eq.${t.entity_id})`));}assert.equal(new URL(d.url).origin,m.ORIGIN);});
for(const change of [{entity_id:m.TARGETS[1].entity_id},{id:m.TARGETS[1].id},{status:'completed'},{finished_at:'2026-09-27T20:00:00Z'},{started_at:'2026-09-27T00:52:50.159Z'}])test('initial identity/status drift refuses '+Object.keys(change)[0],()=>assert.throws(()=>m.validateRow({...row(0),...change},m.TARGETS[0])));
test('full-row schema rejects unknown or absent columns',()=>{assert.throws(()=>m.validateRow({...row(0),new_field:true},m.TARGETS[0]),/row_schema/);const r=row(0);delete r.meta;assert.throws(()=>m.validateRow(r,m.TARGETS[0]),/row_schema/);});
test('duplicate or missing exact claims refuse',()=>{assert.throws(()=>m.validateSet([row(0)]));assert.throws(()=>m.validateSet([row(0),row(0)]));});
test('patch changes three fields only, preserves existing error and cites original terminal attempt',()=>{const b={...row(0),error:'original evidence'},p=m.patchFor(b,m.TARGETS[0],new Date(NOW).toISOString());assert.deepEqual(Object.keys(p).sort(),['error','finished_at','status']);assert.equal(p.status,'failed');assert(p.error.startsWith('original evidence\n'));assert(p.error.includes(m.TARGETS[0].attempt_finished_at));assert(p.error.includes('reconciliation time, not original completion'));});
test('all thirteen before fields are CAS filters; no other claim scope',()=>{const b=row(0),p=m.patchFor(b,m.TARGETS[0],new Date(NOW).toISOString()),d=m.descriptor('patch',0,b,p),q=new URL(d.url).searchParams;for(const k of m.FIELDS)assert(q.has(k));assert.equal(q.get('status'),'eq.running');assert.equal(q.get('finished_at'),'is.null');assert.equal(q.get('meta'),'eq.{}');assert.equal(q.get('id'),'eq.'+b.id);assert(!q.has('or'));assert.equal(d.method,'PATCH');assert.throws(()=>m.descriptor('patch',2,b,p));assert.throws(()=>m.descriptor('patch',0,b,{...p,meta:{}}));});
test('preview TTL, helper hash, evidence and writes are enforced',()=>{m.validatePreview(preview(),NOW);for(const p of [{...preview(),at:new Date(NOW-m.TTL).toISOString()},{...preview(),at:new Date(NOW+1).toISOString()},{...preview(),helper_sha256:'0'.repeat(64)},{...preview(),evidence_pins:{}},{...preview(),writes:1}])assert.throws(()=>m.validatePreview(p,NOW));});
test('preview makes exactly one bounded GET and zero mutations',async()=>{const f=fixture({mode:'preview'}),r=await m.execute({client:f.client,mode:'preview',now:f.now});assert.equal(r.writes,0);assert.equal(r.requests,1);assert.equal(f.calls.length,1);assert.equal(f.calls[0].method,'GET');});
test('apply makes six serial requests/two PATCHes and verifies unchanged counters/metadata',async()=>{const f=fixture(),r=await m.execute({client:f.client,mode:'apply',preview:preview(),now:f.now});assert.equal(r.writes,2);assert.equal(r.requests,6);assert.deepEqual(f.calls.map(c=>c.method),['GET','GET','PATCH','GET','PATCH','GET']);assert(r.counters_meta_owner_and_start_preserved);for(let i=0;i<2;i++)m.verifyPreserved(r.after.find(x=>x.id===m.TARGETS[i].id),r.before[i],r.patches[i]);});
test('early timer wake still waits at least500ms after full response completion',async()=>{const f=fixture({earlyWake:true});await m.execute({client:f.client,mode:'apply',preview:preview(),now:f.now});for(let i=1;i<f.calls.length;i++)assert(f.calls[i].at-f.calls[i-1].at-7>=500);});
test('same-origin changed response URL is forbidden before any mutation',async()=>{const f=fixture({changedURL:true});await assert.rejects(m.execute({client:f.client,mode:'apply',preview:preview(),now:f.now}),/exact_response_url/);assert.equal(f.calls.length,1);});
test('initial full-row drift from reviewed preview prevents writes',async()=>{const f=fixture({mutate:({count,result})=>{if(count===1)result[0].meta={updated:true};}});await assert.rejects(m.execute({client:f.client,mode:'apply',preview:preview(),now:f.now}),/preview_row_drift/);assert.equal(f.calls.length,1);});
test('fresh per-write row drift prevents that PATCH and all later requests',async()=>{const f=fixture({mutate:({count,result})=>{if(count===2)result[0].pages_visited=1;}});await assert.rejects(m.execute({client:f.client,mode:'apply',preview:preview(),now:f.now}),/prewrite_row_drift/);assert.deepEqual(f.calls.map(c=>c.method),['GET','GET']);});
test('zero-row CAS result stops before second claim',async()=>{const f=fixture({mutate:({count})=>count===3?[]:undefined});await assert.rejects(m.execute({client:f.client,mode:'apply',preview:preview(),now:f.now}),/patch_not_exact_one/);assert.equal(f.calls.length,3);});
test('ambiguous PATCH transport failure is never replayed',async()=>{const f=fixture({failAt:3});await assert.rejects(m.execute({client:f.client,mode:'apply',preview:preview(),now:f.now}),/offline outage/);await assert.rejects(f.client.request('all'));assert.equal(f.calls.length,3);assert.equal(f.calls.filter(x=>x.method==='PATCH').length,1);});
test('returned metadata mutation fails full-row preservation',async()=>{const f=fixture({mutate:({count,result})=>{if(count===3)result[0].meta={unexpected:true};}});await assert.rejects(m.execute({client:f.client,mode:'apply',preview:preview(),now:f.now}),/changed_field:meta/);assert.equal(f.calls.length,3);});
test('final readback catches lost preservation',async()=>{const f=fixture({mutate:({count,result})=>{if(count===6)result[0].coffees_found=12;}});await assert.rejects(m.execute({client:f.client,mode:'apply',preview:preview(),now:f.now}),/changed_field:coffees_found/);assert.equal(f.calls.length,6);});
test('preview mode cannot issue PATCH',async()=>{const f=fixture({mode:'preview'}),b=row(0),p=m.patchFor(b,m.TARGETS[0],new Date(NOW).toISOString());await assert.rejects(f.client.request('patch',0,b,p));assert.equal(f.calls.length,0);});
test('bounded Content-Range mismatch is not mistaken for complete read',async()=>{const c=m.createClient({mode:'preview',key:'fake',delegate:async r=>response(r.url,[row(0),row(1)],200,{'content-range':'0-1/3'})});await assert.rejects(c.request('all'),/incomplete_read/);});
test('response cap rejects third row',async()=>{const c=m.createClient({mode:'preview',key:'fake',delegate:async r=>response(r.url,[row(0),row(1),row(0)])});await assert.rejects(c.request('all'),/row_cap/);});
test('503 stops gate without retry',async()=>{let n=0;const c=m.createClient({mode:'preview',key:'fake',delegate:async r=>{n++;return response(r.url,[],503);}});await assert.rejects(c.request('all'));await assert.rejects(c.request('all'));assert.equal(n,1);});
test('20-second-class timeout covers an uncooperative delegate without retry',async()=>{let n=0;const c=m.createClient({mode:'preview',key:'fake',timeoutMs:10,delegate:async()=>{n++;return new Promise(()=>{});}});await assert.rejects(c.request('all'),/timeout_or_abort/);assert.equal(n,1);});
test('intent journal failure prevents dispatch',async()=>{let n=0;const c=m.createClient({mode:'preview',key:'fake',event:()=>{throw Error('disk failure')},delegate:async()=>{n++;}});await assert.rejects(c.request('all'));assert.equal(n,0);});
test('request evidence never includes credential headers',async()=>{const f=fixture({mode:'preview'});await f.client.request('all');const j=JSON.stringify(f.events);assert(!j.includes('not-a-real-credential'));assert(!j.includes('Authorization'));assert(!j.includes('apikey'));});
test('dispatch-time authorization is rechecked after cooldown',async()=>{let n=0,checks=0;const c=m.createClient({mode:'apply',key:'fake',beforeWrite:()=>{if(++checks===2)throw Error('authorization expired')},delegate:async r=>{n++;return response(r.url,[]);}});const b=row(0),p=m.patchFor(b,m.TARGETS[0],new Date(NOW).toISOString());await assert.rejects(c.request('patch',0,b,p),/authorization expired/);assert.equal(n,0);});
test('exclusive output and lock cannot overwrite or seize existing work',()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'exact-two-claims-test-'));try{const f=path.join(d,'result.json');m.save(f,{one:true});assert.throws(()=>m.save(f,{two:true}),/EEXIST/);assert.deepEqual(JSON.parse(fs.readFileSync(f)),{one:true});const l=path.join(d,'apply.lock'),lock=m.acquireLock(l);assert.throws(()=>m.acquireLock(l),/EEXIST/);lock.check();lock.release();assert(!fs.existsSync(l));}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('CLI requires exact confirmation and hash, never arbitrary modes',()=>{assert.deepEqual(m.cli(['--preview']),{mode:'preview'});assert.equal(m.cli(['--apply','/x/result.json','a'.repeat(64),'--confirm-two-failed-claims']).mode,'apply');for(const a of [['--run'],['--apply'],['--apply','x','a'.repeat(64),'--yes']])assert.throws(()=>m.cli(a));});
