'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),h=require('./reconcile-blommers-historical-claims.cjs'),p=h.loadPlan(),clone=h.copy;
const AT='2026-09-27T17:50:00.000Z';
function response(url,rows,status=200){const r=new Response(JSON.stringify(rows),{status,headers:{'content-type':'application/json','content-range':rows.length?'0-'+(rows.length-1)+'/'+rows.length:'*/0'}});Object.defineProperty(r,'url',{value:url});return r;}
function runtime(time){return{at:new Date(time).toISOString(),launchers:[{pid:93940,started_at:'2026-09-27T13:13:32Z'}],nodes:[{pid:93949,started_at:'2026-09-27T13:13:32Z'}],lock_pid:93940,current_log:{bytes:262144,modified_at:new Date(time).toISOString(),owner_or_claim_match:false}};}
function fixture(){let time=Date.parse(AT),hook=null,currentPreview;const state={owner:clone(p.owner),rows:clone(p.expected),other:[]},calls=[],events=[],dispatches=[];const f={state,calls,events,dispatches,now:()=>time,advance:n=>time+=n,setHook:v=>hook=v,proof:()=>h.verifyRuntime(runtime(time),p,time)};
 f.client=(mode='preview',extra={})=>h.createClient({plan:p,key:'fixture-not-secret',mode,now:()=>time,wait:async ms=>time+=ms,event:e=>events.push(e),beforeDispatch:d=>{if(mode==='apply')h.validatePreview(currentPreview,p,time);dispatches.push({time,kind:d.kind,index:d.index});f.proof();},delegate:async(url,req)=>{const call={url,method:req.method,body:req.body&&JSON.parse(req.body),start:time};calls.push(call);time+=50;const q=new URL(url).searchParams;if(hook){const x=await hook({url,req,q,state,calls,call});if(x)return x;}let rows;
 if(req.method==='PATCH'){const id=q.get('id').slice(3),row=state.rows.find(r=>r.id===id);const matches=row&&[...q].filter(([k])=>k!=='select').every(([k,v])=>v==='is.null'?row[k]===null:v==='eq.'+(typeof row[k]==='object'?JSON.stringify(row[k]):String(row[k])));rows=matches?[Object.assign(row,JSON.parse(req.body))]:[];}
 else{assert.equal(req.method,'GET');rows=new URL(url).pathname.endsWith('/entities')?[state.owner]:q.has('status')?[...state.rows.filter(r=>r.status==='running'),...state.other].sort((a,b)=>a.id.localeCompare(b.id)):state.rows;}
 call.complete=time;return response(url,clone(rows));},...extra});
 f.preview=async extra=>{currentPreview=await h.execute({plan:p,client:f.client('preview',extra),mode:'preview',proof:f.proof,now:f.now,record:e=>events.push(e)});return currentPreview;};f.apply=async(v=currentPreview,extra={},execution={})=>h.execute({plan:p,client:f.client('apply',extra),mode:'apply',preview:v,proof:f.proof,now:f.now,record:e=>events.push(e),...execution});return f;}
test('exact43 original rows/source pins loaded, not synthetic IDs',()=>{assert.equal(p.expected.length,43);assert.equal(new Set(p.claim_ids).size,43);assert.equal(p.expected.at(-1).id,p.claim_ids.at(-1));assert.equal(p.pins['blommers-running-claims-inventory-1729.json'],'76d9df18efd27a68b93d53bdae306b0dd978ccaae874349deab17ee07cac8d4b');});
test('plan rejects extra/missing/schema/foreign/success rows',()=>{for(const change of [q=>q.expected.pop(),q=>q.expected[0].unexpected=true,q=>q.expected[0].entity_id='other',q=>q.expected[0].status='completed',q=>q.expected[0].pages_visited=1,q=>q.expected[0].meta={x:1},q=>q.claim_ids.reverse()]){const q=clone(p);change(q);assert.throws(()=>h.validatePlan(q));}});
test('all13 captured columns are exact CAS predicates including JSON/null',()=>{for(let i=0;i<43;i++){const d=h.descriptor('patch',p,i,h.patchFor(p,i,AT)),q=new URL(d.url).searchParams;assert.equal(new URL(d.url).origin,h.ORIGIN);assert.equal(new URL(d.url).pathname,'/rest/v1/crawl_runs');assert.equal(d.method,'PATCH');for(const[k,v]of Object.entries(p.expected[i]))assert.equal(q.get(k),v===null?'is.null':'eq.'+(typeof v==='object'?JSON.stringify(v):String(v)));assert.deepEqual(Object.keys(d.body),['status','finished_at','error']);}});
test('honest reconciliation only, no historical cause inferred',()=>{const b=h.patchFor(p,0,AT);assert.equal(b.finished_at,AT);assert.equal(b.status,'failed');assert.match(b.error,/original finish time and cause unknown; no success inferred; counters preserved\.$/);assert.doesNotMatch(b.error,/timeout|KnownPages|completed/);for(const t of ['bad','2000-01-01T00:00:00.000Z'])assert.throws(()=>h.patchFor(p,0,t));});
test('other mutation kinds/fields/index/owner forbidden',()=>{for(const kind of ['delete','insert','rpc','products'])assert.throws(()=>h.descriptor(kind,p));for(const index of [-1,43,0.5])assert.throws(()=>h.descriptor('patch',p,index,{}));for(const extra of [{meta:{}},{pages_visited:1},{status:'completed'},{entity_id:'other'}])assert.throws(()=>h.descriptor('patch',p,0,{...h.patchFor(p,0,AT),...extra}));});
test('full all-ID/owner active reads exact scopes and bounded44',()=>{for(const kind of ['all','active']){const q=new URL(h.descriptor(kind,p).url).searchParams;assert.equal(q.get('entity_id'),'eq.'+h.OWNER);assert.equal(q.get('limit'),'44');assert.equal(q.get('order'),'id.asc');if(kind==='all')assert.equal(q.get('id'),'in.('+p.claim_ids.join(',')+')');else assert.equal(q.get('status'),'eq.running');}});
test('default offline and explicit confirmation/review required',()=>{assert.equal(h.cli([]).mode,'check');assert.equal(h.cli(['--check']).mode,'check');for(const x of [['--preview'],['--run'],['--apply'],['--preview','--review-sha','bad'],['--apply','p','a'.repeat(64),'--review-sha','b'.repeat(64),'--yes']])assert.throws(()=>h.cli(x));assert.equal(h.cli(['--preview','--review-sha','a'.repeat(64)]).mode,'preview');assert.equal(h.cli(['--apply','p','a'.repeat(64),'--review-sha','b'.repeat(64),'--confirm-reconcile-exact-43-blommers-claims']).mode,'apply');});
test('independent exact helper and plan hashes needed',()=>{const r={status:'PASS',independent:true,helper_sha256:h.helperSha(),plan_sha256:h.PLAN_SHA};h.validateReview(r);for(const delta of [{status:'PASS_CODE_ONLY'},{independent:false},{helper_sha256:'x'},{plan_sha256:'x'}])assert.throws(()=>h.validateReview({...r,...delta}));});
test('preview3GET no writes and full rows retained',async()=>{const f=fixture(),r=await f.preview();assert.equal(r.requests,3);assert.equal(r.writes,0);assert.deepEqual(r.before,p.expected);assert(f.calls.every(c=>c.method==='GET'));assert.equal(f.dispatches.length,3);});
test('apply91 requests43PATCH and final complete readback',async()=>{const f=fixture(),v=await f.preview();f.calls.length=0;f.dispatches.length=0;const r=await f.apply(v);assert.equal(r.requests,91);assert.equal(r.writes,43);assert.equal(f.calls.filter(c=>c.method==='PATCH').length,43);assert.equal(f.dispatches.length,91);assert.equal(r.after.length,43);assert.equal(r.original_finish_and_causes_unknown,true);for(let i=0;i<43;i++)for(const[k,val]of Object.entries(p.expected[i]))if(!['status','finished_at','error'].includes(k))assert.deepEqual(r.after[i][k],val);for(let i=1;i<f.calls.length;i++)assert(f.calls[i].start-f.calls[i-1].complete>=500);});
for(const [label,change]of [['owner drift',f=>f.state.owner.name='Other'],['missing row',f=>f.state.rows.pop()],['counter drift',f=>f.state.rows[3].pages_visited=1],['metadata drift',f=>f.state.rows[8].meta={new:true}],['nonmanifest claim',f=>f.state.other.push({...p.expected[0],id:'ffffffff-ffff-ffff-ffff-ffffffffffff'})],['already failed',f=>f.state.rows[5].status='failed']])test(label+' stops before mutation',async()=>{const f=fixture();change(f);await assert.rejects(f.preview());assert.equal(f.calls.filter(c=>c.method==='PATCH').length,0);});
test('new active owner claim between patches stops after preserved prefix',async()=>{const f=fixture();await f.preview();await assert.rejects(f.apply(undefined,{}, {record:e=>{if(e.event==='mutation_returned_preserved'&&e.index===1)f.state.other.push({...p.expected[0],id:'ffffffff-ffff-ffff-ffff-ffffffffffff'});}}));assert.equal(f.calls.filter(c=>c.method==='PATCH').length,2);assert.equal(f.state.rows.filter(r=>r.status==='failed').length,2);});
test('remaining row counter changes stop before its patch',async()=>{const f=fixture();await f.preview();await assert.rejects(f.apply(undefined,{}, {record:e=>{if(e.event==='mutation_returned_preserved'&&e.index===1)f.state.rows[20].coffees_found=1;}}));assert.equal(f.calls.filter(c=>c.method==='PATCH').length,2);});
test('full CAS race zero-row response does not replay',async()=>{const f=fixture();await f.preview();await assert.rejects(f.apply(undefined,{}, {record:e=>{if(e.event==='mutation_attempt_no_retry')f.state.rows[e.index].meta={raced:true};}}),/exact_one_returned/);assert.equal(f.calls.filter(c=>c.method==='PATCH').length,1);});
test('failed response never retries and latches all queued work',async()=>{const f=fixture();f.setHook(({url,req})=>req.method==='PATCH'?response(url,{code:'57014'},500):null);const c=f.client('apply',{beforeDispatch:()=>{}});await assert.rejects(c.request('patch',0,h.patchFor(p,0,AT)));await assert.rejects(c.request('patch',0,h.patchFor(p,0,AT)));await assert.rejects(c.request('owner'));assert.equal(f.calls.length,1);});
test('successful PATCH index cannot replay within same client',async()=>{const f=fixture(),c=f.client('apply',{beforeDispatch:()=>{}});await c.request('patch',0,h.patchFor(p,0,AT));await assert.rejects(c.request('patch',0,h.patchFor(p,0,AT)));assert.equal(f.calls.length,1);});
test('preview cannot mutate',async()=>{const f=fixture(),c=f.client();await assert.rejects(c.request('patch',0,h.patchFor(p,0,AT)));assert.equal(f.calls.length,0);});
test('ten-minute/future/foreign preview refuses before requests',async()=>{const f=fixture(),v=await f.preview();for(const delta of [{at:'2000-01-01T00:00:00Z'},{at:'2100-01-01T00:00:00Z'},{helper_sha256:'x'},{plan_sha256:'x'},{before:[]}]){const n=f.calls.length;await assert.rejects(f.apply({...v,...delta}));assert.equal(f.calls.length,n);}});
test('returned drift/unexpected columns/wrong ID/missing rows rejected',()=>{const patch=h.patchFor(p,0,AT);for(const delta of [{meta:{x:1}},{pages_visited:1},{id:p.claim_ids[1]},{extra:true}])assert.throws(()=>h.verifyRow({...p.expected[0],...patch,...delta},p.expected[0],patch));assert.throws(()=>h.verifySet(p.expected.slice(1),p.expected));});
test('microsecond timestamp equality accepts +00:00 but not changed instant',()=>{const b=p.expected[0],patch=h.patchFor(p,0,AT),r={...b,...patch,finished_at:'2026-09-27T17:50:00+00:00'};h.verifyRow(r,b,patch);assert.throws(()=>h.verifyRow({...r,finished_at:'2026-09-27T17:50:00.000001Z'},b,patch));});
test('final readback catches drift in completed prefix',async()=>{const f=fixture();await f.preview();await assert.rejects(f.apply(undefined,{}, {record:e=>{if(e.event==='mutation_returned_preserved'&&e.index===42)f.state.rows[0].meta={late:true};}}),/row_drift/);assert.equal(f.calls.filter(c=>c.method==='PATCH').length,43);});
test('final new active owner claim prevents verified result',async()=>{const f=fixture();await f.preview();await assert.rejects(f.apply(undefined,{}, {record:e=>{if(e.event==='mutation_returned_preserved'&&e.index===42)f.state.other.push({...p.expected[0],id:'ffffffff-ffff-ffff-ffff-ffffffffffff'});}}),/new_owner_claim/);});
test('runtime after pacing before physical dispatch may refuse',async()=>{const f=fixture(),c=f.client('apply',{beforeDispatch:()=>{throw Error('current owner activity');}});await assert.rejects(c.request('patch',0,h.patchFor(p,0,AT)));assert.equal(f.calls.length,0);});
test('runtime source inspector remains separately pinned and untouched',()=>{assert.equal(p.pins['retire-blommers-historical-claim.cjs'],'c842d2cc41deb611f170906af777b6b97f4412a8d5da18b629c85f2e53872283');assert.equal(p.runtime_reference,'blommers-historical-claim-retirement-plan.json');});
for(const[label,change]of [['old worker',s=>s.nodes[0].started_at='2026-01-01T00:00:00Z'],['owner log',s=>s.current_log.owner_or_claim_match=true],['stale log',s=>s.current_log.modified_at='2026-09-27T17:00:00Z'],['stale proof',s=>s.at='2026-09-27T17:00:00Z'],['future proof',s=>s.at='2026-09-28T17:00:00Z']])test('runtime extension refuses '+label,()=>{const s=runtime(Date.parse(AT));change(s);assert.throws(()=>h.verifyRuntime(s,p,Date.parse(AT)));});
test('no-worker proof accepted only after inherited inspector validated absence',()=>{const s=runtime(Date.parse(AT));s.launchers=[];s.nodes=[];s.lock_pid=null;s.current_log=null;h.verifyRuntime(s,p,Date.parse(AT));});
for(const[label,make]of [['wrong response URL',u=>response(u+'x',[])],['bad MIME',u=>{const r=response(u,[]);r.headers.set('content-type','text/html');return r;}],['bad JSON',u=>{const r=new Response('notjson',{headers:{'content-type':'application/json'}});Object.defineProperty(r,'url',{value:u});return r;}],['unknown count',u=>{const r=response(u,[]);r.headers.set('content-range','*/*');return r;}],['truncated exact count',u=>{const r=response(u,[p.expected[0]]);r.headers.set('content-range','0-0/43');return r;}],['overflow',u=>response(u,Array(45).fill({}))],['HTTP429',u=>response(u,[],429)],['HTTP503',u=>response(u,[],503)]])test('transport fails closed '+label,async()=>{const f=fixture();f.setHook(({url})=>make(url));const c=f.client();await assert.rejects(c.request('all'));await assert.rejects(c.request('all'));assert.equal(f.calls.length,1);});
test('network failure stops without retry',async()=>{const f=fixture();f.setHook(()=>{throw Error('network');});const c=f.client();await assert.rejects(c.request('all'));await assert.rejects(c.request('all'));assert.equal(f.calls.length,1);});
test('full response body1MiB cap',async()=>{const f=fixture();f.setHook(({url})=>{const r=new Response(' '.repeat(h.MAX_BODY+1),{headers:{'content-type':'application/json'}});Object.defineProperty(r,'url',{value:url});return r;});await assert.rejects(f.client().request('all'),/body_bound/);});
test('500ms spacing is after consumed body, not header arrival',async()=>{let time=0,complete;const starts=[],c=h.createClient({plan:p,key:'x',mode:'preview',now:()=>time,wait:async n=>time+=n,delegate:async u=>{starts.push(time);const body=new ReadableStream({start(controller){time+=700;controller.enqueue(new TextEncoder().encode('[]'));time+=800;controller.close();complete=time;}});const r=new Response(body,{headers:{'content-type':'application/json','content-range':'*/0'}});Object.defineProperty(r,'url',{value:u});return r;}});await c.request('active');const end=complete;await c.request('active');assert(starts[1]-end>=500);});
test('early timer wake loops and overslept deadline prevents dispatch',async()=>{let time=0,n=0;const waits=[],c=h.createClient({plan:p,key:'x',mode:'preview',now:()=>time,wait:async ms=>{waits.push(ms);time+=ms===500?499:ms;},delegate:async u=>{n++;return response(u,[]);}});await c.request('active');await c.request('active');assert.deepEqual(waits,[500,1]);const d=h.createClient({plan:p,key:'x',mode:'preview',now:()=>time,wait:async()=>time+=h.MAX_TIME,delegate:async u=>{n++;return response(u,[]);}});await d.request('active');await assert.rejects(d.request('active'),/deadline/);assert.equal(n,3);});
test('runtime proof exceeding elapsed cap prevents dispatch',async()=>{let time=0,n=0;const c=h.createClient({plan:p,key:'x',mode:'preview',now:()=>time,beforeDispatch:()=>time=h.MAX_TIME,delegate:async u=>{n++;return response(u,[]);}});await assert.rejects(c.request('active'));assert.equal(n,0);});
test('request abort is capped by remaining global time and body deadline latches',async()=>{let time=0,n=0;const timers=[],c=h.createClient({plan:p,key:'x',mode:'preview',now:()=>time,setTimer:(fn,ms)=>{timers.push(ms);return 1;},clearTimer:()=>{},beforeDispatch:()=>{time=h.MAX_TIME-1234;},delegate:async u=>{n++;time=h.MAX_TIME;return response(u,[]);}});await assert.rejects(c.request('active'),/response_stopped_or_exceeded_global_deadline/);assert.deepEqual(timers,[1234]);await assert.rejects(c.request('active'));assert.equal(n,1);});
test('final91st response crossing total deadline cannot yield verified result',async()=>{const f=fixture();await f.preview();let n=0;f.setHook(()=>{if(++n===91)f.advance(h.MAX_TIME);});await assert.rejects(f.apply(),/response_stopped_or_exceeded_global_deadline/);assert.equal(f.calls.filter(c=>c.method==='PATCH').length,43);assert(!f.events.some(e=>e.event==='final_readback_verified'));});
test('20s abort remains active while consuming response body',async()=>{let abortNow;const timers=[],c=h.createClient({plan:p,key:'x',mode:'preview',setTimer:(fn,ms)=>{abortNow=fn;timers.push(ms);return 1;},clearTimer:()=>{},delegate:async(u,req)=>{const stream=new ReadableStream({start(controller){req.signal.addEventListener('abort',()=>controller.error(Error('body_aborted')),{once:true});queueMicrotask(()=>abortNow());}});const r=new Response(stream,{headers:{'content-type':'application/json','content-range':'*/0'}});Object.defineProperty(r,'url',{value:u});return r;}});await assert.rejects(c.request('active'),/body_aborted/);assert.deepEqual(timers,[20000]);await assert.rejects(c.request('active'));});
test('journal intent failure prevents mutation dispatch',async()=>{const f=fixture(),c=f.client('apply',{beforeDispatch:()=>{},event:()=>{throw Error('disk');}});await assert.rejects(c.request('patch',0,h.patchFor(p,0,AT)));assert.equal(f.calls.length,0);});
test('journal result failure stops after uncertain commit and no next claim',async()=>{const f=fixture();await f.preview();await assert.rejects(f.apply(undefined,{event:e=>{if(e.event==='request_result'&&e.kind==='patch')throw Error('disk');}}));assert.equal(f.calls.filter(c=>c.method==='PATCH').length,1);});
test('simultaneous request rejected, no second physical dispatch',async()=>{let resolve,n=0;const c=h.createClient({plan:p,key:'x',mode:'preview',delegate:async u=>{n++;await new Promise(r=>resolve=r);return response(u,[]);}});const one=c.request('active');await assert.rejects(c.request('active'));resolve();await assert.rejects(one);assert.equal(n,1);await assert.rejects(c.request('active'));});
test('request caps exactly3preview and91apply',async()=>{for(const[mode,max]of [['preview',3],['apply',91]]){const f=fixture(),c=f.client(mode,{beforeDispatch:()=>{}});for(let i=0;i<max;i++)await c.request('owner');await assert.rejects(c.request('owner'));assert.equal(f.calls.length,max);}});
test('one-shot file reservation/journal and locks remain required in CLI implementation',()=>{const source=fs.readFileSync(require.resolve('./reconcile-blommers-historical-claims.cjs'),'utf8');assert(source.includes("fs.mkdirSync(out,{mode:0o700})"));assert(source.includes("opt.mode==='apply'?'-apply'"));assert(source.includes("fs.openSync(out+'/events.ndjson','wx'"));assert(source.includes("/.state/my-coffee-explorer/apply.lock"));assert(source.includes("/.product-only-entity-locks/"));assert(source.includes('fs.fsyncSync(fd)'));assert(source.includes("process.env.NODE_TLS_REJECT_UNAUTHORIZED='1'"));});
