'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),h=require('./retire-blommers-historical-claim.cjs'),p=h.loadPlan(),clone=x=>JSON.parse(JSON.stringify(x));
const AT='2026-09-27T17:30:00.750Z';
function runtime(){return{at:AT,code_sha256:p.create_claim_source.sha256,history_sha256:p.historical_log.sha256,launchers:[{pid:93940,started_at:'2026-09-27T13:13:32Z'}],nodes:[{pid:93949,started_at:'2026-09-27T13:13:32Z'}],lock_pid:93940,current_log:{bytes:262144,owner_or_claim_match:false},direct_claim_or_owner_process:false,unbound_index_process:false};}
function response(url,rows,status=200){const r=new Response(JSON.stringify(rows),{status,headers:{'content-type':'application/json','content-range':Array.isArray(rows)&&rows.length?'0-'+(rows.length-1)+'/*':'*/*'}});Object.defineProperty(r,'url',{value:url});return r;}
function fixture(){let time=Date.parse(AT);const state={owner:clone(p.owner),claim:clone(p.expected),otherRuns:[]},calls=[],events=[];let hook=null;const f={state,calls,events,now:()=>time,advance:n=>time+=n,setHook:x=>hook=x,proof:()=>h.assessRuntime({...runtime(),at:new Date(time).toISOString()},p,time)};
 f.client=(mode='preview',extra={})=>h.createClient({plan:p,key:'test',mode,now:()=>time,wait:async n=>time+=n,event:e=>events.push(e),delegate:async(url,req)=>{calls.push({url,method:req.method,body:req.body&&JSON.parse(req.body)});time+=50;const u=new URL(url),q=u.searchParams;if(hook){const result=hook({url,req,q,state,calls});if(result)return result;}if(req.method==='PATCH'){const match=[...q].filter(([k])=>k!=='select').every(([k,v])=>v==='is.null'?state.claim[k]===null:v==='eq.'+(typeof state.claim[k]==='object'?JSON.stringify(state.claim[k]):String(state.claim[k])));if(!match)return response(url,[]);Object.assign(state.claim,JSON.parse(req.body));state.claim.finished_at=state.claim.finished_at.replace('.750Z','.75+00:00').replace('Z','+00:00');return response(url,[clone(state.claim)]);}assert.equal(req.method,'GET');return response(url,u.pathname.endsWith('/entities')?[clone(state.owner)]:q.has('status')?clone(state.otherRuns):[clone(state.claim)]);},...extra});return f;}
async function preview(f){return h.execute({plan:p,client:f.client(),mode:'preview',proof:f.proof,record:e=>f.events.push(e),now:f.now});}
async function apply(f,v,extra={}){return h.execute({plan:p,client:f.client('apply',{beforeWrite:()=>{h.validatePreview(v,p,f.now());f.proof();}}),mode:'apply',preview:v,proof:f.proof,record:e=>f.events.push(e),now:f.now,...extra});}
test('frozen exact claim/owner evidence pins load',()=>{assert.equal(p.expected.id,h.ID);assert.equal(p.expected.entity_id,h.OWNER);assert.equal(p.expected.status,'running');assert.deepEqual(p.expected.meta,{});});
test('only three fields patched with honest current time',()=>{const patch=h.patchFor(p,p.expected,AT);assert.deepEqual(Object.keys(patch),['status','finished_at','error']);assert.equal(patch.status,'failed');assert.equal(patch.finished_at,AT);assert.match(patch.error,/reconciliation time, not historical finish time/);assert.throws(()=>h.patchFor(p,p.expected,'2026-07-11T19:48:00Z'));assert.throws(()=>h.patchFor(p,{...p.expected,pages_visited:1},AT));});
test('every captured claim field included in CAS, including meta JSON and nulls',()=>{const d=h.requestFor('patch',p,h.patchFor(p,p.expected,AT)),u=new URL(d.url);assert.equal(d.method,'PATCH');assert.equal(u.origin,h.ORIGIN);assert.equal(u.pathname,'/rest/v1/crawl_runs');for(const[k,v]of Object.entries(p.expected))assert.equal(u.searchParams.get(k),v===null?'is.null':'eq.'+(typeof v==='object'?JSON.stringify(v):String(v)));assert.equal(u.searchParams.get('meta'),'eq.{}');});
test('counter/meta/completed/other payloads forbidden',()=>{for(const extra of [{pages_visited:1},{meta:{reconciled:true}},{status:'completed'},{entity_id:'other'}])assert.throws(()=>h.requestFor('patch',p,{...h.patchFor(p,p.expected,AT),...extra}));assert.throws(()=>h.requestFor('delete',p));});
test('default offline; preview and apply need independent audit hash',()=>{assert.equal(h.cli([]).mode,'check');for(const a of [['--preview'],['--apply'],['--preview','--review-sha','x'],['--apply','p','a'.repeat(64),'--review-sha','b'.repeat(64),'--yes']])assert.throws(()=>h.cli(a));assert.equal(h.cli(['--preview','--review-sha','a'.repeat(64)]).mode,'preview');});
test('review must independently bind exact helper and plan',()=>{const a={status:'PASS',independent:true,helper_sha256:h.helperSha(),plan_sha256:h.PLAN_SHA};assert.doesNotThrow(()=>h.validateReview(a));for(const change of [{status:'hold'},{independent:false},{helper_sha256:'x'},{plan_sha256:'x'}])assert.throws(()=>h.validateReview({...a,...change}));});
test('preview is exactly3GET and zero writes',async()=>{const f=fixture(),v=await preview(f);assert.equal(v.requests,3);assert.equal(v.writes,0);assert.deepEqual(f.calls.map(c=>c.method),['GET','GET','GET']);});
test('apply uses5requests,claim last before1PATCH,verified readback preserving counters/meta',async()=>{const f=fixture(),v=await preview(f);f.calls.length=0;const r=await apply(f,v);assert.equal(r.requests,5);assert.equal(r.writes,1);assert.deepEqual(f.calls.map(c=>c.method),['GET','GET','GET','PATCH','GET']);for(const[k,val]of Object.entries(p.expected))if(!['status','finished_at','error'].includes(k))assert.deepEqual(r.after[k],val);assert.equal(r.after.status,'failed');assert.equal(r.worker_changed,false);assert.equal(r.inventory_complete,false);assert(Date.parse(r.after.finished_at)>Date.parse(v.at));});
test('changed owner/current claim/counters/meta each block before patch',async()=>{for(const change of [f=>f.state.owner.name='other',f=>f.state.claim.finished_at=AT,f=>f.state.claim.pages_visited=1,f=>f.state.claim.meta={new:true}]){const f=fixture();change(f);await assert.rejects(preview(f));assert(!f.calls.some(c=>c.method==='PATCH'));}});
test('new active Blommers claim stops before target claim or mutation',async()=>{const f=fixture();f.state.otherRuns=[{id:'new'}];await assert.rejects(preview(f),/another_owner_claim/);assert.equal(f.calls.length,2);});
test('expired/future/foreign preview refuses before live calls',async()=>{const f=fixture(),v=await preview(f);for(const q of [{...v,at:'2000-01-01T00:00:00Z'},{...v,at:'2100-01-01T00:00:00Z'},{...v,helper_sha256:'x'}]){const before=f.calls.length;await assert.rejects(apply(f,q));assert.equal(f.calls.length,before);}});
test('changed claim at final CAS returns0 and is not replayed',async()=>{const f=fixture(),v=await preview(f);await assert.rejects(apply(f,v,{record:e=>{if(e.event==='mutation_attempt_no_retry')f.state.claim.pages_visited=1;}}),/exact_one/);assert.equal(f.calls.filter(c=>c.method==='PATCH').length,1);});
test('returned counter/meta drift is rejected',()=>{const patch=h.patchFor(p,p.expected,AT);for(const extra of [{pages_discovered:1},{meta:{changed:true}}])assert.throws(()=>h.verifyRow([{...p.expected,...patch,...extra}],p.expected,patch),/preservation/);});
test('SQL equivalent timestamp spellings pass but one microsecond change fails',()=>{const patch=h.patchFor(p,p.expected,AT),row={...p.expected,...patch,finished_at:'2026-09-27T17:30:00.75+00:00'};assert.doesNotThrow(()=>h.verifyRow([row],p.expected,patch));assert.throws(()=>h.verifyRow([{...row,created_at:'2026-07-11T19:48:08.957474+00:00'}],p.expected,patch),/created_at/);});
test('after-readback drift never reported verified',async()=>{const f=fixture(),v=await preview(f);await assert.rejects(apply(f,v,{record:e=>{if(e.event==='mutation_returned_preserved')f.state.claim.coffees_found=1;}}));assert.equal(f.calls.filter(c=>c.method==='PATCH').length,1);});
test('current newer launcher/lock/other-owner log accepted; no worker stops',()=>{const r=h.assessRuntime(runtime(),p,Date.parse(AT));assert.equal(r.lock_pid,93940);});
test('no known legacy worker accepted only without lock/node',()=>{assert.doesNotThrow(()=>h.assessRuntime({...runtime(),launchers:[],nodes:[],lock_pid:null,current_log:null},p,Date.parse(AT)));assert.throws(()=>h.assessRuntime({...runtime(),launchers:[]},p,Date.parse(AT)));});
test('orphan index process cannot be mistaken for no crawler',()=>{assert.throws(()=>h.assessRuntime({...runtime(),launchers:[],nodes:[],lock_pid:null,current_log:null,unbound_index_process:true},p,Date.parse(AT)),/unbound_index/);});
for(const[label,mutate]of [['old worker',s=>s.nodes[0].started_at='2026-07-11T19:00:00Z'],['lock mismatch',s=>s.lock_pid=123],['missing log',s=>s.current_log=null],['recent Blommers activity',s=>s.current_log.owner_or_claim_match=true],['claim process',s=>s.direct_claim_or_owner_process=true],['source changed',s=>s.code_sha256='x'],['historical proof changed',s=>s.history_sha256='x'],['stale runtime',s=>s.at='2026-09-27T17:00:00Z'],['ambiguous launchers',s=>s.launchers.push({...s.launchers[0],pid:1})]])test('runtime proof refuses '+label,()=>{const s=runtime();mutate(s);assert.throws(()=>h.assessRuntime(s,p,Date.parse(AT)));});
test('fresh runtime refusal after pacing prevents actual PATCH',async()=>{const f=fixture(),c=f.client('apply',{beforeWrite:()=>{throw Error('worker changed');}});await assert.rejects(c.request('patch',h.patchFor(p,p.expected,AT)));assert.equal(f.calls.length,0);});
test('preview client cannot PATCH',async()=>{const f=fixture(),c=f.client();await assert.rejects(c.request('patch',h.patchFor(p,p.expected,AT)));assert.equal(f.calls.length,0);});
test('ambiguous500 PATCH latches without replay',async()=>{const f=fixture();f.setHook(({url,req})=>req.method==='PATCH'?response(url,{code:'57014'},500):null);const c=f.client('apply'),patch=h.patchFor(p,p.expected,AT);await assert.rejects(c.request('patch',patch));await assert.rejects(c.request('patch',patch));assert.equal(f.calls.length,1);});
for(const[label,reply]of [['changed URL',u=>response(u+'x',[])],['missing URL',()=>new Response('[]')],['bad JSON type',u=>{const r=response(u,[]);r.headers.set('content-type','text/html');return r;}],['bad content range',u=>{const r=response(u,[]);r.headers.set('content-range','0-0/*');return r;}],['row overflow',u=>response(u,[{},{},{}])]])test('transport stops '+label,async()=>{const f=fixture();f.setHook(({url})=>reply(url));const c=f.client();await assert.rejects(c.request('claim'));await assert.rejects(c.request('claim'));assert.equal(f.calls.length,1);});
test('500ms completion pacing loops after early wake',async()=>{let time=0,n=0,end=0;const waits=[];const c=h.createClient({plan:p,key:'x',mode:'preview',now:()=>time,wait:async ms=>{waits.push(ms);time+=ms===500?499:ms;},delegate:async u=>{if(n++)assert(time-end>=500);time+=1200;end=time;return response(u,[]);}});await c.request('otherRuns');await c.request('otherRuns');assert.deepEqual(waits,[500,1]);});
test('deadline reached while pacing blocks second request',async()=>{let time=0,n=0;const c=h.createClient({plan:p,key:'x',mode:'preview',now:()=>time,wait:async()=>time=120001,delegate:async u=>{n++;return response(u,[]);}});await c.request('otherRuns');await assert.rejects(c.request('otherRuns'));assert.equal(n,1);});
test('journal failure blocks mutation dispatch',async()=>{const f=fixture(),c=f.client('apply',{event:()=>{throw Error('disk');}});await assert.rejects(c.request('patch',h.patchFor(p,p.expected,AT)));assert.equal(f.calls.length,0);});
